### ISSUE TITLE
map search functionality

### ISSUE THREAD

**Issue by colinbeier** [caryfitzhugh/NYCCSC-map-viewer#100]
Right now it appears the search box is only connected to a database of place names.  Are we going to connect this to the pgSQL table that contains the metadata for the layers?  

Or is there some other plan to make the layers searchable?  This is pretty important.  

I know there has been some discussion about moving the search function to the Layers tab.  But I want to see the search working - to get places or layers - first.  Then we can decide if / how to move it from the tab.

**Comment by sasignell** [comment]
Actually, this is already an issue (#83) and I believe Cary is working on
this today.

On Thu, Dec 10, 2015 at 9:24 AM, colinbeier <notifications@github.com>
wrote:

> Right now it appears the search box is only connected to a database of
> place names. Are we going to connect this to the pgSQL table that contains
> the metadata for the layers?
>
> Or is there some other plan to make the layers searchable? This is pretty
> important.
>
> I know there has been some discussion about moving the search function to
> the Layers tab. But I want to see the search working - to get places or
> layers - first. Then we can decide if / how to move it from the tab.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/caryfitzhugh/NYCCSC-map-viewer/issues/100>.
>



-- 
Steve Signell
Frontier Spatial, L.L.C.
1062 Dean St.
Schenectady, NY 12309
518-232-1008
frontierspatial.com
steve@frontierspatial.com

**Comment by colinbeier** [comment]
my bad!  will close this one.
