### ISSUE TITLE
CLIMAID Precipitation Layer

### ISSUE THREAD

**Issue by caryfitzhugh** [caryfitzhugh/NYCCSC-map-viewer#104]
Add the precip layer.  Like climaid temp layer.

Same controls, just precip data.  brown == less rain -> blue / darkblue == more rain

[ClimAID_precip_pcntdeltas.geojson.zip](https://github.com/caryfitzhugh/NYCCSC-map-viewer/files/82927/ClimAID_precip_pcntdeltas.geojson.zip)

**Comment by caryfitzhugh** [comment]
@colinbeier what is the scale here? inches change? cm change?

**Comment by caryfitzhugh** [comment]
check it out.  Not too much variation in the data.

Converted it from the geojson that I had into our "custom" format that the temp deltas were in.

It's quite compact acrtually, about 1.7MB per file.  Which is pretty small.  Compressed with gzip it is even tinier.

**Comment by caryfitzhugh** [comment]
check it out on the gh-pages site.

I aslo added a task for Steve to help me put these json files in the geoserver www dir.  
They will serve faster, and we can have apache gzip them (I hope) ?

g;night!

**Comment by colinbeier** [comment]
cm

Colin Beier
SUNY ESF

On Jan 11, 2016 6:24 PM, Cary FitzHugh <notifications@github.com> wrote:

@colinbeier<https://github.com/colinbeier> what is the scale here? inches change? cm change?
