### ISSUE TITLE
Edit legend caption for NARCCAP

### ISSUE THREAD

**Issue by colinbeier** [caryfitzhugh/NYCCSC-map-viewer#106]
It currently reads "temperature change" but NARCCAP data is not a delta, it is an actual value

should read "projected temperature" (or precip) for NARCCAP... the ClimAID caption stays the same.

**Comment by caryfitzhugh** [comment]
this should involve setting the legend text in the renderer (as we do with the color ranges as well).
So narccap would set "color_legend_text" = X
and climaid would set it to something different.
