### ISSUE TITLE
Converting PRISM UI to d3?

### ISSUE THREAD

**Issue by colinbeier** [caryfitzhugh/NYCCSC-map-viewer#110]
Guys, the NARCCAP and ClimAID data look and work so frickin good with d3.  I think the historical data (PRISM) could use the same treatment, for consistency if nothing else. 

Cary, how much time would you need to convert the PRISM layers to the same d3 and legend format as NARCCAP and ClimAID?

**Comment by caryfitzhugh** [comment]
@sasignell what kind of data is it?
we have counties and watershed boundaries, but we'd need climate divisions as a geojson.
and then steve, what does the PRISM data look like?

**Comment by sasignell** [comment]
The path is similar (substituting prism for narccap):

https://s3.amazonaws.com/nyccsc-cache.nrcc.cornell.edu/prism/area/prod_
season

Where area is one of {state, county, basin}, season is {ANN, MAM, JJA, SON,
DJF, Jan, Feb…} and prod is one of {pcpn, mint, maxt, avgt, gdd50, hdd65,
cdd65, tx90, tx95, tx100, tn32, tn0, pcpn_1, pcpn_2, pcpn_4}.

here's a sample:

https://s3.amazonaws.com/nyccsc-cache.nrcc.cornell.edu/prism/county/mint_ANN


You should be able to joint these to the existing geometries using the
UIDs.

On Mon, Jan 11, 2016 at 6:43 PM, Cary FitzHugh <notifications@github.com>
wrote:

> @sasignell <https://github.com/sasignell> what kind of data is it?
> we have counties and watershed boundaries, but we'd need climate divisions
> as a geojson.
> and then steve, what does the PRISM data look like?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/caryfitzhugh/NYCCSC-map-viewer/issues/110#issuecomment-170733935>
> .
>



-- 
Steve Signell
Frontier Spatial, L.L.C.
1062 Dean St.
Schenectady, NY 12309
518-232-1008
frontierspatial.com
steve@frontierspatial.com

**Comment by caryfitzhugh** [comment]
Oh man, that's pretty simple.

Do we have a geometry file for the watersheds (or huc8) or... I don't know
it's name, but I know we only have geojson boundaries for 2 things, and the
prism data is connected to 3 :)

**Comment by sasignell** [comment]
lets ditch the climate divisions for now-- is that OK Colin?

On Mon, Jan 11, 2016 at 8:01 PM, Cary FitzHugh <notifications@github.com>
wrote:

> Oh man, that's pretty simple.
>
> Do we have a geometry file for the watersheds (or huc8) or... I don't know
> it's name, but I know we only have geojson boundaries for 2 things, and the
> prism data is connected to 3 :)
>
> On Mon, Jan 11, 2016 at 7:25 PM, Steve Signell <notifications@github.com>
> wrote:
>
> > The path is similar (substituting prism for narccap):
> >
> > https://s3.amazonaws.com/nyccsc-cache.nrcc.cornell.edu/prism/area/prod_
> > season
> >
> > Where area is one of {state, county, basin}, season is {ANN, MAM, JJA,
> SON,
> > DJF, Jan, Feb…} and prod is one of {pcpn, mint, maxt, avgt, gdd50, hdd65,
> > cdd65, tx90, tx95, tx100, tn32, tn0, pcpn_1, pcpn_2, pcpn_4}.
> >
> > here's a sample:
> >
> >
> >
> https://s3.amazonaws.com/nyccsc-cache.nrcc.cornell.edu/prism/county/mint_ANN
> >
> >
> > You should be able to joint these to the existing geometries using the
> > UIDs.
> >
> > On Mon, Jan 11, 2016 at 6:43 PM, Cary FitzHugh <notifications@github.com
> >
> > wrote:
> >
> > > @sasignell <https://github.com/sasignell> what kind of data is it?
> > > we have counties and watershed boundaries, but we'd need climate
> > divisions
> > > as a geojson.
> > > and then steve, what does the PRISM data look like?
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/caryfitzhugh/NYCCSC-map-viewer/issues/110#issuecomment-170733935
> > >
> > > .
> > >
> >
> >
> >
> > --
> > Steve Signell
> > Frontier Spatial, L.L.C.
> > 1062 Dean St.
> > Schenectady, NY 12309
> > 518-232-1008
> > frontierspatial.com
> > steve@frontierspatial.com
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/caryfitzhugh/NYCCSC-map-viewer/issues/110#issuecomment-170741751
> >
> > .
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/caryfitzhugh/NYCCSC-map-viewer/issues/110#issuecomment-170747073>
> .
>



-- 
Steve Signell
Frontier Spatial, L.L.C.
1062 Dean St.
Schenectady, NY 12309
518-232-1008
frontierspatial.com
steve@frontierspatial.com

**Comment by colinbeier** [comment]
Yes dump em

Colin Beier
SUNY ESF

On Jan 11, 2016 9:11 PM, Steve Signell <notifications@github.com> wrote:
lets ditch the climate divisions for now-- is that OK Colin?

On Mon, Jan 11, 2016 at 8:01 PM, Cary FitzHugh <notifications@github.com>
wrote:

> Oh man, that's pretty simple.
>
> Do we have a geometry file for the watersheds (or huc8) or... I don't know
> it's name, but I know we only have geojson boundaries for 2 things, and the
> prism data is connected to 3 :)
>
> On Mon, Jan 11, 2016 at 7:25 PM, Steve Signell <notifications@github.com>
> wrote:
>
> > The path is similar (substituting prism for narccap):
> >
> > https://s3.amazonaws.com/nyccsc-cache.nrcc.cornell.edu/prism/area/prod_
> > season
> >
> > Where area is one of {state, county, basin}, season is {ANN, MAM, JJA,
> SON,
> > DJF, Jan, Feb…} and prod is one of {pcpn, mint, maxt, avgt, gdd50, hdd65,
> > cdd65, tx90, tx95, tx100, tn32, tn0, pcpn_1, pcpn_2, pcpn_4}.
> >
> > here's a sample:
> >
> >
> >
> https://s3.amazonaws.com/nyccsc-cache.nrcc.cornell.edu/prism/county/mint_ANN
> >
> >
> > You should be able to joint these to the existing geometries using the
> > UIDs.
> >
> > On Mon, Jan 11, 2016 at 6:43 PM, Cary FitzHugh <notifications@github.com
> >
> > wrote:
> >
> > > @sasignell <https://github.com/sasignell> what kind of data is it?
> > > we have counties and watershed boundaries, but we'd need climate
> > divisions
> > > as a geojson.
> > > and then steve, what does the PRISM data look like?
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/caryfitzhugh/NYCCSC-map-viewer/issues/110#issuecomment-170733935
> > >
> > > .
> > >
> >
> >
> >
> > --
> > Steve Signell
> > Frontier Spatial, L.L.C.
> > 1062 Dean St.
> > Schenectady, NY 12309
> > 518-232-1008
> > frontierspatial.com
> > steve@frontierspatial.com
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/caryfitzhugh/NYCCSC-map-viewer/issues/110#issuecomment-170741751
> >
> > .
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/caryfitzhugh/NYCCSC-map-viewer/issues/110#issuecomment-170747073>
> .
>



--
Steve Signell
Frontier Spatial, L.L.C.
1062 Dean St.
Schenectady, NY 12309
518-232-1008
frontierspatial.com
steve@frontierspatial.com

**Comment by caryfitzhugh** [comment]
ok!  easy peasy.
I noticed that we called them "Basins" on one layer, and "watershed" in
another.
Is there a common name we could use for both?

**Comment by colinbeier** [comment]
let them all be called watersheds :)

Colin Beier
SUNY ESF

On Jan 12, 2016 9:49 AM, Cary FitzHugh <notifications@github.com> wrote:
ok! easy peasy.
I noticed that we called them "Basins" on one layer, and "watershed" in
another.
Is there a common name we could use for both?

**Comment by caryfitzhugh** [comment]
what is the prism data precipitation and temp scales?
F and cm?

**Comment by caryfitzhugh** [comment]
what *are* the...

**Comment by caryfitzhugh** [comment]
according to this it is Inches and F

**Comment by caryfitzhugh** [comment]
http://www.prism.oregonstate.edu/mtd/

**Comment by colinbeier** [comment]
Two tweaks for PRISM:

1. We should only show the mean value from 1980-2014 (as the layer title indicates).  

Right now you can scroll through the entire 20th century year by year.  That's an impressive feat for the UI ... but the problem is that PRISM data is not all that reliable pre-1950.  We may want to show a series of 30 yr means for PRISM (e.g., 1920-1949, 1950-1979, 1980-2009, etc) but I need to clear that with Art and NYSERDA first.  For now lets keep it simple and just show the 1980-2014 mean value.  

2. The watersheds don't seem to work on the gh pages.  I tried both precip and temp.  Not sure what's going on there.

**Comment by caryfitzhugh** [comment]
Good catch on the watersheds. I'm looking at it now - soe CORS issue with the CDN I think.  

And I'll just limit it to 1980 - 2014.  Having some ability to aggregate older values would be difficult with the slider... SO I'm hoping no one asks for that. :)

**Comment by caryfitzhugh** [comment]
the watershed issue is still here.  moving to a new bug.

**Comment by colinbeier** [comment]
how is d3 scaling the color bar for the PRISM layers?  a few of the months lead to polgyons that are basically all the same color, i.e., a very narrow range of the data.  

cc-ing this directly to your emails in case the screen cap does not show up in gh

**Comment by caryfitzhugh** [comment]
I believe the color bar is calculated by including all the values for all
the years for that set of data (so all years, county, Annual).  Or
all years, watershed, MAM)
.
If you want it something different, just tell me.  Though, not sure what
else it could really be.  When you select December, I can't really
calculate anything other than those december data points across 1 year, 5
years, 10 years, or N years...

Lemme know!
Thanks
Cary

**Comment by colinbeier** [comment]
That's what I thought, but for PRISM there should be only the 1980-2014 mean for whatever variable / polygon combo. So if each dataset should yield it's own color bar based on its range, then the min and max colors should always be present in the map, right?  But a few of the layers / datasets seem to draw all one color, especially for precip x watersheds.

We also don't need the year slider for PRISM :)

Colin Beier
SUNY ESF

On Jan 14, 2016 8:54 PM, Cary FitzHugh <notifications@github.com> wrote:
I believe the color bar is calculated by including all the values for all
the years for that set of data (so all years, county, Annual). Or
all years, watershed, MAM)
.
If you want it something different, just tell me. Though, not sure what
else it could really be. When you select December, I can't really
calculate anything other than those december data points across 1 year, 5
years, 10 years, or N years...

Lemme know!
Thanks
Cary

**Comment by caryfitzhugh** [comment]
oh oh oh..   so PRISM should be 1980-2014, and just the average across
those dates? (hence no date slider?)
And the legend should be for (say) the max / min of 1980-2014 for
December.  Right?

**Comment by colinbeier** [comment]
Yep :)

Colin Beier
SUNY ESF

On Jan 14, 2016 9:23 PM, Cary FitzHugh <notifications@github.com> wrote:
oh oh oh.. so PRISM should be 1980-2014, and just the average across
those dates? (hence no date slider?)
And the legend should be for (say) the max / min of 1980-2014 for
December. Right?

**Comment by colinbeier** [comment]
Sorry to reopen... but a few notes / edits on PRISM: 

- The units for precipitation are off.  I know that PRISM provides PPT data in inches, but I can assure you that nowhere in NYS gets 70+ (6 feet) of rain each year, and this data does not include snow.  Either we are missing a decimal point, or these are in cm.  Since these data are summarized by ACIS, we should check with them about units.  

- We should remove the year slider, as noted above.  If we are just pushing the 1980-2014 average, which can come directly from ACIS, then we don't need d3 to calculate the mean, and we are only using the d3 to render the color bar.  

Here is an example of where the max and min values don't seem to appear in the map:
![image](https://cloud.githubusercontent.com/assets/7375034/12355441/a7637f36-bb6a-11e5-9303-bafa950bedc8.png)

The drawing is also a bit laggy / slow, so I'm not sure what is going on... 

My only intention in moving PRISM to d3 was to have a dynamic color bar so that each dataset / sublayer would be drawn with the maximum color spread possible - and to be consistent with NARCCAP and ClimAID.   Sorry if I've made this more complex than necessary.

**Comment by caryfitzhugh** [comment]
I'm pusihng some code up now which fixes the legend.

The lagginess is mainly b/c the PRISM files are large, and every change to
the settings causes us to have to go request a new file from ACIS.
If we want it sped up, we could download their files, and cut off
everything that is not 1980 - 2014.
Heck, we could even pre-process the means and extent then as well.  But if
they update things, we have to re-do that work.

I think the big lag is the file loading.

Is there a file from ACIS
https://s3.amazonaws.com/nyccsc-cache.nrcc.cornell.edu/prism/.....

Which just shows 1980-2014?

How can I find out - who could I email to determine the units in the file?

**Comment by colinbeier** [comment]
I think the original PRISM layer - before converting to d3 - was just pulling the mean 1980-2014 files from ACIS.  

I'll email Bill and Art about units

**Comment by caryfitzhugh** [comment]
I believe that data was pre-processed by steve based on the files on amazon (which is what I'm pulling in directly).  

Try it out, if it's still too laggy we can do something else -- pulling down the data to pre-process it isn't the end of the world. (I don't think).
@sasignell  ?

**Comment by sasignell** [comment]
I did preprocess the data, which can be accessed as geojson via the
geoserver api.  I can work on this during nap today

**Comment by caryfitzhugh** [comment]
what I have may be "good enough"...  

@colinbeier should we keep looking athte geojson / etc

Or go with what is on the gh-pages site?

Should I release today? CLIMAID, some bug-fixes... ?
I can also remove the one layer (NOAA_SLR I think).

**Comment by colinbeier** [comment]
what's there is pretty good!   works great as far as I can tell.  the color bars are dialed in.. thanks for fixing!  

please DO NOT remove NOAA_SLR.  the layer to remove is slr_vuln (Coastal Vulnerability to Sea-Level Rise)

i would like to make edits to the layer descriptions for NARCCAP and ClimAID before releasing.  Steve, the correct text is here https://github.com/caryfitzhugh/NYCCSC-map-viewer/issues/105

also in this release, don't forget the layer drag/drop feature was added.

**Comment by caryfitzhugh** [comment]
haha... right. Not NOAA_SLR.

Ok - so release is blocked pending 2 things:
fixing the text and removing the slr_vuln

I'll release a preview to gh-pages sometime after lunch, and we can
thumb-up it and release before the COB.

>
>
