### ISSUE TITLE
Move climaid data files to geo server

### ISSUE THREAD

**Issue by caryfitzhugh** [caryfitzhugh/NYCCSC-map-viewer#111]
@sasignell the two new climaid files in src/data should go onto the WWW of the geoserver.

So I can get them with CORS.

And if possible we should make sure apache is gzipping them.  The 1.7 MB files compress with gzip down to like 200k or something nuts.

When this is done, I can just point the UI at the new URLs

**Comment by sasignell** [comment]
Ok I moved them over, should be available as is and with .gz extensions.
Also check out basin.topojson.gz

On Mon, Jan 11, 2016 at 6:45 PM, Cary FitzHugh <notifications@github.com>
wrote:

> @sasignell <https://github.com/sasignell> the two new climaid files in
> src/data should go onto the WWW of the geoserver.
>
> So I can get them with CORS.
>
> And if possible we should make sure apache is gzipping them. The 1.7 MB
> files compress with gzip down to like 200k or something nuts.
>
> When this is done, I can just point the UI at the new URLs
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/caryfitzhugh/NYCCSC-map-viewer/issues/111>.
>



-- 
Steve Signell
Frontier Spatial, L.L.C.
1062 Dean St.
Schenectady, NY 12309
518-232-1008
frontierspatial.com
steve@frontierspatial.com

**Comment by caryfitzhugh** [comment]
Sweet! Thanks!

**Comment by caryfitzhugh** [comment]
blarg.   is it supposed to be:
http://52.2.5.122:8080/geoserver/www/climaid_temp_deltas.json
and
http://52.2.5.122:8080/geoserver/www/climaid_precip_deltas.json

I only could retrieve the first one. ?
I have added them both to git, in the server/data/www directory, FWIW.

But this is looking really good!
1.9MB file, was only 168kb gzipped!
![developer tools - http 52 2 5 122 8080 geoserver www climaid_temp_deltas json 2016-01-12 10-00-03](https://cloud.githubusercontent.com/assets/445848/12266851/554dad42-b913-11e5-9a27-8debb61addfb.png)

**Comment by sasignell** [comment]
OK I pushed the changes... give it a whirl and let me know how it goes

On Tue, Jan 12, 2016 at 10:01 AM, Cary FitzHugh <notifications@github.com>
wrote:

> blarg. is it supposed to be:
> http://52.2.5.122:8080/geoserver/www/climaid_temp_deltas.json
> and
> http://52.2.5.122:8080/geoserver/www/climaid_precip_deltas.json
>
> I only could retrieve the first one. ?
> I have added them both to git, in the server/data/www directory, FWIW.
>
> But this is looking really good!
> 1.9MB file, was only 168kb gzipped!
> [image: developer tools - http 52 2 5 122 8080 geoserver www
> climaid_temp_deltas json 2016-01-12 10-00-03]
> <https://cloud.githubusercontent.com/assets/445848/12266851/554dad42-b913-11e5-9a27-8debb61addfb.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/caryfitzhugh/NYCCSC-map-viewer/issues/111#issuecomment-170939833>
> .
>



-- 
Steve Signell
Frontier Spatial, L.L.C.
1062 Dean St.
Schenectady, NY 12309
518-232-1008
frontierspatial.com
steve@frontierspatial.com

**Comment by caryfitzhugh** [comment]
pushed-  tested - bang! :) done!

**Comment by caryfitzhugh** [comment]
released the gh-pages

**Comment by sasignell** [comment]
Very cool.  Just one thing-- add a decimal place for the symbology
gradient.  Looking good good good.  Is Prism next on the chopping block?

On Tue, Jan 12, 2016 at 11:13 AM, Cary FitzHugh <notifications@github.com>
wrote:

> released the gh-pages
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/caryfitzhugh/NYCCSC-map-viewer/issues/111#issuecomment-170960873>
> .
>



-- 
Steve Signell
Frontier Spatial, L.L.C.
1062 Dean St.
Schenectady, NY 12309
518-232-1008
frontierspatial.com
steve@frontierspatial.com

**Comment by caryfitzhugh** [comment]
I believe PRISM is next in the queue. 
Adding another bit of precision, causes us to lose a bit of space.

I can stagger the text, so it's easier to read the number.

![nycscc map viewer 2016-01-12 11-40-53](https://cloud.githubusercontent.com/assets/445848/12269872/78cd5868-b921-11e5-90a4-8a81aa5f3d70.png)

Just not stagger it.
![nycscc map viewer 2016-01-12 11-42-39](https://cloud.githubusercontent.com/assets/445848/12269910/9da6dbb4-b921-11e5-8756-59d93bdbfc54.png)

Maybe go with a smaller font? 

Or hide every other text label.

![nycscc map viewer 2016-01-12 11-44-24](https://cloud.githubusercontent.com/assets/445848/12269964/d990d6ca-b921-11e5-8e0e-7803be040a71.png)

Opinions?

**Comment by colinbeier** [comment]
One significant digit will suffice for all of these.  Hopefully that solves the space problem...

**Comment by caryfitzhugh** [comment]
ok - went back to one digit.

**Comment by sasignell** [comment]
I was actually referring to the precip only, which I think does need a second digit, or you just get a bunch of .1 and .2 values
