### ISSUE TITLE
NYSERDA & NESCAUM comments on map viewer 

### ISSUE THREAD

**Issue by colinbeier** [caryfitzhugh/NYCCSC-map-viewer#115]
FYI - I just got this from Lisa. I will be going through the whole thing, to pull out and prioritize the primary issues that we might address before launch, after launch, or never.... 

Feel free to look through this if you like.  I'll try my best to translate it to our workflow.  

[Jan 2016 map comments.docx](https://github.com/caryfitzhugh/NYCCSC-map-viewer/files/92024/Jan.2016.map.comments.docx)

**Comment by caryfitzhugh** [comment]
I think this can be closed... right? @colinbeier  since ou added it in tasks ...

**Comment by colinbeier** [comment]
Yep.
