### ISSUE TITLE
Add layer: DEC waterbody classification

### ISSUE THREAD

**Issue by colinbeier** [caryfitzhugh/NYCCSC-map-viewer#118]
Link to NYS GIS Clearinghouse
http://gis.ny.gov/gisdata/inventories/details.cfm?DSID=1259

Here's the shapefile
http://gis.ny.gov/gisdata/fileserver/?DSID=1259&file=aa_aas_watersheds.zip

Should be easy... other than we have to serve it.  

Please look into this and comment:  easy - moderate - hard

**Comment by sasignell** [comment]
easy (~1/2hr)

**Comment by sasignell** [comment]
Here's what the linked shapefile looks like, and it has NO attributes except keys and geometry.  Is that what you're expecting?

![image](https://cloud.githubusercontent.com/assets/4191479/12582777/1f598e68-c40d-11e5-9239-dd3d1f0fce36.png)

**Comment by colinbeier** [comment]
Looks like first order catchments, no attributes because they are only a single classification (see below).

This dataset provides an approximation of the watershed boundaries of water bodies classified as AA and AAs in Title 6 of the Official Compilation of Codes, Rules and Regulations of the State of New York (6NYCRR) Part 800 et seq. and their tributaries. This information shall be used by the owner of a regulated construction activity to see if their project is eligible for coverage under the NYS Department of Environmental Conservation's State Pollutant Discharge Elimination Discharge System (SPDES) General Permit for Storm water Discharges from Construction Activity (see Part I.D.7. and 8. in GP-0-10-001). 

I'll forward this along to Lisa et al.  and see what they say.

**Comment by caryfitzhugh** [comment]
@colinbeier status?  Should it be added?  by @sasignell

**Comment by colinbeier** [comment]
Last I heard was negatory... but will confirm with Lisa.

Colin Beier
SUNY ESF

On Feb 8, 2016 4:16 PM, Cary FitzHugh <notifications@github.com> wrote:

@colinbeier<https://github.com/colinbeier> status? Should it be added? by @sasignell<https://github.com/sasignell>

**Comment by sasignell** [comment]
Closing this one based on comments, above
