### ISSUE TITLE
Add layer: DEC wells (oil, gas, etc)

### ISSUE THREAD

**Issue by colinbeier** [caryfitzhugh/NYCCSC-map-viewer#119]
Item page on NYS GIS Clearinghouse
http://gis.ny.gov/gisdata/inventories/details.cfm?DSID=1272

The data is viewable (kinda) on this dumpster fire of a web map
http://www.dec.ny.gov/imsmaps/minerals/viewer.htm

Also can download as csv from here.  Might be way to go, convert to geojson?  
ftp://ftp.dec.state.ny.us/dmn/zip/wellDOS.zip

Please comment to rate for time/effort: easy - moderate - hard

**Comment by sasignell** [comment]
This is pretty easy.  It would be even easier to hit the data.ny.gov API directly-- I think they are serving this same dataset here:

https://data.ny.gov/Energy-Environment/Oil-Gas-Other-Regulated-Wells-Map-Beginning-1860/5xpn-xxne

Unfortunatley there is no geojson output, and the json output has no lat/lons.  However, the .csv does:

https://data.ny.gov/resource/5xpn-xxne.csv

Cary- how hard would it be to use csv instead of a geojson to build the layer?

If its a pain I can just bring it into PostGIS and spit out a GeoJSON from there.  It would be cool to have a link to the live data, however!

**Comment by colinbeier** [comment]
Just bumping this back up...

**Comment by sasignell** [comment]
I got the csv and imported to PostGIS... however, there are 40,000+ points
so no possibility of geojson.  Should I just do it via WMS or should we
winnow it down somehow?

On Mon, Feb 8, 2016 at 11:53 AM, colinbeier <notifications@github.com>
wrote:

> Just bumping this back up...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/caryfitzhugh/NYCCSC-map-viewer/issues/119#issuecomment-181426334>
> .
>



-- 
Steve Signell
Frontier Spatial, L.L.C.
1062 Dean St.
Schenectady, NY 12309
518-232-1008
frontierspatial.com
steve@frontierspatial.com

**Comment by caryfitzhugh** [comment]
@sasignell can it go with topojson? how big is 40k geojson points?

**Comment by caryfitzhugh** [comment]
duh. topojson wouldn't help much - since there aren't shared borders.   but maybe it makes it smaller anyway.

**Comment by sasignell** [comment]
Yeah unfortunately topjson won't get us much.  I say we just bring it in as
a wms.  I'll tryt o get it up and running later tonight

On Mon, Feb 8, 2016 at 4:20 PM, Cary FitzHugh <notifications@github.com>
wrote:

> duh. topojson wouldn't help much - since there aren't shared borders. but
> maybe it makes it smaller anyway.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/caryfitzhugh/NYCCSC-map-viewer/issues/119#issuecomment-181551492>
> .
>



-- 
Steve Signell
Frontier Spatial, L.L.C.
1062 Dean St.
Schenectady, NY 12309
518-232-1008
frontierspatial.com
steve@frontierspatial.com

**Comment by caryfitzhugh** [comment]
@sasignell could we split it into separate layers?
DEC Oil
DEC Water
DEC ... etc?

So you're only bringing in a couple hundred k of data each time

**Comment by colinbeier** [comment]
I think that would be fine to split them out, if there are different icons we can use, would help with viz

**Comment by caryfitzhugh** [comment]
@sasignell the CSV file gzipped is 56kb... raw is 391kb.  Should I just ingest that directly, and do some processing in JS?   That might not be too bad.

What's the geojson file look like that you generated?

**Comment by caryfitzhugh** [comment]
And what fields would we want?  I checked my first guess...
- [x] API Well Number,
- [ ] County Code,
- [ ] API Hole Number,
- [ ] Sidetrack,
- [ ] Completion,
- [x] Well Name,
- [x] Company Name,
- [ ] Operator Number,
- [x] Well Type,
- [ ] Map Symbol,
- [ ] Well Status ,
- [ ] Status Date,
- [ ] Permit Application Date,
- [ ] Permit Issued Date,
- [ ] Date Spudded,
- [ ] Date of Total Depth,
- [ ] Date Well Completed,
- [ ] Date Well Plugged,
- [ ] Date Well Confidentiality Ends,
- [ ] Confidentiality Code,
- [ ] Town,
- [ ] Quad,
- [ ] Quad Section,
- [ ] Producing Field,
- [ ] Producing Formation,
- [ ] Financial Security,
- [ ] Slant,
- [ ] County,
- [ ] Region,
- [ ] State Lease,
- [ ] "Proposed Depth, ft",
- [x] Surface Longitude,
- [x] Surface Latitude,
- [ ] Bottom Hole Longitude,
- [ ] Bottom Hole Latitude,
- [ ] "True Vertical Depth, ft",
- [ ] "Measured Depth, ft",
- [ ] "Kickoff, ft",
- [x] "Drilled Depth, ft",
- [ ] "Elevation, ft",
- [ ] Original Well Type,
- [ ] Permit Fee,
- [ ] Objective Formation,
- [ ] Depth Fee,
- [ ] Spacing,
- [ ] Spacing Acres,
- [ ] Integration,
- [ ] Hearing Date,
- [ ] Date Last Modified,
- [x] DEC Database Link
- [ ] Location 1

**Comment by colinbeier** [comment]
Maybe just add well status... and don't need to show lat / long

Colin Beier
SUNY ESF

On Feb 9, 2016 2:33 PM, Cary FitzHugh <notifications@github.com> wrote:

And what fields would we want? I checked my first guess...

  *    API Well Number,
  *    County Code,
  *    API Hole Number,
  *    Sidetrack,
  *    Completion,
  *    Well Name,
  *    Company Name,
  *    Operator Number,
  *    Well Type,
  *    Map Symbol,
  *    Well Status ,
  *    Status Date,
  *    Permit Application Date,
  *    Permit Issued Date,
  *    Date Spudded,
  *    Date of Total Depth,
  *    Date Well Completed,
  *    Date Well Plugged,
  *    Date Well Confidentiality Ends,
  *    Confidentiality Code,
  *    Town,
  *    Quad,
  *    Quad Section,
  *    Producing Field,
  *    Producing Formation,
  *    Financial Security,
  *    Slant,
  *    County,
  *    Region,
  *    State Lease,
  *    "Proposed Depth, ft",
  *    Surface Longitude,
  *    Surface Latitude,
  *    Bottom Hole Longitude,
  *    Bottom Hole Latitude,
  *    "True Vertical Depth, ft",
  *    "Measured Depth, ft",
  *    "Kickoff, ft",
  *    "Drilled Depth, ft",
  *    "Elevation, ft",
  *    Original Well Type,
  *    Permit Fee,
  *    Objective Formation,
  *    Depth Fee,
  *    Spacing,
  *    Spacing Acres,
  *    Integration,
  *    Hearing Date,
  *    Date Last Modified,
  *    DEC Database Link
  *    Location 1

**Comment by caryfitzhugh** [comment]
I think I need the lat/lng to plot the well location, right?  is that what
you meant?

**Comment by caryfitzhugh** [comment]
oh, did you mean on the popup?
I was speaking to what fields to pull in from the CSV.
Which is sortof related.  I think I understand.

Don't need to put lat/lng in the little popup.

**Comment by colinbeier** [comment]
yes, need lat-long to plot, don't need to return lat-long values in the attribute table / pop-up when you click on the feature.  sorry if being pedantic.

**Comment by caryfitzhugh** [comment]
no worries, we're all nerds here. :)

**Comment by caryfitzhugh** [comment]
@sasignell do you have the full 41k wells download somewhere? I only got 1k or so in that zip file you posted.

**Comment by caryfitzhugh** [comment]
I found it.

**Comment by caryfitzhugh** [comment]
well...

I have added it.

gzipped the topojson is only 600k.  it loads in very quickly.
Renering 40000 SVG elements is a bit slow.

http://caryfitzhugh.github.io/NYCCSC-map-viewer/dist/map_viewer.html

We need a few things.

* How do we split them up into separate layers?

*  by type 
![ubuntu ip-172-31-30-91 var lib tomcat7 webapps geoserver data www 2016-02-09 17-02-31](https://cloud.githubusercontent.com/assets/445848/12932068/f5d61d84-cf4e-11e5-84b8-f667c25ce571.png)
* by status?
![ubuntu ip-172-31-30-91 var lib tomcat7 webapps geoserver data www 2016-02-09 17-02-17](https://cloud.githubusercontent.com/assets/445848/12932069/f5d678ec-cf4e-11e5-973d-b2ba96a8d34d.png)

* ## Need Icons!
  * The ones on the NY DEC site aren't all that grand.  Just colored circles (or with a slash through them).
  * though , those are easy in SVG...

**Comment by caryfitzhugh** [comment]
@colinbeier @sasignell the legend on the NY site seems to split them by:
* gas (9500 + 350 + 300 + 15) == about 10k
* oil (4000 + 16000) == about 20k
* other (I guess about 10k)

Is that good enough way to split them?

And then you could filter inside a layer by the status.

Thoughts?

I can use the same icons they have (red / blue / green circles).

**Comment by sasignell** [comment]
Sounds good to me

**Comment by colinbeier** [comment]
Works for me too

**Comment by caryfitzhugh** [comment]
![image](https://cloud.githubusercontent.com/assets/445848/12950753/ab3de566-cfdc-11e5-938a-a322f852d023.png)

**Comment by caryfitzhugh** [comment]
ok. so I've done this, and it's on the gh-pages site.
It's a lot of points, so on loading / displaying all of the points, it can be a couple seconds pause.

In this I did notice that many of the wells are at the same exact lat / long.  I've seen situations where the same lat/lng has 7 wells in it.  We're shipping that data around, and I'm going to have a look to see if I can't "smoosh" things together and hopefully only render / transport 1/10th the geojson points.

**Comment by caryfitzhugh** [comment]
well, many have one point. but 2928 share points. And 1400 of those are 0,0 or "","".

So I'd like to drop the 0,0 points. That saves us 1000 points or so.

I looked, and clustering the wells, even to the 8th sig digit (resolution of 1.1mm or so) [http://gis.stackexchange.com/questions/8650/how-to-measure-the-accuracy-of-latitude-and-longitude]

Grouping things like this saves us another 2k points (or so).  Not sure if it's worth the effort.  For those points which are dupe'd there is no way to see all the info for all the wells, you'll just be clicking on the "top" one.


@colinbeier ?

**Comment by colinbeier** [comment]
Are we still providing a toggle to select among well types?

Colin Beier
SUNY ESF

On Feb 10, 2016 3:58 PM, Cary FitzHugh <notifications@github.com> wrote:

well, many have one point. but 2928 share points. And 1400 of those are 0,0 or "","".

So I'd like to drop the 0,0 points. That saves us 1000 points or so.

I looked, and clustering the wells, even to the 8th sig digit (resolution of 1.1mm or so) [http://gis.stackexchange.com/questions/8650/how-to-measure-the-accuracy-of-latitude-and-longitude]

Grouping things like this saves us another 2k points (or so). Not sure if it's worth the effort. For those points which are dupe'd there is no way to see all the info for all the wells, you'll just be clicking on the "top" one.

@colinbeier<https://github.com/colinbeier> ?

**Comment by caryfitzhugh** [comment]
I have 3 "layers"
Oil, Gas, Other

And inside a layer you can toggle by well type and well status

**Comment by colinbeier** [comment]
That should work... don't worry about the duplicates

Colin Beier
SUNY ESF

On Feb 10, 2016 4:09 PM, Cary FitzHugh <notifications@github.com> wrote:

I have 3 "layers"
Oil, Gas, Other

And inside a layer you can toggle by well type and well status

**Comment by caryfitzhugh** [comment]
ok @colinbeier @sasignell check it out 
http://caryfitzhugh.github.io/NYCCSC-map-viewer/dist/map_viewer.html

I put them under "Energy"... Not sure about the metadata in Layer Info, I did the best I could :)

**Comment by colinbeier** [comment]
makes sense in that folder, thanks! will check layer info and will reopen this if any changes are needed...

Colin Beier
SUNY ESF

On Feb 10, 2016 4:37 PM, Cary FitzHugh <notifications@github.com> wrote:

ok @colinbeier<https://github.com/colinbeier> @sasignell<https://github.com/sasignell> check it out
http://caryfitzhugh.github.io/NYCCSC-map-viewer/dist/map_viewer.html

I put them under "Energy"... Not sure about the metadata in Layer Info, I did the best I could :)
