### ISSUE TITLE
Add layers: DEC Environmental Mapper

### ISSUE THREAD

**Issue by colinbeier** [caryfitzhugh/NYCCSC-map-viewer#121]
NYSERDA asked us to bring in layers from one of DEC's (godawful) web maps.  

http://www.dec.ny.gov/imsmaps/ERM/viewer.htm
Note: you must zoom in to see these layers (which is weird) 

Here is where I found them elsewhere. If there is a wms or API somewhere, we can use that too. 

1. NYS Freshwater Wetlands 
This layer shows those wetlands that are currently mapped under the state's Freshwater Wetlands Act (outside the Adirondack Park -- the APA has the ADK wetlands layer).  These are available via CUGIR on a county-by-county basis, which is annoying.  I could not find any search results consistent with this layer on data.ny.gov, but I might have missed something.  

Item page: http://gis.ny.gov/gisdata/inventories/details.cfm?DSID=1274
Source link: http://cugir.mannlib.cornell.edu/datatheme.jsp?id=111

2. Streams, Rivers, Lakes and Ponds 
This layer shows water quality classifications of New York ’s streams, rivers, lakes, and ponds.

Item page: http://gis.ny.gov/gisdata/inventories/details.cfm?DSID=1118
Source link: http://gis.ny.gov/gisdata/fileserver/?DSID=1118&file=nysdec_wtrcls.zip

Please comment: easy - moderate - hard

**Comment by colinbeier** [comment]
Update from Amanda: 

From the DEC ERM, I’d like to see the Rare Plants and Rare Animals layer, as well as the Significant Natural Communities.  

Steve, do you want me to find the NYS GIS pages for these?  

Also check out http://maps.naturalresourcenavigator.org/ for lots of relevant REST services

Amanda says: 
-          I’d like a few of the extreme precip layers. These are actually Art’s data, though, so we might be able to get them from him more easily. Check with him first.
-          They have some current and future rare species layers that might be good (they aren’t listed on the link Steve sent). We probably don’t want those AND the one from the ERM, though. Probably just one or the other.
-          I like their future predicted changes in land use/landcover. (They also have the current land use layer just for NYS, if we want to use that instead of the entire region.)
-          I wouldn’t want to bring in any of their “scored” layers. Users need to be able to use TNC’s tool to understand what those layers mean.

**Comment by caryfitzhugh** [comment]
@sasignell well, I'vs downloading that dataset.
http://gis.ny.gov/gisdata/inventories/details.cfm?DSID=1274

Downloading qgis and fiddling.

But - I also went here: http://www.naturalresourcenavigator.org/resources-page/data/
And couldn't download anything - that page seems like it's not been finished.

**Comment by caryfitzhugh** [comment]
@sasignell well. I think I could create a single GEOJson file of all these checkzones.

Here is one for albany? 

I believe I can just open all the stupid nested zipfiles, and then put all these checkzones into one big geojson... right?


[albany_checkzones.geojson.zip](https://github.com/caryfitzhugh/NYCCSC-map-viewer/files/122191/albany_checkzones.geojson.zip)

**Comment by caryfitzhugh** [comment]
water controls is 
[water_controls.topojson.zip](https://github.com/caryfitzhugh/NYCCSC-map-viewer/files/122207/water_controls.topojson.zip)

Well -- I'll just leave this alone for now. Not sure if I'm doing the right thing.
As topoj

**Comment by caryfitzhugh** [comment]
I've been testing on geojson.io

**Comment by caryfitzhugh** [comment]
@sasignell is creating a single geojson of all those checkzones the right approach? do you think?

**Comment by sasignell** [comment]
We're talking about the wetlands, right?  We should just be able to add
this from wms/esri-- I just opened up a new issue

On Thu, Feb 11, 2016 at 9:40 AM, Cary FitzHugh <notifications@github.com>
wrote:

> @sasignell <https://github.com/sasignell> is creating a single geojson of
> all those checkzones the right approach? do you think?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/caryfitzhugh/NYCCSC-map-viewer/issues/121#issuecomment-182891917>
> .
>



-- 
Steve Signell
Frontier Spatial, L.L.C.
1062 Dean St.
Schenectady, NY 12309
518-232-1008
frontierspatial.com
steve@frontierspatial.com

**Comment by sasignell** [comment]
I'm really confused about this issue thread, there are about 5 different
datasets mentioned...  can we make a different issue for each dataset?

On Thu, Feb 11, 2016 at 9:50 AM, Steve Signell <steve@frontierspatial.com>
wrote:

> We're talking about the wetlands, right?  We should just be able to add
> this from wms/esri-- I just opened up a new issue
>
> On Thu, Feb 11, 2016 at 9:40 AM, Cary FitzHugh <notifications@github.com>
> wrote:
>
>> @sasignell <https://github.com/sasignell> is creating a single geojson
>> of all those checkzones the right approach? do you think?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/caryfitzhugh/NYCCSC-map-viewer/issues/121#issuecomment-182891917>
>> .
>>
>
>
>
> --
> Steve Signell
> Frontier Spatial, L.L.C.
> 1062 Dean St.
> Schenectady, NY 12309
> 518-232-1008
> frontierspatial.com
> steve@frontierspatial.com
>



-- 
Steve Signell
Frontier Spatial, L.L.C.
1062 Dean St.
Schenectady, NY 12309
518-232-1008
frontierspatial.com
steve@frontierspatial.com

**Comment by caryfitzhugh** [comment]
Ok. checking this out:

* NYS Freshwater Wetlands
   Item page: http://gis.ny.gov/gisdata/inventories/details.cfm?DSID=1274
   Source link: http://cugir.mannlib.cornell.edu/datatheme.jsp?id=111

* ~~Water Quality for Streams / Lakes / Rivers / Ponds~~
  Item page: http://gis.ny.gov/gisdata/inventories/details.cfm?DSID=1118
  Source link: http://gis.ny.gov/gisdata/fileserver/?DSID=1118&file=nysdec_wtrcls.zip
  Contained in Issue #134 

* Extreme precip layers 
  * These are in the climate tab.
  * An [An example info request](http://services.coastalresilience.org/arcgis/rest/services/New_York/NY_CLIMAD_toolkit/MapServer/155?f=json&callback=jQuery190044797275378368795_1455203008982&_=1455203008986)
  * [The ArcGIS REST Url](http://services.coastalresilience.org/arcgis/rest/services/New_York/NY_CLIMAD_toolkit/MapServer/)
* future predicted land use
  * [ArcGIS REST Page](http://services.coastalresilience.org/arcgis/rest/services/New_York/NY_CLIMAD_toolkit/MapServer/206)
* Rare Plants & Animals (DEC ERM)
 * maps.naturalresourcenavigator.org
  * These are the calls to the service for species hexagons
  *  [ArcGIS page](http://services.coastalresilience.org/arcgis/rest/services/New_York/NY_CLIMAD_species/MapServer/)
  * Statewide Data:  
[allspp_nonsp_download.zip](https://github.com/caryfitzhugh/NYCCSC-map-viewer/files/126557/allspp_nonsp_download.zip)

**Comment by caryfitzhugh** [comment]
@sasignell we can split these out into separate issues, once you take a gander and say "yes, these have't been done or cancelled yet".

**Comment by sasignell** [comment]
ok the wetlands and water classes are done... making separate issues for the others
