### ISSUE TITLE
Add layer: National Hydrography Dataset (NHD) -- Wellhead Protection Areas

### ISSUE THREAD

**Issue by colinbeier** [caryfitzhugh/NYCCSC-map-viewer#122]
NYSERDA specifically asked for "Wellhead Protection Areas" via the NHD.  There are a lot of other types of information in NHD, and I will try to clarify whether its just wellheads or other features too.  We already have the HUC-4s in there as the watersheds boundary layer.  

NHD is available via the National Map.  I think this means we can grab a wms, right? 

http://viewer.nationalmap.gov/viewer/nhd.html?p=nhd

Please comment: easy - moderate - hard

**Comment by sasignell** [comment]
I can't find a data link anywhere for this kind of data, there's some information and contact info here: https://www.health.ny.gov/environmental/water/drinking/wellhead/wellfact.htm

Is this a GIS layer that someone has seen, or just something they know or think exists?

**Comment by caryfitzhugh** [comment]
Using this page: http://viewer.nationalmap.gov/basic/?howTo=true#productSearch

I was able to download the NHD best resolution shapefile (I think that's what you need).

It's about 593 MB, so I'm putting it onto S3 in a moment (once it's done downloading).

**Comment by caryfitzhugh** [comment]
@sasignell I'm not sure how I could upload the shapefile to geoserver.. I think the rest is in your lap... right? I could help with adding WMS layers in the client if you tell me what to do.

**Comment by sasignell** [comment]
OK this is just the NHD right?  I don't think there's anything about
wellhead protection areas in there.  My vote is to say no to this layer.

Steve

On Tue, Mar 1, 2016 at 12:56 PM, Steve Signell <steve@frontierspatial.com>
wrote:

> yeah I can do that
>
> On Tue, Mar 1, 2016 at 12:48 PM, Cary FitzHugh <notifications@github.com>
> wrote:
>
>> @sasignell <https://github.com/sasignell> I'm not sure how I could
>> upload the shapefile to geoserver.. I think the rest is in your lap...
>> right? I could help with adding WMS layers in the client if you tell me
>> what to do.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/caryfitzhugh/NYCCSC-map-viewer/issues/122#issuecomment-190829971>
>> .
>>
>
>
>
> --
> Steve Signell
> Frontier Spatial, L.L.C.
> 1062 Dean St.
> Schenectady, NY 12309
> 518-232-1008
> frontierspatial.com
> steve@frontierspatial.com
>



-- 
Steve Signell
Frontier Spatial, L.L.C.
1062 Dean St.
Schenectady, NY 12309
518-232-1008
frontierspatial.com
steve@frontierspatial.com

**Comment by colinbeier** [comment]
yea, i don't know, this one is kind of a mess.  i will check with Lisa / Amanda...
