### ISSUE TITLE
Add layer(s): Reservoirs

### ISSUE THREAD

**Issue by colinbeier** [caryfitzhugh/NYCCSC-map-viewer#123]
NYSERDA wants to add several layers to the Water Resources folders, related to reservoirs.  I think these should be easy.  Steve -- I like the approach of sharing a preview image of these layers with NYSERDA and NESCAUM before bringing them into the map.  

1. Primary Aquifers - 1:24,000 
http://gis.ny.gov/gisdata/inventories/details.cfm?DSID=1203
http://gis.ny.gov/gisdata/fileserver/?DSID=1203&file=WaterWellProgram.zip

2. Water Quality Classifications - NYS ‘
http://gis.ny.gov/gisdata/inventories/details.cfm?DSID=1118
http://gis.ny.gov/gisdata/fileserver/?DSID=1118&file=nysdec_wtrcls.zip

3. Water Wells 
http://gis.ny.gov/gisdata/inventories/details.cfm?DSID=1232
http://gis.ny.gov/gisdata/fileserver/?DSID=1232&file=primaryaquifers.zip

4. Unconsolidated Aquifers at 1:250,000 
http://gis.ny.gov/gisdata/inventories/details.cfm?DSID=1141
http://gis.ny.gov/gisdata/fileserver/?DSID=1141&file=dow_uncon_aqui.zip

**Comment by sasignell** [comment]
Hey Cary,
    Here's a geojson of these points (attached).   The others are polygons so I'll run them through geoserver.
[water_well_program.zip](https://github.com/caryfitzhugh/NYCCSC-map-viewer/files/123857/water_well_program.zip)

**Comment by caryfitzhugh** [comment]
ok. I can add these tomorrow.

**Comment by sasignell** [comment]
I split this up into 4 separate issues, and am closing
