### ISSUE TITLE
Add layer(s): Miscellaneous NYS DEC

### ISSUE THREAD

**Issue by colinbeier** [caryfitzhugh/NYCCSC-map-viewer#124]
Also on NYSERDA's list are the potential layers below.  Focus effort on 1 and 3.  I will check on 2.  

1. Bulk Storage Sites in New York State 
http://gis.ny.gov/gisdata/inventories/details.cfm?DSID=1253
ftp://ftp.dec.state.ny.us/der/FOIL/bulkstorageGIS.zip
-- a geojson marker layer would be ideal for this data, if possible 

2. Potential Environmental Justice Areas 
http://gis.ny.gov/gisdata/inventories/details.cfm?DSID=1273
http://www.dec.ny.gov/maps/pejalink.kmz
-- only format i can find is a KMZ, which is not easy to work with.  contact info for data steward is on the GIS Clearinghouse page (first link), might see if the original shapefile is available. but first, i will check to see how much of a priority this is for NYSERDA.  it is a very similar, if not identical, dataset to the Social Vulnerability Index we already have up.  

3. Remediation Sites in New York State 
http://gis.ny.gov/gisdata/inventories/details.cfm?DSID=1097
http://www.dec.ny.gov/derdata/remedsiteborders.zip

**Comment by colinbeier** [comment]
Also add to Water Resources folder: 

Combined Sewer Overflows
https://data.ny.gov/Energy-Environment/Combined-Sewer-Overflows-CSOs-Map/i8hd-rmbi

**Comment by sasignell** [comment]
None of the gis.ny.gov links open for me... do you have to have a partner login?  I don't have one.  Or maybe their site is down?

also this doesn't contain any geographic information:
ftp://ftp.dec.state.ny.us/der/FOIL/bulkstorageGIS.zip

**Comment by colinbeier** [comment]
They all open fine for me today (08 Feb)... did you try again?  

We can remove layer no. 2 above... Potential Environmental Justice Areas.

**Comment by sasignell** [comment]
I'm splitting these up into 3 separate issues and closing this one
