### ISSUE TITLE
UI: Map sharing options

### ISSUE THREAD

**Issue by colinbeier** [caryfitzhugh/NYCCSC-map-viewer#125]
Guys, I would like to scope out what we can do to improve on the map sharing options we have now.  

1. The export serialization is a nice feature, but only works for those who have their own web map.  This is a very small portion of our audience.  

2. The import map serialization is also a nice feature, but has a very limited user population.  

Things I would like to see us evaluate and try to add:

3. Embed code for the iframe that holds the map, with the active layers and settings captured, etc. This way someone can pop a version of the map into their own website.  I don't know what, if any, contingencies this creates with CDNs etc., but it could be worth exploring.  

***This one is probably the most important*** 
4. A nice layout-style image/pdf export that includes the NYCCSC logo and legend (for up to 4-5 layers).  I know we have the map print tool, but it does not work all that well (at least on my Mac in Chrome and Safari).   I don't care specifically how we do this, but we need to have something that works nicely here. 

5. Other ideas / options?

**Comment by colinbeier** [comment]
Guys, any thoughts on this?

**Comment by caryfitzhugh** [comment]
dup of this: https://github.com/caryfitzhugh/NYCCSC-map-viewer/issues/116
CLosing that one.

**Comment by caryfitzhugh** [comment]
OK - so printing is all you really care about ATM.

So - can we put the map on page 1
and the legend on page 2?
So printing gives a 2 page PDF?

**Comment by colinbeier** [comment]
That sounds good - I would like to see how that looks.

**Comment by caryfitzhugh** [comment]
@colinbeier it's a little tricky.  Since the width of your screen determines the width of the printed image. I wonder how google maps handles it...

Anyway  THis is sortof where I'm going with this (lots of CSS fiddling).  two pages. Second page needs legends (but they need to be a different style because background images are not printed.  -- not too hard to fix...
[NYCSCC Map Viewer - Print.pdf](https://github.com/caryfitzhugh/NYCCSC-map-viewer/files/134945/NYCSCC.Map.Viewer.-.Print.pdf)

**Comment by caryfitzhugh** [comment]
@colinbeier check this out. 

deploying to the gh-pages site.

Example: 
[NYCSCC Map Viewer - Print.pdf](https://github.com/caryfitzhugh/NYCCSC-map-viewer/files/135173/NYCSCC.Map.Viewer.-.Print.pdf)

**Comment by caryfitzhugh** [comment]
It's not perfect on the legends (sometimes the taller legends gum up the alignment). but to fix that is sortof a whole-nother ball of wax.  Especially on print views.

**Comment by colinbeier** [comment]
that looks great!

**Comment by sasignell** [comment]
Excellent.

On Wed, Feb 17, 2016 at 5:01 PM, colinbeier <notifications@github.com>
wrote:

> that looks great!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/caryfitzhugh/NYCCSC-map-viewer/issues/125#issuecomment-185427038>
> .
>



-- 
Steve Signell
Frontier Spatial, L.L.C.
1062 Dean St.
Schenectady, NY 12309
518-232-1008
frontierspatial.com
steve@frontierspatial.com

**Comment by colinbeier** [comment]
print quality looks great.  the frame width, alas, might be adjusted.  looks like it is printing the map that's under the sidebar, which most users will forget about as they add and fiddle with layers.  i'm fine with a two page approach, but maybe in a one-pager that space in the printed image (under the sidebar on the screen) is where the legends go (in a sidebar space like the one on screen)?  could it print data from that tab even if the tab wasn't open?  

this does relate to another little bug that i've noticed for a while: the map moves when the sidebar is collapsed and reopened. can we fix that easily?

**Comment by caryfitzhugh** [comment]
hey colin,

the recentering is on purpose.  I redraw the map when you open the sidebar
(at the same center).  This is all I could think to do.

If we don't want that, I think the only option would be to have the sidebar
*overlay* the map.  Which works, but then on printing, you'll still get the
stuff underneath the sidebar... hrm....

We could maybe fiddle and see how that would work (legend information on
the left).  It brings up the question, what to do if the layers sidebar is
closed.... ?

**Comment by sasignell** [comment]
I think we may have to just deal with redrawing the map... it just works
better with the printing and view extent calculations. terria.js did it
that way too, probably with good reason..

On Thu, Feb 18, 2016 at 12:38 PM, Cary FitzHugh <notifications@github.com>
wrote:

> hey colin,
>
> the recentering is on purpose. I redraw the map when you open the sidebar
> (at the same center). This is all I could think to do.
>
> If we don't want that, I think the only option would be to have the sidebar
> *overlay* the map. Which works, but then on printing, you'll still get the
> stuff underneath the sidebar... hrm....
>
> We could maybe fiddle and see how that would work (legend information on
> the left). It brings up the question, what to do if the layers sidebar is
> closed.... ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/caryfitzhugh/NYCCSC-map-viewer/issues/125#issuecomment-185828653>
> .
>



-- 
Steve Signell
Frontier Spatial, L.L.C.
1062 Dean St.
Schenectady, NY 12309
518-232-1008
frontierspatial.com
steve@frontierspatial.com

**Comment by colinbeier** [comment]
It's OK as is, especially since you just did all the print upgrades based on the current setup. If we get complaints about it later we can ask for more time / money to fix it!

Colin Beier
SUNY ESF

On Feb 18, 2016 12:45 PM, Steve Signell <notifications@github.com> wrote:
I think we may have to just deal with redrawing the map... it just works
better with the printing and view extent calculations. terria.js did it
that way too, probably with good reason..

On Thu, Feb 18, 2016 at 12:38 PM, Cary FitzHugh <notifications@github.com>
wrote:

> hey colin,
>
> the recentering is on purpose. I redraw the map when you open the sidebar
> (at the same center). This is all I could think to do.
>
> If we don't want that, I think the only option would be to have the sidebar
> *overlay* the map. Which works, but then on printing, you'll still get the
> stuff underneath the sidebar... hrm....
>
> We could maybe fiddle and see how that would work (legend information on
> the left). It brings up the question, what to do if the layers sidebar is
> closed.... ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/caryfitzhugh/NYCCSC-map-viewer/issues/125#issuecomment-185828653>
> .
>



--
Steve Signell
Frontier Spatial, L.L.C.
1062 Dean St.
Schenectady, NY 12309
518-232-1008
frontierspatial.com
steve@frontierspatial.com
