### ISSUE TITLE
Sewer Overflows

### ISSUE THREAD

**Issue by sasignell** [caryfitzhugh/NYCCSC-map-viewer#126]
Hey Cary,
   I tried to create a new layer sewer_overflows, pulling directly from this api:

https://data.ny.gov/resource/5d4q-pk7d.geojson

I just got a little stuck trying to figure out how to modify the WMS callback code to bring it in... can you take a quick look?  Thanks

**Comment by caryfitzhugh** [comment]
@sasignell I have pushed this. I made a new icon. ? try it out.
I can't close this b/c the CDN for it isn't set up, but once I get the OK, I'll do the CDN and polish it off.

Thanks

**Comment by colinbeier** [comment]
its the same icon as the wastewater treatment plants.  what other options?

**Comment by sasignell** [comment]
Looks good to me!  Maybe Colin has an opinion on the icon?

On Mon, Feb 8, 2016 at 11:45 PM, colinbeier <notifications@github.com>
wrote:

> its the same icon as the wastewater treatment plants. what other options?
>
> On Feb 8, 2016, at 11:39 PM, Cary FitzHugh wrote:
>
> > @sasignell I have pushed this. I made a new icon. ? try it out.
> > I can't close this b/c the CDN for it isn't set up, but once I get the
> OK, I'll do the CDN and polish it off.
> >
> > Thanks
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/caryfitzhugh/NYCCSC-map-viewer/issues/126#issuecomment-181709351>
> .
>



-- 
Steve Signell
Frontier Spatial, L.L.C.
1062 Dean St.
Schenectady, NY 12309
518-232-1008
frontierspatial.com
steve@frontierspatial.com

**Comment by colinbeier** [comment]
would like a different icon if possible, or we keep this and change the wastewater treatment plants icon.

**Comment by sasignell** [comment]
I switched the sped icon to the sewer outflows and brought in a new icon
for spdes.  Let me know what you think:

http://52.2.5.122/NYCCSC-map-viewer/src/map_viewer.html?active-layers=spdes,sewer_overflows


On Mon, Feb 8, 2016 at 11:52 PM, colinbeier <notifications@github.com>
wrote:

> would like a different icon if possible, or we keep this and change the
> wastewater treatment plants icon.
>
> On Feb 8, 2016, at 11:50 PM, Steve Signell wrote:
>
> > Looks good to me! Maybe Colin has an opinion on the icon?
> >
> > On Mon, Feb 8, 2016 at 11:45 PM, colinbeier <notifications@github.com>
> > wrote:
> >
> > > its the same icon as the wastewater treatment plants. what other
> options?
> > >
> > > On Feb 8, 2016, at 11:39 PM, Cary FitzHugh wrote:
> > >
> > > > @sasignell I have pushed this. I made a new icon. ? try it out.
> > > > I can't close this b/c the CDN for it isn't set up, but once I get
> the
> > > OK, I'll do the CDN and polish it off.
> > > >
> > > > Thanks
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub.
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> https://github.com/caryfitzhugh/NYCCSC-map-viewer/issues/126#issuecomment-181709351
> >
> > > .
>
> > >
> >
> >
> >
> > --
> > Steve Signell
> > Frontier Spatial, L.L.C.
> > 1062 Dean St.
> > Schenectady, NY 12309
> > 518-232-1008
> > frontierspatial.com
> > steve@frontierspatial.com
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/caryfitzhugh/NYCCSC-map-viewer/issues/126#issuecomment-181710183>
> .
>



-- 
Steve Signell
Frontier Spatial, L.L.C.
1062 Dean St.
Schenectady, NY 12309
518-232-1008
frontierspatial.com
steve@frontierspatial.com

**Comment by colinbeier** [comment]
Looks great, thanks!

**Comment by caryfitzhugh** [comment]
sorry - I have to add the CDN in -- there were soe AWS issues before. that's all this needs.

**Comment by caryfitzhugh** [comment]
*so* weird.  I set up a cloudfront CDN.
d13dls4epa0ynw.cloudfront.net

And hit it. It should be hitting data.ny.gov, but.. it doesn't.
It redirects to "www.socrata.com"

ok. so it makes more sense now.
The data.ny site is built / run by socrata

They must be redirecting things coming from AWS to a black hole.  blerg. 
well, no CDN for them then!

**Comment by colinbeier** [comment]
fine with me

Colin Beier
SUNY ESF

On Feb 10, 2016 4:29 PM, Cary FitzHugh <notifications@github.com> wrote:

so weird. I set up a cloudfront CDN.
d13dls4epa0ynw.cloudfront.net

And hit it. It should be hitting data.ny.gov, but.. it doesn't.
It redirects to "www.socrata.com"

ok. so it makes more sense now.
The data.ny site is built / run by socrata

They must be redirecting things coming from AWS to a black hole. blerg.
well, no CDN for them then!

**Comment by caryfitzhugh** [comment]
ok. removed. done. closing.  deployed to gh-pages.

**Comment by colinbeier** [comment]
Minor edit: Pop up table, field should be "Receiving waterbody" instead of "waterboy"...

**Comment by caryfitzhugh** [comment]
Fixed. 
![image](https://cloud.githubusercontent.com/assets/445848/13580203/2b225e28-e46f-11e5-805a-a499fdd1fde7.png)

**Comment by colinbeier** [comment]
well played sir.
