### ISSUE TITLE
Map Orientation / Intro

### ISSUE THREAD

**Issue by colinbeier** [caryfitzhugh/NYCCSC-map-viewer#127]
We very much need an orientation / intro / help feature (or feature) so that users can figure out what the different tools / functions are in the map.  

Can we talk about different ways to do this?  For a bunch of next-gen web maps I've seen lately, there is an orientation / help feature that explains everything, every button, icon, etc.  There is also annotation / notices that pop up whenever a layer is added, removed, etc. That can get very cluttery / busy, and I don't know if we need all that.  But it does seem the more advanced the map UI, the more hand-holding that needs to happen.  

Cary, I'm expecting this will be a significant investment of your time and effort.  I will talk with Lisa after we complete this round of testing today.

**Comment by sasignell** [comment]
This is something I could work on too-- tooltips are easy and I can work on
some demo/help videos.

FYI this is a public repo, so anyone can read what you write!

On Fri, Feb 5, 2016 at 10:01 AM, colinbeier <notifications@github.com>
wrote:

> We very much need an orientation / intro / help feature (or feature) so
> that users can figure out what the different tools / functions are in the
> map. I'm sitting here watching someone test the map and never realized that
> somebody could be so f*cking clueless... they could not figure out or find
> the most basic things.
>
> Can we talk about different ways to do this? For a bunch of next-gen web
> maps I've seen lately, there is an orientation / help feature that explains
> everything, every button, icon, etc. There is also annotation / notices
> that pop up whenever a layer is added, removed, etc. That can get very
> cluttery / busy, and I don't know if we need all that. But it does seem the
> more advanced the map UI, the more hand-holding that needs to happen.
>
> Cary, I'm expecting this will be a significant investment of your time and
> effort. I will talk with Lisa after we complete this round of testing
> today.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/caryfitzhugh/NYCCSC-map-viewer/issues/127>.
>



-- 
Steve Signell
Frontier Spatial, L.L.C.
1062 Dean St.
Schenectady, NY 12309
518-232-1008
frontierspatial.com
steve@frontierspatial.com

**Comment by colinbeier** [comment]
Steve - that would be great!  We need some way to call attention to all of the tools, explain how they work, etc.  We may need to make buttons bigger, icons on the map or in the legend to indicate when something can be clicked on, etc.  We may need to implement a couple of overlapping ways to do this so the novice user gets enough of it to be functional.  One of the testers with GIS experience found the map very intuitive and really enjoyed the features.  The other testers really struggled to do much of anything, including navigating their browser to the correct link, so its not all on the map itself.

**Comment by caryfitzhugh** [comment]
We can do tooltips.

We can do an overlay with little arrows.

We can do a tutorial with steps and a wizard.

Help links? We'd need to figure out what needs help. And that's ahrd, b/c it seems so darn obvious to me / us.

**Comment by caryfitzhugh** [comment]
I guess I start to look at the map when you first come to it (we could use a cookie to trigger a popup that shows the first time you come).

What might it say?  I'll at least take a stab at it so people have something to critique.

## Welcome Modal
"Welcome to the NYCCSC Map Viewer.
  It's purpose is to allow you to visually explore all sorts of data relating to climate change and NY state's ecology and infrastructure.  

  We have some tutorials which can help you learn about the functionality provided by the viewer
  *  How to add things I want to see to the map
  *  Moving around the map
  *  Dig deeper into what is shown on the map.
  *  Cloning layers
  *  Search for landmarks and locations
  * Print the map "


## Adding things to the map
Show an arrow pointing to the "Layers" tab.  
Tell the user to click on the layers tab.
Once they click, ask them to find the "Climate Data", "Projected", "NARCCAP Precipitation Projections".
  Help them drill down and locate the layer.
When they click on the layer, they should see it appear in the map.
Suggest that they add another (a point layer). "Energy" > "Power Plants".
Now you can see how the precipitation changes may affect some of the power plants in NY state.
Suggest that they click on the "i" icon. which shows them detailed information about where that layer comes from, etc.
Now add another layer, but use the search - to type it in.
"CLIMAID" , and add it.
You can change the base layer (change it to Imagery).

## Moving around the map
Each of these will be a step in a wizard and have a highlight / arrow on it.
You can double click to zoom.
Press the - to zoom out.
Press the + to zoom in.
Use the scroll-wheel to zoom.
To center on your location, press the (crosshairs)
To reset (if you get lost) - press the house.


## Dig Deeper
You should add some layers (NARCCAP and CLIMAD as example).
Click on legend.
Notice that NARCCAP is over the climaid data.  You can re-order the layers by clicking the up chevrons
You can change opacity.
You can hide / show a layer individually (or all).
You can remove things from the map with the trashcan.
Change some of the settings on CLIMAID

## Cloning Layers
Used to compare things within a layer. (usually?)
Do it with CLIMAD.
Pick some settings, and then clone it. 
Change opacities and such.

## Searching for locations
Click on the locations tab.
Search for "Albany".
Select the city, clicking on it, zooms the map to that location.
Now try "Northport" - zoom there.
Click house to go home.

## Print
Show how to print the page.
Highlight the button.

**Comment by sasignell** [comment]
Cary, I like the overview.   How would this be laid out?  I was picturing a 'Help' modal with each of your headings as basically slides in a slideshow that could be swiped or toggled forward/back.  Maybe the easiest thing to do would just be a fest-type run through of what you've outlined.   Very simple... a header and a little looping movie showing it in action. 

We could also add annotation and build a  follow-along  tutorial as you describe  but that  would be more time consuming... maybe we could add that later?

**Comment by colinbeier** [comment]
Good overview - I think that covers most of it.  I guess I have the same question as Steve.  The content of the orientation / intro is obviously important, but equally important is the layout.  A modal works, but are there other ways (aside from hover text), to deliver this kind of content.  Tool tips?  Animated sequences?  

On the FEST site, I think Jesse used Snagit to do the screen grab GIFs.  I'm looking at a few options for doing this myself.

**Comment by caryfitzhugh** [comment]
I had thought to use either:

* Little GIFs and some descriptive text

or

* CSS and a wizard to wait for actions to occur
i.e. "Toaster popup in the bottom which says - "ok, now add the layer X, to
do so click on the Layers tab" .. and the layers tab would have an arrow or
highlighting on it.

The second one is more work, but if it's in the budget, I think it's a
better experience.   It does take more time to figure out / design as well.
The first one may suffice.  Just some modal / help pages with animated GIFs
and explanations.

**Comment by colinbeier** [comment]
Here is the freeware program Jesse used to create screen grab GIFs for the FEST site 
[GifCam.zip](https://github.com/caryfitzhugh/NYCCSC-map-viewer/files/125070/GifCam.zip)

**Comment by colinbeier** [comment]
here's a demo gif from a free app i tinkered with today.  made a few of them but this one is the only one small and clear enough to post here.  

![layers tab](https://cloud.githubusercontent.com/assets/7375034/12995997/c60fc29c-d0f9-11e5-9be4-36fde0b7a27b.gif)

got glitchy, so am switching over to a different screen recorder.  will have some new ones to share tomorrow.

**Comment by colinbeier** [comment]
Quick question - what is a suggested max size for the gifs we use in the orientation / tooltip modals?  I have recorded a few nice ones, but they are 10-20 MB files.  Are these going to take too long to load up?

**Comment by caryfitzhugh** [comment]
Hrm.  Well, if they are that large, we can just upload to youtube, and have
a "play" button.  I would think a few MB is about the max for GIFs, since
they will load up automatically and play..  There may be some ways to
re-encode them and get them smaller.  What's their resolution / framerate /
etc. ?

**Comment by colinbeier** [comment]
I can adjust resolution, frame rate, etc. when I export them... the length is the key variable. How many things to show in each one? Going to work on shorter GIFs ...

Colin Beier
SUNY ESF

On Feb 14, 2016 7:44 AM, Cary FitzHugh <notifications@github.com> wrote:
Hrm. Well, if they are that large, we can just upload to youtube, and have
a "play" button. I would think a few MB is about the max for GIFs, since
they will load up automatically and play.. There may be some ways to
re-encode them and get them smaller. What's their resolution / framerate /
etc. ?

**Comment by sasignell** [comment]
I like the YouTube option

**Comment by colinbeier** [comment]
I have the source videos that can be uploaded to YouTube ... but the GIFs might be better in certain slots.  Is there a place on GH where i can post larger files for you guys to grab / comment on? Issues pages have size limit.

Colin Beier
SUNY ESF

On Feb 14, 2016 8:40 AM, Steve Signell <notifications@github.com> wrote:
I like the YouTube option

**Comment by caryfitzhugh** [comment]
You could make an s3 bucket on aws and post them there?

**Comment by colinbeier** [comment]
sure... just first have to figure out how to do that!

**Comment by colinbeier** [comment]
created the bucket nyccsc.map.gifs.videos not sure how to provide you access - maybe you already have it?  

btw the content in here is just what i have at the moment, i am working on making the recordings shorter and then exporting them with low frame rates, to minimize file size.

**Comment by caryfitzhugh** [comment]
Yeah - we all have access b/c we have logins to the NYCCSC AWS account. :)

**Comment by colinbeier** [comment]
figures.  just wasn't sure if each bucket was open or i needed to set permissions somewhere.

**Comment by caryfitzhugh** [comment]
there are definitely permissions you can set on them, but by default
"private" files can be seen by AWS users.  (if not, I think I have access
to change the permissions).

**Comment by caryfitzhugh** [comment]
@colinbeier I would suggest much shorter videos, showing 1 thing at a time.

For example, on the search locations video, just say "Searching for New York City"... in the header.
and the gif does that one thing.  Hopefully people can extrapolate that they can search for more than one thing :P  

I might suggest that we do a short GIF for each of the bullet-points above, basically.

Thoughts?

**Comment by colinbeier** [comment]
ok, makes sense.  working on it...

**Comment by caryfitzhugh** [comment]
I'll start working on HTML / layouts for this... see what we can do.  
I'll put a ? link in the top bar.  In the future we could make it open automatically if it's your first time.

**Comment by caryfitzhugh** [comment]
I have pushed some new code which has the first few slides.  Will do more tomorrow.

Take a gander and just see if the format is what you want.

@colinbeier @sasignell 

Thanks
Cary

**Comment by colinbeier** [comment]
Looks good.  I worry about the amount of space for the gifs, if they will be legible.  But I like the layout!

**Comment by caryfitzhugh** [comment]
ok, I can put them on the bottom probably.  So they can go full-width.

**Comment by colinbeier** [comment]
Can we add a slide / hint that explains the three tabs in the sidebar?  We had one tester that struggled to figure this out.  

**Using the Sidebar**
**Layers** tab gives you access to a variety of map layers and data sources organized by sector. 
**Legend** tab provides map legend information, allows you to adjust the layer information and how it is shown in the map. 
**Locations** tab allows you to search for a location (town, country, watershed) in New York State.  

![threetabs_3](https://cloud.githubusercontent.com/assets/7375034/13496399/fa09ab42-e11d-11e5-9109-5477f6cfa196.gif)

**Comment by colinbeier** [comment]
Another slide: 

**Adjusting your map view and base layer**
**Click and drag** on the map itself to adjust the map view. 
Use the controls in the upper right to **zoom in and out**. You may also double-click on the map, or use your mouse scroll wheel to zoom. 
Click the **House** icon to return to the default view of NY State. 
Click on the **Target** icon to zoom to your ucrrent location (note: your browser will request permission). 
Click on **Base Map** to select one of the available base map layers.  

![adjusting map view 1_75](https://cloud.githubusercontent.com/assets/7375034/13497339/cb3db43e-e122-11e5-8201-45458b3ef59e.gif)

**Comment by colinbeier** [comment]
**Adding things to the map**
You can add layers by clicking on the Layers tab, which will show you all the layers available to be added to the map. 
You can also use the search box to find layers.  
Once you find a layer you are interested in, you can click its name or checkbox to enable it. Once it is loaded it will display on the map. Some layers may take a few moments to load.  
![layers tab intro](https://cloud.githubusercontent.com/assets/7375034/13497936/c40ea74c-e125-11e5-868f-5f708535ad0d.gif)

**Comment by colinbeier** [comment]
Cary is it helpful to provide the slide text and GIFs this way?  If so I will do more later today.  If you want them in a different way, let me know.  Happy to do whatevs.  

I also have made some longer videos to explain how to use complex layers like PRISM, ClimAID, etc.  I wonder if we can put those in a modal and have them accessible somehow, maybe via a ? icon that sits next to the info icon, and/or a link in the info modal.

**Comment by colinbeier** [comment]
**Finding out more about a layer**
Click on the i icon [insert info icon here] to learn more about the layer and find a link to its source, where you can often find detailed data descriptions and relevant information.  For some layers, you can also **click directly on the map** to identify the value at that location.  
![layer info](https://cloud.githubusercontent.com/assets/7375034/13501031/09d6ee6c-e133-11e5-8a6b-46b4fb3b05ab.gif)

**Comment by caryfitzhugh** [comment]
Yeah, this is fine.  I can convert them into slides pretty easily.
If you want additional pages with details, just mail them over.

If you want to have a ? help button on different layers, tell me and I can
hook that in so that it "jumps" directly to the right slide in the wizard.

**Comment by colinbeier** [comment]
Sounds good.  

My thought was for PRISM and others where we have a video link, we would bring up a modal just for that purpose (an iframe with a bit of header text and the video).  Is that what you were thinking too?  So layers like that would have a ? help button but it would not point to the wizard with multiple generic slides.  it would point to a layer-specific modal with the corresponding gif / video.  make sense?  

Another question, do you think we should have an icon somewhere just indicating those layers that are active for GetInfo?  that might be helpful, but if its a lot of work, not necessary.

**Comment by caryfitzhugh** [comment]
We can do a modal with just a video.  A ? link on the layer would work.


We can indicate on a layer if it has get feature info... what icon? / how?

**Comment by colinbeier** [comment]
maybe a finger/hand icon (like what shows up now when you can click on something) or maybe the generic Google location 'teardrop' icon?

**Comment by caryfitzhugh** [comment]
WHere are you thinking it goes? in the legends (next to the name or
osmething).
In info modal (or both)

**Comment by caryfitzhugh** [comment]
@colinbeier the first one looks pretty sweet!

![image](https://cloud.githubusercontent.com/assets/445848/13530767/0d38a208-e1f1-11e5-9fa5-b08d6c5a1b01.png)

**Comment by caryfitzhugh** [comment]
@colinbeier any more slides, and just make them individual issues, I'll add them individually.

**Comment by caryfitzhugh** [comment]
deployed to gh pages.

**Comment by colinbeier** [comment]
looks good!  couple of minor edits -- 

1. Adjusting your map view... controls is mis-spelled.  
2. Finding out more about a layer... you can delete the text 'i icon' from the first sentence, since the icon is there.   Also that GIF is really grainy ... did you reduce the size, or maybe when I uploaded to gh it resized the file?

**Comment by caryfitzhugh** [comment]
fixed the typo.
removed the icon.
the image is what it is.  is 700 x 277 or so.
If you want to email me a "raw" copy, maybe I can drop it in.

**Comment by colinbeier** [comment]
Can't look at it at the moment, but I meant to leave the info icon itself, but delete the text 'i icon' ... not sure if that's what you meant.

I'll email you the raw gif in a few...

Colin Beier
SUNY ESF

On Mar 4, 2016 2:12 PM, Cary FitzHugh <notifications@github.com> wrote:

fixed the typo.
removed the icon.
the image is what it is. is 700 x 277 or so.
If you want to email me a "raw" copy, maybe I can drop it in.

**Comment by caryfitzhugh** [comment]
yup. ok!

**Comment by colinbeier** [comment]
nevermind, its a low-res raw file, trying to keep it as small as possible.

**Comment by caryfitzhugh** [comment]
ok.
