### ISSUE TITLE
05 Feb user testing notes -- FYI

### ISSUE THREAD

**Issue by colinbeier** [caryfitzhugh/NYCCSC-map-viewer#128]
FYI, this is based on 5 user testing sessions conducted by webinar.  

**Amanda Stevens, NYSERDA project manager**
> 
Here’s a link to the site I was talking about: http://maps.naturalresourcenavigator.org/. If you X out of the splash screen and then click “tour” at the top, it walks you through what I was talking about on the last call. (Note that the tour doesn’t seem to work in IE.)
 
>Mapper
·         Make Legend & Locations tabs orange, so they look like buttons
·         Change tab text
·         Add tour a la NRN
·         Legend text on many of the layers needs to be cleaned up (e.g., SLR, projections)
·         Make layer search more obvious, make text similar to Location search—“Type to search layers” or something like that 

**Darcy Branchini, Mann Library**
> Labels and/or information in the legends need to be clearer too
-  piggy back off of this, any acronyms should be explained somewhere (NARCCAP came up with two users)
- “Feet" for sea level rise; 8.5 for a scenario – what does that mean?
- Consistent units — precipitation – inches for historial, but cm for projected?  And/or differences between map and grapher
- Legend available on data grapher with fuller information available through modal
- Colors on the map came up a few times in different ways
- Layering and similar color schemes — can’t tell which layer is which – this came up mostly around the heatwaves and social vulnerability index question
- Color ranges within a given layer – very close in color so weren’t sure which color was applicable to an area they were interested in; opacity seems to complicate this issue (because then a given color value looks closer to a different value when lowering the opacity
- People didn’t expect the legend to be dynamic — meaning that’s where you will change scenarios, etc. (might go back to labeling “legend” as something different)<

**Ingrid Zabel, Cornell**
>Map Viewer:
·         Legends were not clear enough
o    Users were looking for units and descriptions to understand what they were seeing
o    Users were looking for instructions (e.g., it wasn't obvious they could click on regions or points to get information)
o    For climate data layers, the percentiles and "symbolize by" options seemed particularly confusing
·         Color scales could be hard to interpret: users sometimes had trouble distinguishing between different shades

**Comment by sasignell** [comment]
a few thoughts:

I took a look at the 'tour' on the NRN site... kind of cool, but I
personally don't think it does much to convey the possibilities of the
site.  Also totally useless on tablets and smaller-- the arrows get all
messed up and don't function correctly.  Perhaps we could just take a
screenshot and mark a few things up with photoshop, so just a static
image.

Personally, I prefer narrated videos and the kind of think Jesse did for
FEST. If you go to this page and click 'help' you'll see what I'm talking
about.  http://forestecoservices.net/wfr.php. Colin-- did you ever find out
from Jesse how he did those?

Regarding the legends and layer overlay problems, the fact is that we have
no control over most of the layer symbologies, so people will just have to
accept something less than ideal here.  That said, we should probably take
a look at our layers and try to improve them as best we can.

As far as units go, we probably could do a better job of explaining, but
again, the fact is that some of these data products are in english and
others in metric, so not much we can do there except hope the USA converts
to metric.  HA!



On Mon, Feb 8, 2016 at 12:43 PM, colinbeier <notifications@github.com>
wrote:

> FYI, this is based on 5 user testing sessions conducted by webinar.
>
> *Amanda Stevens, NYSERDA project manager*
>
> Here’s a link to the site I was talking about:
> http://maps.naturalresourcenavigator.org/. If you X out of the splash
> screen and then click “tour” at the top, it walks you through what I was
> talking about on the last call. (Note that the tour doesn’t seem to work in
> IE.)
>
> Mapper
> · Make Legend & Locations tabs orange, so they look like buttons
> · Change tab text
> · Add tour a la NRN
> · Legend text on many of the layers needs to be cleaned up (e.g., SLR,
> projections)
> · Make layer search more obvious, make text similar to Location
> search—“Type to search layers” or something like that
>
> *Darcy Branchini, Mann Library*
>
> Labels and/or information in the legends need to be clearer too
>
>    - piggy back off of this, any acronyms should be explained somewhere
>    (NARCCAP came up with two users)
>    - “Feet" for sea level rise; 8.5 for a scenario – what does that mean?
>    - Consistent units — precipitation – inches for historial, but cm for
>    projected? And/or differences between map and grapher
>    - Legend available on data grapher with fuller information available
>    through modal
>    - Colors on the map came up a few times in different ways
>    - Layering and similar color schemes — can’t tell which layer is which
>    – this came up mostly around the heatwaves and social vulnerability index
>    question
>    - Color ranges within a given layer – very close in color so weren’t
>    sure which color was applicable to an area they were interested in; opacity
>    seems to complicate this issue (because then a given color value looks
>    closer to a different value when lowering the opacity
>    - People didn’t expect the legend to be dynamic — meaning that’s where
>    you will change scenarios, etc. (might go back to labeling “legend” as
>    something different)<
>
> *Ingrid Zabel, Cornell*
>
> Map Viewer:
> · Legends were not clear enough
> o Users were looking for units and descriptions to understand what they
> were seeing
> o Users were looking for instructions (e.g., it wasn't obvious they could
> click on regions or points to get information)
> o For climate data layers, the percentiles and "symbolize by" options
> seemed particularly confusing
> · Color scales could be hard to interpret: users sometimes had trouble
> distinguishing between different shades
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/caryfitzhugh/NYCCSC-map-viewer/issues/128>.
>



-- 
Steve Signell
Frontier Spatial, L.L.C.
1062 Dean St.
Schenectady, NY 12309
518-232-1008
frontierspatial.com
steve@frontierspatial.com

**Comment by caryfitzhugh** [comment]
I can do a popup like that FEST thing.  

What should it say? any ideas?

**Comment by caryfitzhugh** [comment]
@colinbeier not sure how to execute this task.  Is it just a parent task, which spawned a few other issues? like #142 and others?

**Comment by colinbeier** [comment]
Yes, sorry, I just wanted a place to put the comments for reference purposes.  You can close the issue since we can always refer back to it as needed.
