### ISSUE TITLE
Potential Environmental Justice Areas 

### ISSUE THREAD

**Issue by sasignell** [caryfitzhugh/NYCCSC-map-viewer#130]
http://gis.ny.gov/gisdata/inventories/details.cfm?DSID=1273
http://www.dec.ny.gov/maps/pejalink.kmz
-- only format i can find is a KMZ, which is not easy to work with. contact info for data steward is on the GIS Clearinghouse page (first link), might see if the original shapefile is available. but first, i will check to see how much of a priority this is for NYSERDA. it is a very similar, if not identical, dataset to the Social Vulnerability Index we already have up.

**Comment by colinbeier** [comment]
Don't need this one, see my comments from earlier today, the SOVI layer will suffice.

Colin Beier
SUNY ESF

On Feb 8, 2016 2:23 PM, Steve Signell <notifications@github.com> wrote:

http://gis.ny.gov/gisdata/inventories/details.cfm?DSID=1273
http://www.dec.ny.gov/maps/pejalink.kmz
-- only format i can find is a KMZ, which is not easy to work with. contact info for data steward is on the GIS Clearinghouse page (first link), might see if the original shapefile is available. but first, i will check to see how much of a priority this is for NYSERDA. it is a very similar, if not identical, dataset to the Social Vulnerability Index we already have up.
