### ISSUE TITLE
Bulk Storage Sites in New York State 

### ISSUE THREAD

**Issue by sasignell** [caryfitzhugh/NYCCSC-map-viewer#131]
http://gis.ny.gov/gisdata/inventories/details.cfm?DSID=1253
ftp://ftp.dec.state.ny.us/der/FOIL/bulkstorageGIS.zip
-- a geojson marker layer would be ideal for this data, if possible

**Comment by sasignell** [comment]
This one is a kmz only so I'll have to try to convert it with ArcGIS if it's still a priority

**Comment by caryfitzhugh** [comment]
for my learning - what is bad about KMZ?
This site seems to imply it's just a format to convert from.
http://datajournalismi.blogspot.fi/2015/04/kml-to-geojson-to-topojson-on-mac-os-x.html?m=1

But it's got more deficiencies than that I think..?

**Comment by colinbeier** [comment]
About how many hours?  

I know these are a pain, so I'll try to get this knocked down (or off) the list, regardless...

**Comment by sasignell** [comment]
A kmz is just a zipped kml file, and sometimes some other stuff.  If you
rename the .kmz extension to .zip and unzip it you'll see what's in there.
Sometimes its the actual data, but more often than not, it contains a link
to the data source.  For example if you unzip the env. justice kmz
<http://www.dec.ny.gov/maps/pejalink.kmz> colin provided the link for get
the kml below, with the bolded link to the actual data (
http://www.dec.ny.gov/maps/peja.kmz).  Then you have to unzip that and then
parse to get the actual data.  So not too much fun.

<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://www.opengis.net/kml/2.2">
<Document>
<name>&lt;font face=&quot;helvetica&quot; font
color=&quot;#2E7B1B&quot;&gt;Potential Environmental Justice
Areas&lt;/font&gt;</name>
<open>1</open>
<NetworkLink>
<name>Potential Environmental Justice Areas</name>
<open>1</open>
<snippet>Data is automatically updated whenever the file is opened.
Right-click and select "Refresh" for additional updates.</snippet>
<styleUrl>#TOC</styleUrl>
<Style id="TOC">
<ListStyle><bgColor>00ffffff</bgColor><maxSnippetLines>4</maxSnippetLines></ListStyle>
</Style>
<refreshVisibility>1</refreshVisibility>
<flyToView>1</flyToView>
<Link>
<href>*http://www.dec.ny.gov/maps/peja.kmz
<http://www.dec.ny.gov/maps/peja.kmz>*</href>
<refreshMode>onChange</refreshMode>
</Link>
</NetworkLink>
</Document>
</kml>, e.g.



On Mon, Feb 8, 2016 at 5:07 PM, colinbeier <notifications@github.com> wrote:

> About how many hours?
>
> I know these are a pain, so I'll try to get this knocked down (or off) the
> list, regardless...
>
> On Feb 8, 2016, at 2:25 PM, Steve Signell wrote:
>
> > This one is a kmz only so I'll have to try to convert it with ArcGIS if
> it's still a priority
>
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/caryfitzhugh/NYCCSC-map-viewer/issues/131#issuecomment-181581411>
> .
>



-- 
Steve Signell
Frontier Spatial, L.L.C.
1062 Dean St.
Schenectady, NY 12309
518-232-1008
frontierspatial.com
steve@frontierspatial.com

**Comment by sasignell** [comment]
I got this going as a layer, but like the wells there are a ton of points-- perhaps we should do this like the wells?  I put a geojson and .gz on geoserver/www, e.g. http://52.2.5.122:8080/geoserver/www/bulkstorage.geojson.json.gz

**Comment by caryfitzhugh** [comment]
@sasignell the meta-data for this layer is all screwy.  FYI. I'd fix it, but I am not sure what it should say.

**Comment by caryfitzhugh** [comment]
@sasignell I am looking at how we might split it up...

**Comment by caryfitzhugh** [comment]
@colinbeier @sasignell the meta data from that page says the facilities are split into 3 groups
Petroleum Bulk Storage (PBS)
Major Oil Storage Facilities (MOSF)
Chemical Bulk Storage (CBS)

This is also updated daily... yeesh. :(

**Comment by colinbeier** [comment]
Can split it into three, either as layers or via toggle. Just scrape the data once, make it static, note the date / time of the data in the metadata or description, if possible

Colin Beier
SUNY ESF

On Feb 17, 2016 4:33 PM, Cary FitzHugh <notifications@github.com> wrote:

@colinbeier<https://github.com/colinbeier> @sasignell<https://github.com/sasignell> the meta data from that page says the facilities are split into 3 groups
Petroleum Bulk Storage (PBS)
Major Oil Storage Facilities (MOSF)
Chemical Bulk Storage (CBS)

This is also updated daily... yeesh. :(

**Comment by colinbeier** [comment]
fwiw, bulk storage layer is KILLING my browser (Chrome 47.02).  i'll ask if we can filter out the PBS.  that's like every tank outside of a gas station or in the parking lot of a grease pit.

**Comment by sasignell** [comment]
I say we just do a wms or ditch it.

**Comment by sasignell** [comment]
I fixed the metadata and converted it to wms instead of markers.  I know
its not ideal, but it works, and at some point we have to start considering
the amount of time required to deal with some of these secondary layers.

On Wed, Feb 17, 2016 at 5:32 PM, Steve Signell <steve@frontierspatial.com>
wrote:

> I say we just do a wms or ditch it.
> On Feb 17, 2016 5:02 PM, "colinbeier" <notifications@github.com> wrote:
>
>> fwiw, bulk storage layer is KILLING my browser (Chrome 47.02). i'll ask
>> if we can filter out the PBS. that's like every tank outside of a gas
>> station or in the parking lot of a grease pit.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/caryfitzhugh/NYCCSC-map-viewer/issues/131#issuecomment-185427683>
>> .
>>
>


-- 
Steve Signell
Frontier Spatial, L.L.C.
1062 Dean St.
Schenectady, NY 12309
518-232-1008
frontierspatial.com
steve@frontierspatial.com

**Comment by caryfitzhugh** [comment]
ok, @colinbeier is this done? It's WMS, and apparenlty works.

**Comment by colinbeier** [comment]
yep, looks good.  if NESCAUM or NYSERDA has issues, we'll reopen.
