### ISSUE TITLE
Add primary aquifers

### ISSUE THREAD

**Issue by sasignell** [caryfitzhugh/NYCCSC-map-viewer#133]
Primary Aquifers - 1:24,000 
http://gis.ny.gov/gisdata/inventories/details.cfm?DSID=1203
http://gis.ny.gov/gisdata/fileserver/?DSID=1203&file=WaterWellProgram.zip
i.zip

**Comment by sasignell** [comment]
Hey the WaterWellProgram.zip aren't aquifers-- they are point locations of wells... is this what you meant?
![image](https://cloud.githubusercontent.com/assets/4191479/12978889/c53a0b3c-d0a1-11e5-9a79-b139c2194e7a.png)

**Comment by colinbeier** [comment]
Here is the Primary Acquifers layer from DEC:

http://gis.ny.gov/gisdata/inventories/details.cfm?DSID=1232

http://gis.ny.gov/gisdata/fileserver/?DSID=1232&file=primaryaquifers.zip

**Comment by sasignell** [comment]
oh ok those got switched somehow

On Thu, Feb 11, 2016 at 9:36 AM, colinbeier <notifications@github.com>
wrote:

> Here is the Primary Acquifers layer from DEC:
>
> http://gis.ny.gov/gisdata/inventories/details.cfm?DSID=1232
>
> http://gis.ny.gov/gisdata/fileserver/?DSID=1232&file=primaryaquifers.zip
>
> On Feb 11, 2016, at 9:28 AM, Steve Signell wrote:
>
> > Hey the WaterWellProgram.zip aren't aquifers-- they are point locations
> of wells... is this what you meant?
> >
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/caryfitzhugh/NYCCSC-map-viewer/issues/133#issuecomment-182890920>
> .
>



-- 
Steve Signell
Frontier Spatial, L.L.C.
1062 Dean St.
Schenectady, NY 12309
518-232-1008
frontierspatial.com
steve@frontierspatial.com
