### ISSUE TITLE
Add water wells

### ISSUE THREAD

**Issue by sasignell** [caryfitzhugh/NYCCSC-map-viewer#135]
Water Wells 
http://gis.ny.gov/gisdata/inventories/details.cfm?DSID=1203
http://gis.ny.gov/gisdata/fileserver/?DSID=1203&file=WaterWellProgram.zip

**Comment by sasignell** [comment]
Here's the geojson for this:
[water_well_program.zip](https://github.com/caryfitzhugh/NYCCSC-map-viewer/files/126608/water_well_program.zip)

**Comment by caryfitzhugh** [comment]
I can pick this one up if you want.

**Comment by sasignell** [comment]
sure-- seems you got a good process for the geojsons

On Thu, Feb 11, 2016 at 10:35 AM, Cary FitzHugh <notifications@github.com>
wrote:

> I can pick this one up if you want.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/caryfitzhugh/NYCCSC-map-viewer/issues/135#issuecomment-182919113>
> .
>



-- 
Steve Signell
Frontier Spatial, L.L.C.
1062 Dean St.
Schenectady, NY 12309
518-232-1008
frontierspatial.com
steve@frontierspatial.com
