### ISSUE TITLE
converting NARCCAP to delta values

### ISSUE THREAD

**Issue by colinbeier** [caryfitzhugh/NYCCSC-map-viewer#141]
Art brought this up a couple of weeks ago, I'm circling back to it now:  

>1) We discussed showing decadal periods and NOT individual years.  The projections for any individual future year are meaningless, so we should displacing individual years on a map to avoid mis-use of the data.

We have the decades in there data-wise, just need a clearer way to show this.  Instead of showing 2039, 2049, etc. can it show 2030-2039, 2040-2049, etc.  

>2) I believe actual values are shown as opposed to difference values.  The actual values are also are again a misinterpretation of the data.  NARCCAP has NOT been biased corrected.  In other words it’s historical period values are not an exact representation of observed historical conditions (look at the data grapher and you will see that the historical NARCCAP and observed values rarely overlap, especially for smaller areas like counties).   Therefor saying it will be 68° in some future year is also biased.  To get around this a delta method is used.   SO the NARCAPP future decade values should be mapped as the difference (temperature) % difference (precip) between the historical period and the future decade that is selected. Given the format that we send the NARCCAP data in, it is possible to do this differencing within the Javascript.

Cary, we had an email exchange about this a little while ago.  You mentioned there was some earlier data in the NARRCAP json files - but I don't recall the length / time period of that data.  The earlier data, assuming it is for a period not in the future, would be the reference point for calculating the deltas for the future values.  Assuming we have ten years (or more) of temp and precip, the d3 code should calculate the mean of the reference data for the different seasons / months, and then use subtraction (future predicted minus recent observed) to calculate the deltas.  

We'll also need to edit a bunch of stuff - layer name, color bar caption, metadata / info modal - when we do this.   

I hope this is easy but let me know if there are issues.

**Comment by sasignell** [comment]
Maybe I could try tackling this one.  I should be able to figure this out
and can always call on Cary for help if need be.

On Mon, Feb 15, 2016 at 10:44 AM, colinbeier <notifications@github.com>
wrote:

> Art brought this up a couple of weeks ago, I'm circling back to it now:
>
> 1) We discussed showing decadal periods and NOT individual years. The
> projections for any individual future year are meaningless, so we should
> displacing individual years on a map to avoid mis-use of the data.
>
> We have the decades in there data-wise, just need a clearer way to show
> this. Instead of showing 2039, 2049, etc. can it show 2030-2039, 2040-2049,
> etc.
>
> 2) I believe actual values are shown as opposed to difference values. The
> actual values are also are again a misinterpretation of the data. NARCCAP
> has NOT been biased corrected. In other words it’s historical period values
> are not an exact representation of observed historical conditions (look at
> the data grapher and you will see that the historical NARCCAP and observed
> values rarely overlap, especially for smaller areas like counties).
> Therefor saying it will be 68° in some future year is also biased. To get
> around this a delta method is used. SO the NARCAPP future decade values
> should be mapped as the difference (temperature) % difference (precip)
> between the historical period and the future decade that is selected. Given
> the format that we send the NARCCAP data in, it is possible to do this
> differencing within the Javascript.
>
> Cary, we had an email exchange about this a little while ago. You
> mentioned there was some earlier data in the NARRCAP json files - but I
> don't recall the length / time period of that data. The earlier data,
> assuming it is for a period not in the future, would be the reference point
> for calculating the deltas for the future values. Assuming we have ten
> years (or more) of temp and precip, the d3 code should calculate the mean
> of the reference data for the different seasons / months, and then use
> subtraction (future predicted minus recent observed) to calculate the
> deltas.
>
> We'll also need to edit a bunch of stuff - layer name, color bar caption,
> metadata / info modal - when we do this.
>
> I hope this is easy but let me know if there are issues.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/caryfitzhugh/NYCCSC-map-viewer/issues/141>.
>



-- 
Steve Signell
Frontier Spatial, L.L.C.
1062 Dean St.
Schenectady, NY 12309
518-232-1008
frontierspatial.com
steve@frontierspatial.com

**Comment by colinbeier** [comment]
Sure, that would be great.  Thanks!

**Comment by caryfitzhugh** [comment]
yeah - cool. Steve ask away if you have questions.

:)

**Comment by sasignell** [comment]
Hey Cary,
     I think narccap is really close... just pushed changes to narccap.js
where i calculate a baseline averavge for 1990-199 in addition to the
binned averages (lines 41-58).  I think all we have to do is subtract this
from the binned values and send it t geojson-- see my comment on line 81.
I was having difficulty subtracting the arrays and figured you could do it
in a snap.  Hopefully I'm right!



On Mon, Feb 15, 2016 at 11:15 AM, Cary FitzHugh <notifications@github.com>
wrote:

> yeah - cool. Steve ask away if you have questions.
>
> :)
>
> On Mon, Feb 15, 2016 at 10:46 AM, colinbeier <notifications@github.com>
> wrote:
>
> > Sure, that would be great. Thanks!
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/caryfitzhugh/NYCCSC-map-viewer/issues/141#issuecomment-184262947
> >
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/caryfitzhugh/NYCCSC-map-viewer/issues/141#issuecomment-184277548>
> .
>



-- 
Steve Signell
Frontier Spatial, L.L.C.
1062 Dean St.
Schenectady, NY 12309
518-232-1008
frontierspatial.com
steve@frontierspatial.com

**Comment by caryfitzhugh** [comment]
ok! I'll check it out! thanks

**Comment by caryfitzhugh** [comment]
@colinbeier @sasignell done and pushed onto gh-pages.
I adjusted the legend as well.

I changed the text in the legends, something like "Projected Change in Precipitation (cm)"...  just think you all should double-check.
