### ISSUE TITLE
edits to ClimAID layers

### ISSUE THREAD

**Issue by colinbeier** [caryfitzhugh/NYCCSC-map-viewer#142]
Testers really struggled with this set of controls.  I am creating a video that explains how to use the entire layer, and we might snip bits of it to drop in animated GIFs in places (like small pop-ups).  But some degree of redundancy here cannot hurt, based on what I've seen with testers.  

A few edits and some tool tips or info pop-ups that would be helpful:

1. When a ClimAID layer is clicked on, can we have the map zoom to layer extent?  And could we have a help modal / info tool tip pop up come up automatically?  

2. **Scenarios**:  Edit text as follows: Scenario:  **O** low emissions (4.5)  **O** high emissions (8.5) 
(the **O** above represents the buttons)

2. **Percentile**:  can we add a tooltip or some text below to explain what's going on?  for example, the default position would be at the 50th percentile (median), and below it would say: "Median: half of the models predict less change, half predict greater change". The remaining text for the points on the slider would be "10th Percentile: nearly all models predict greater change", "25th Percentile: most models predict greater change", "75th Percentile: most models predict less change" and "90th Percentile: nearly all models predict less change." 

3. **for both Scenarios and Percentile**: can we add an info or question mark button that leads to a pop-up that provides a brief bit of text on what these options / variables are?  A hover over might work too, but I think the text for each will be too long.  

3. **Symbolize By**: this needs more explanation in a few places.  It might also make sense visually to move it below the color bar, since it is more of a scaling thing.   But if that's a PITA or looks bad, we can forget it.  I will cover it in my layer guide video, but I also think a hover-over or info/question button would be helpful.  It might say "Choose the range of data used to create the color ramp", with more explanation / demonstration in a modal.

**Comment by sasignell** [comment]
Hey Cary, can I just add a descriptio element to the parameter section of
the layerinfo.js and use that to cycle the text as the parameters change?

**Comment by caryfitzhugh** [comment]
You could probably use {{#if symbolize_by === "season"}}   <p> Some
description about the seasons </p> {{/if}}

If that's what you mean.  Yeah - that would work great I think.

**Comment by sasignell** [comment]
I added some tooltips to the climaid_temp layer.  Colin-- is this heading
in the right direction?  And Cary, is that adding this plugin
<https://www.npmjs.com/package/ractive-tooltip> the right way to do
tooltips?

http://52.2.5.122/NYCCSC-map-viewer/src/map_viewer.html?active-layers=climaid_temp

On Mon, Feb 15, 2016 at 12:01 PM, Cary FitzHugh <notifications@github.com>
wrote:

> You could probably use {{#if symbolize_by === "season"}} <p> Some
> description about the seasons </p> {{/if}}
>
> If that's what you mean. Yeah - that would work great I think.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/caryfitzhugh/NYCCSC-map-viewer/issues/142#issuecomment-184301608>
> .
>



-- 
Steve Signell
Frontier Spatial, L.L.C.
1062 Dean St.
Schenectady, NY 12309
518-232-1008
frontierspatial.com
steve@frontierspatial.com

**Comment by caryfitzhugh** [comment]
That plug in is probably a good start.

**Comment by colinbeier** [comment]
I like the tooltips - they are helpful.  Several of the testers I observed did not know about hover-over and even if the information popped up, it did not seem they absorbed it.  But this will definitely help.  

Can you do hover tooltips like this for all of the buttons, including the move to top, clone, info, etc. in lieu of the little yellow hover-over?  Or does this become messy?  

Cheers
Colin

**Comment by caryfitzhugh** [comment]
I believe that the plugin should make it very simple, right steve?

**Comment by sasignell** [comment]
Yep!

**Comment by caryfitzhugh** [comment]
schweet!

**Comment by colinbeier** [comment]
Steve, do you have a timeline for adding these tooltips?  I see them for ClimAID temps but not elsewhere.

**Comment by colinbeier** [comment]
Also, the ClimAID precip layer is still pushing an orange-red color bar (with only positive values) when the percentile is set to 75 or 90 and symbolized by percentile.  The rest of the various combinations are going tan to green, as they should.

**Comment by sasignell** [comment]
These should be fixed now.  Take a look at the tooltips

On Wed, Feb 17, 2016 at 9:50 PM, colinbeier <notifications@github.com>
wrote:

> Also, the ClimAID precip layer is still pushing an orange-red color bar
> (with only positive values) when the percentile is set to 75 or 90 and
> symbolized by percentile. The rest of the various combinations are going
> tan to green, as they should.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/caryfitzhugh/NYCCSC-map-viewer/issues/142#issuecomment-185518616>
> .
>



-- 
Steve Signell
Frontier Spatial, L.L.C.
1062 Dean St.
Schenectady, NY 12309
518-232-1008
frontierspatial.com
steve@frontierspatial.com

**Comment by colinbeier** [comment]
Cleared my cache, seems to still be doing the same thing with the legend.    tooltips look good.   BTW, you have emissions spelled wrong ... it only has one m

**Comment by sasignell** [comment]
Are you looking at this?

http://52.2.5.122/NYCCSC-map-viewer/src/map_viewer.html?active-layers=climaid_precip

 It's working for me there

On Thu, Feb 18, 2016 at 11:36 AM, colinbeier <notifications@github.com>
wrote:

> Cleared my cache, seems to still be doing the same thing with the legend.
> tooltips look good. BTW, you have emissions spelled wrong ... it only has
> one m
>
>
>
> On Feb 18, 2016, at 9:59 AM, Steve Signell wrote:
>
> > These should be fixed now. Take a look at the tooltips
> >
> > On Wed, Feb 17, 2016 at 9:50 PM, colinbeier <notifications@github.com>
> > wrote:
> >
> > > Also, the ClimAID precip layer is still pushing an orange-red color bar
> > > (with only positive values) when the percentile is set to 75 or 90 and
> > > symbolized by percentile. The rest of the various combinations are
> going
> > > tan to green, as they should.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> https://github.com/caryfitzhugh/NYCCSC-map-viewer/issues/142#issuecomment-185518616
> >
> > > .
> > >
> >
> >
> >
> > --
> > Steve Signell
> > Frontier Spatial, L.L.C.
> > 1062 Dean St.
> > Schenectady, NY 12309
> > 518-232-1008
> > frontierspatial.com
> > steve@frontierspatial.com
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/caryfitzhugh/NYCCSC-map-viewer/issues/142#issuecomment-185805730>
> .
>



-- 
Steve Signell
Frontier Spatial, L.L.C.
1062 Dean St.
Schenectady, NY 12309
518-232-1008
frontierspatial.com
steve@frontierspatial.com

**Comment by sasignell** [comment]
oh wait I see what you're talking about


On Thu, Feb 18, 2016 at 12:08 PM, Steve Signell <steve@frontierspatial.com>
wrote:

> Are you looking at this?
>
>
> http://52.2.5.122/NYCCSC-map-viewer/src/map_viewer.html?active-layers=climaid_precip
>
>  It's working for me there
>
> On Thu, Feb 18, 2016 at 11:36 AM, colinbeier <notifications@github.com>
> wrote:
>
>> Cleared my cache, seems to still be doing the same thing with the legend.
>> tooltips look good. BTW, you have emissions spelled wrong ... it only has
>> one m
>>
>>
>>
>> On Feb 18, 2016, at 9:59 AM, Steve Signell wrote:
>>
>> > These should be fixed now. Take a look at the tooltips
>> >
>> > On Wed, Feb 17, 2016 at 9:50 PM, colinbeier <notifications@github.com>
>> > wrote:
>> >
>> > > Also, the ClimAID precip layer is still pushing an orange-red color
>> bar
>> > > (with only positive values) when the percentile is set to 75 or 90 and
>> > > symbolized by percentile. The rest of the various combinations are
>> going
>> > > tan to green, as they should.
>> > >
>> > > —
>> > > Reply to this email directly or view it on GitHub
>> > > <
>> https://github.com/caryfitzhugh/NYCCSC-map-viewer/issues/142#issuecomment-185518616
>> >
>> > > .
>> > >
>> >
>> >
>> >
>> > --
>> > Steve Signell
>> > Frontier Spatial, L.L.C.
>> > 1062 Dean St.
>> > Schenectady, NY 12309
>> > 518-232-1008
>> > frontierspatial.com
>> > steve@frontierspatial.com
>> > —
>> > Reply to this email directly or view it on GitHub.
>> >
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/caryfitzhugh/NYCCSC-map-viewer/issues/142#issuecomment-185805730>
>> .
>>
>
>
>
> --
> Steve Signell
> Frontier Spatial, L.L.C.
> 1062 Dean St.
> Schenectady, NY 12309
> 518-232-1008
> frontierspatial.com
> steve@frontierspatial.com
>



-- 
Steve Signell
Frontier Spatial, L.L.C.
1062 Dean St.
Schenectady, NY 12309
518-232-1008
frontierspatial.com
steve@frontierspatial.com

**Comment by sasignell** [comment]
ok try it now


On Thu, Feb 18, 2016 at 12:10 PM, Steve Signell <steve@frontierspatial.com>
wrote:

> oh wait I see what you're talking about
>
>
> On Thu, Feb 18, 2016 at 12:08 PM, Steve Signell <steve@frontierspatial.com
> > wrote:
>
>> Are you looking at this?
>>
>>
>> http://52.2.5.122/NYCCSC-map-viewer/src/map_viewer.html?active-layers=climaid_precip
>>
>>  It's working for me there
>>
>> On Thu, Feb 18, 2016 at 11:36 AM, colinbeier <notifications@github.com>
>> wrote:
>>
>>> Cleared my cache, seems to still be doing the same thing with the
>>> legend. tooltips look good. BTW, you have emissions spelled wrong ... it
>>> only has one m
>>>
>>>
>>>
>>> On Feb 18, 2016, at 9:59 AM, Steve Signell wrote:
>>>
>>> > These should be fixed now. Take a look at the tooltips
>>> >
>>> > On Wed, Feb 17, 2016 at 9:50 PM, colinbeier <notifications@github.com>
>>> > wrote:
>>> >
>>> > > Also, the ClimAID precip layer is still pushing an orange-red color
>>> bar
>>> > > (with only positive values) when the percentile is set to 75 or 90
>>> and
>>> > > symbolized by percentile. The rest of the various combinations are
>>> going
>>> > > tan to green, as they should.
>>> > >
>>> > > —
>>> > > Reply to this email directly or view it on GitHub
>>> > > <
>>> https://github.com/caryfitzhugh/NYCCSC-map-viewer/issues/142#issuecomment-185518616
>>> >
>>> > > .
>>> > >
>>> >
>>> >
>>> >
>>> > --
>>> > Steve Signell
>>> > Frontier Spatial, L.L.C.
>>> > 1062 Dean St.
>>> > Schenectady, NY 12309
>>> > 518-232-1008
>>> > frontierspatial.com
>>> > steve@frontierspatial.com
>>> > —
>>> > Reply to this email directly or view it on GitHub.
>>> >
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/caryfitzhugh/NYCCSC-map-viewer/issues/142#issuecomment-185805730>
>>> .
>>>
>>
>>
>>
>> --
>> Steve Signell
>> Frontier Spatial, L.L.C.
>> 1062 Dean St.
>> Schenectady, NY 12309
>> 518-232-1008
>> frontierspatial.com
>> steve@frontierspatial.com
>>
>
>
>
> --
> Steve Signell
> Frontier Spatial, L.L.C.
> 1062 Dean St.
> Schenectady, NY 12309
> 518-232-1008
> frontierspatial.com
> steve@frontierspatial.com
>



-- 
Steve Signell
Frontier Spatial, L.L.C.
1062 Dean St.
Schenectady, NY 12309
518-232-1008
frontierspatial.com
steve@frontierspatial.com

**Comment by caryfitzhugh** [comment]
@colinbeier is this completed? I see stuff on gh-pages, but wanted to have you check. I'm scrubbing the issues before we release today.

**Comment by colinbeier** [comment]
nearly.  i am still working on a video tutorial specifically for this layer, but that will come after this release, and it is unrelated to this work.  

only thing left is, can you have the map zoom to layer extent when ClimAID is turned on?  way back when we used to have this feature for the SLR data.  not sure if it had to be removed or just got lost in the fray.  it's a minor detail, not required, but might be helpful so that users can get a better sense of what they are looking at.

**Comment by caryfitzhugh** [comment]
I can add a zoom-to-layer extent the first time you click climad layer
active.
