### ISSUE TITLE
Narccap and Climaid often timing out... cdn related?

### ISSUE THREAD

**Issue by sasignell** [caryfitzhugh/NYCCSC-map-viewer#143]
from the console:

XMLHttpRequest cannot load https://d3k0ernyjb0bdf.cloudfront.net/geoserver/www/counties.geojson.json. The 'Access-Control-Allow-Origin' header has a value 'http://localhost' that is not equal to the supplied origin. Origin 'http://caryfitzhugh.github.io' is therefore not allowed access.

**Comment by caryfitzhugh** [comment]
Yes, CDN related.. hrm...

**Comment by caryfitzhugh** [comment]
I'm looking at this now.

**Comment by caryfitzhugh** [comment]
i saw it once... but can't reproduce.  If things happen again - I'll try to look at this again. :(

**Comment by sasignell** [comment]
Haven't seen this in a while so closing
