### ISSUE TITLE
Add NARCCAP Click For Temp/Precip details

### ISSUE THREAD

**Issue by caryfitzhugh** [caryfitzhugh/NYCCSC-map-viewer#144]
Add it like we did for invasives.

**Comment by sasignell** [comment]
want me to do these?

On Thu, Feb 18, 2016 at 10:15 AM, Cary FitzHugh <notifications@github.com>
wrote:

> Add it like we did for invasives.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/caryfitzhugh/NYCCSC-map-viewer/issues/144>.
>



-- 
Steve Signell
Frontier Spatial, L.L.C.
1062 Dean St.
Schenectady, NY 12309
518-232-1008
frontierspatial.com
steve@frontierspatial.com

**Comment by caryfitzhugh** [comment]
hey steve, let me do this first one.  to get the kinks out. and then you
can do the other ones... I'm nearly done, but there are a few gotchas...

**Comment by sasignell** [comment]
sounds good

On Thu, Feb 18, 2016 at 10:19 AM, Cary FitzHugh <notifications@github.com>
wrote:

> hey steve, let me do this first one. to get the kinks out. and then you
> can do the other ones... I'm nearly done, but there are a few gotchas...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/caryfitzhugh/NYCCSC-map-viewer/issues/144#issuecomment-185770377>
> .
>



-- 
Steve Signell
Frontier Spatial, L.L.C.
1062 Dean St.
Schenectady, NY 12309
518-232-1008
frontierspatial.com
steve@frontierspatial.com

**Comment by caryfitzhugh** [comment]
ok @sasignell .  

the basic idea is this:
the L.SVGOverlay layer has a function (find_polygon_with_click).

All that does is find the SVG path element which a click event is inside of.

So the way it works is this:

when the layer is being rendered by d3, any data you want to get on the click has to be added as a data attribute to the SVG element (I used data-count, and data-county) in my two examples.

Use the find_polygon_with_click, to find the polygon that is being clicked on.
And thne use .getAttribute() to read the values out.

The find_geo_json function should return a hash of data.

And lastly, in the map_viewer, around like 465, we render the data in the modal.

Enjoy!

**Comment by sasignell** [comment]
did you push the changes?

On Thu, Feb 18, 2016 at 10:28 AM, Cary FitzHugh <notifications@github.com>
wrote:

> ok @sasignell <https://github.com/sasignell> .
>
> the basic idea is this:
> the L.SVGOverlay layer has a function (find_polygon_with_click).
>
> All that does is find the SVG path element which a click event is inside
> of.
>
> So the way it works is this:
>
> when the layer is being rendered by d3, any data you want to get on the
> click has to be added as a data attribute to the SVG element (I used
> data-count, and data-county) in my two examples.
>
> Use the find_polygon_with_click, to find the polygon that is being clicked
> on.
> And thne use .getAttribute() to read the values out.
>
> The find_geo_json function should return a hash of data.
>
> And lastly, in the map_viewer, around like 465, we render the data in the
> modal.
>
> Enjoy!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/caryfitzhugh/NYCCSC-map-viewer/issues/144#issuecomment-185774798>
> .
>



-- 
Steve Signell
Frontier Spatial, L.L.C.
1062 Dean St.
Schenectady, NY 12309
518-232-1008
frontierspatial.com
steve@frontierspatial.com

**Comment by caryfitzhugh** [comment]
whoops. pushed.
