### ISSUE TITLE
Rearrange climate data subfolders

### ISSUE THREAD

**Issue by sasignell** [caryfitzhugh/NYCCSC-map-viewer#147]
How about 2 subfolders: precip & temp?  

Right now it doesn't really make sense.

**Comment by colinbeier** [comment]
Another solution would be to put the historical extreme precip rasters in the Historical folder, and put the projected extreme precip in the projected folder.  They really are two completely different datasets / map layers.

**Comment by sasignell** [comment]
Which way you want to go?  Personally I'd think it might be more satisfying
to view all precip together, then all temp together, but that's just a
guess.

Kind of a pain to split it in two if we don't have to, but I could go
either way

On Fri, Mar 4, 2016 at 12:42 PM, colinbeier <notifications@github.com>
wrote:

> Another solution would be to put the historical extreme precip rasters in
> the Historical folder, and put the projected extreme precip in the
> projected folder. They really are two completely different datasets / map
> layers.
>
> On Mar 3, 2016, at 7:43 PM, Steve Signell wrote:
>
> > How about 2 subfolders: precip & temp?
> >
> > Right now it doesn't really make sense.
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/caryfitzhugh/NYCCSC-map-viewer/issues/147#issuecomment-192376147>
> .
>



-- 
Steve Signell
Frontier Spatial, L.L.C.
1062 Dean St.
Schenectady, NY 12309
518-232-1008
frontierspatial.com
steve@frontierspatial.com

**Comment by colinbeier** [comment]
the historical vs projected split is an important one too.  i'm a bit hesitant to make changes in how the climate data are organized at this stage, but what you propose makes sense.  let's do it.  if someone doesn't like it, we can deal with that later.

**Comment by sasignell** [comment]
ok

On Fri, Mar 4, 2016 at 12:48 PM, colinbeier <notifications@github.com>
wrote:

> the historical vs projected split is an important one too. i'm a bit
> hesitant to make changes in how the climate data are organized at this
> stage, but what you propose makes sense. let's do it. if someone doesn't
> like it, we can deal with that later.
>
> On Mar 4, 2016, at 12:45 PM, Steve Signell wrote:
>
> > Which way you want to go? Personally I'd think it might be more
> satisfying
> > to view all precip together, then all temp together, but that's just a
> > guess.
> >
> > Kind of a pain to split it in two if we don't have to, but I could go
> > either way
> >
> > On Fri, Mar 4, 2016 at 12:42 PM, colinbeier <notifications@github.com>
> > wrote:
> >
> > > Another solution would be to put the historical extreme precip rasters
> in
> > > the Historical folder, and put the projected extreme precip in the
> > > projected folder. They really are two completely different datasets /
> map
> > > layers.
> > >
> > > On Mar 3, 2016, at 7:43 PM, Steve Signell wrote:
> > >
> > > > How about 2 subfolders: precip & temp?
> > > >
> > > > Right now it doesn't really make sense.
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub.
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> https://github.com/caryfitzhugh/NYCCSC-map-viewer/issues/147#issuecomment-192376147
> >
> > > .
>
> > >
> >
> >
> >
> > --
> > Steve Signell
> > Frontier Spatial, L.L.C.
> > 1062 Dean St.
> > Schenectady, NY 12309
> > 518-232-1008
> > frontierspatial.com
> > steve@frontierspatial.com
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/caryfitzhugh/NYCCSC-map-viewer/issues/147#issuecomment-192377635>
> .
>



-- 
Steve Signell
Frontier Spatial, L.L.C.
1062 Dean St.
Schenectady, NY 12309
518-232-1008
frontierspatial.com
steve@frontierspatial.com
