### ISSUE TITLE
Add icon to label layers that are getinfo enabled

### ISSUE THREAD

**Issue by colinbeier** [caryfitzhugh/NYCCSC-map-viewer#148]
i would like to indicate which layers are Get Info enabled, just with an icon (something like this: https://cdn2.iconfinder.com/data/icons/flat-style-svg-icons-part-1/512/location_marker_pin-512.png) that sits next to the info icon on the layer tree, and somewhere logical in the legends tab. you would not need to be able to click on the icon, but just a tooltip saying 'Get info by clicking on map' would be great.

**Comment by caryfitzhugh** [comment]
![image](https://cloud.githubusercontent.com/assets/445848/13538931/34668a5a-e21b-11e5-872d-8d0ea1c8e95b.png)

little icons in-place!

**Comment by colinbeier** [comment]
booyakasha!  noice.
