### ISSUE TITLE
Wizard Slide: Using the Legends tab

### ISSUE THREAD

**Issue by colinbeier** [caryfitzhugh/NYCCSC-map-viewer#150]
**Using the Legends tab**

- Each layer has a set of buttons that vary depending on the functions available for that layer.  
- All layers have: [[double up arrows]] which moves the layer to the **top** of the map, [[eye]] which **hides** or shows the layer, [[info]] which provides **layer information**, and [[trash]] which **removes** the layer from the view
- **Opacity** can be adjusted using the slider 
- **Expand / Collapse all** – these buttons change how the legend information is viewed in the sidebar. It does not affect how layers appear in the map view.  Each legend can also be opened or closed by clicking on the layer name or the triangle to the left. 
- **Hide all** – this hides all layers but does not remove them from the map view or change how their legends appear in the sidebar. 
- **Remove all** – this removes all layers from the map and their legends from the sidebar.  

![using legends tab](https://cloud.githubusercontent.com/assets/7375034/13544787/a855811e-e248-11e5-8596-1d4629f1a352.gif)

**Comment by caryfitzhugh** [comment]
Whoops. that's not it.
