### ISSUE TITLE
Wizard Slide: Ordering layers

### ISSUE THREAD

**Issue by colinbeier** [caryfitzhugh/NYCCSC-map-viewer#151]
**Ordering layers**
If a layer is active but you cannot see any features, it may be hidden behind other layers. Layers are ordered in the sidebar as they are ‘stacked’ in the map view. 

You can use the [[double up arrows]] to move layers to the top, or click and drag on the [[hand]] to drag layers into the order you prefer.  Note that some types of layers will always draw on top of other layers - and these will not have the [[double up arrows]] or [[hand]] available. You can always hide [[eye]] or remove [[trash]] these layers to take them out of the map view.  

![using legends tab](https://cloud.githubusercontent.com/assets/7375034/13544876/9f37243c-e24a-11e5-8eef-4ebdd71c8a11.gif)

**Comment by caryfitzhugh** [comment]
This one is done.
