### ISSUE TITLE
Wizard Slide: Printing the Map View

### ISSUE THREAD

**Issue by colinbeier** [caryfitzhugh/NYCCSC-map-viewer#152]
**Printing the map**
The [[printer]] button will export your map and legends to a layout and open the print dialog window automatically from your browser. 

The print layout includes a full-page map view and one or more additional pages for legend information. Note that the map view that is exported includes the area beneath the sidebar. 

_Hint: you can hide the sidebar by double-clicking on any tab name, or clicking on the name of the open tab. When the sidebar is collapsed, the map view shows what will be sent to the print layout._  

![printing the map](https://cloud.githubusercontent.com/assets/7375034/13544977/c0916bf4-e24c-11e5-9309-652858ead079.gif)

**Comment by colinbeier** [comment]
Can you delete the last sentence there?  _Each layer has a set of buttons that vary depending on the functions available for that layer._  Looks like it got carried over somehow from another slide :)

**Comment by caryfitzhugh** [comment]
Ha. Oops.
