### ISSUE TITLE
Wizard Slide: NOAA Sea Level Rise

### ISSUE THREAD

**Issue by colinbeier** [caryfitzhugh/NYCCSC-map-viewer#153]
I would like to have a wizard slide, either as part of the existing deck, or as a standalone in its own modal, for the SLR data.  Below is text and GIF

**How to use the NOAA Sea Level Rise layer**
This interactive layer gives you access to sea level maps based on model simulations of between 0-6 feet rise in the mean height of high water (MHHW), provided by NOAA as a web service. 

Use the slider to adjust the mean height of high water (MHHW) in one-foot increments from 0 to +6.   _Please note the map data may take a few moments to load from the NOAA server._

You may also select which variable appears in the map: **Sea Level**, the predicted sea level (see color bar for rough estimate of depth), and **Confidence**, the relative degree of confidence in model predictions of sea level at a given location.  See the NOAA site for more information.  

![slr noaa](https://cloud.githubusercontent.com/assets/7375034/13556347/51367c54-e3a5-11e5-8c2b-c53bdd7e985e.gif)

**Comment by caryfitzhugh** [comment]
Adding here: 
![nycscc map viewer 2016-03-07 10-59-24](https://cloud.githubusercontent.com/assets/445848/13574798/b90597a8-e453-11e5-831e-efb95621ccb3.png)

Click and the modal comes up.  

We can add these to any layer we want.

**Comment by colinbeier** [comment]
You sir are the Mayor of Awesometown.  Thanks.
