### ISSUE TITLE
GetInfo not working consistently for PRISM, NARCCAP

### ISSUE THREAD

**Issue by colinbeier** [caryfitzhugh/NYCCSC-map-viewer#154]
Not sure what is going on, but not getting a modal to pop up when I click on polygons for either PRISM or NARCCAP.  Earlier today it was spotty, now its not seeming to work at all.  

I am running a version of Chrome on OS X that is telling me that it no longer will be supported by Google (yes i need to upgrade my OS).   Maybe that has something to do with it?  I am trying to check with Safari but the gh page is quite slow / not loading there.

**Comment by colinbeier** [comment]
Reloaded the map in Chrome and now it appears to be working.

I did notice a bug in Safari though -- the color bars are not showing up for those rendered via d3.  The numbers are there but no boxes.  I am running an old version of Safari which may be the issue.  Version 6.1.6 (7537.78.2)

**Comment by colinbeier** [comment]
Nope, GetInfo is still dodgy.  I am trying to record a video for PRISM and this is killing me!  Not sure what's up.

**Comment by caryfitzhugh** [comment]
ok. I'll look.

**Comment by caryfitzhugh** [comment]
create a new issue for safari.

What are you doing in the PRISM video? That may help me narrow down what is going on.

**Comment by caryfitzhugh** [comment]
@colinbeier I do notice something, debugging.

**Comment by caryfitzhugh** [comment]
So - the point location is probably 100% broken.. DOH! glad we found it at least. something about... the lat / lng and the point-in-polygon code seems to be borked.  hrm....

**Comment by caryfitzhugh** [comment]
It is "correct" - or seems to be in the default zoom. But changing zoom gets it wonked. have to run, but will look at this more in a bit.
