### ISSUE TITLE
Wizard Slide: ClimAID

### ISSUE THREAD

**Issue by colinbeier** [caryfitzhugh/NYCCSC-map-viewer#157]
**About the data**: This layer provides access to a set of coarse-resolution gridded climate predictions, developed for the NYS ClimAID project. 

- **Year**: select predictions for either 2020, 2050 or 2080
- **Scenario**: select either a low (4.5) or high (8.5) emissions scenario
- **Percentile**: select data that represents different percentiles of the range of all model predictions generated by the ClimAID simulations. The 50th percentile or median prediction is the default value. For the 10th percentile, 90% of predictions are of greater magnitude; for the 90th percentile, only 10% of predictions are of greater magnitude.  
- **Symbolize by**: the legend color bar can be set to span different ranges of the ClimAID data, based on the year, scenario or model percentile. To use this feature, choose the factor you would like to hold constant, and vary the other factors to see how the data changes in the map. For example, if you want to see how temperatures in 2080 might change, select 2080 and ‘summarize by year’, then use the toggle buttons to vary the scenario and model percentiles.  

**Note**: when this layer is activated, the **map will automatically zoom to the full geographic extent** of the data provided. You can adjust the map view manually or return to the default view using the [[home]] button.  

![climaid layer controls2](https://cloud.githubusercontent.com/assets/7375034/13611666/ac8b03ee-e531-11e5-868d-e182fc986feb.gif)

**Comment by colinbeier** [comment]
Please edit the header on the slide to say "Using the ClimAID layers"... right now it says NARCCAP.  thanks!

**Comment by caryfitzhugh** [comment]
oy.
