### ISSUE TITLE
Map getting slower to load: is it the slide GIFs? 

### ISSUE THREAD

**Issue by colinbeier** [caryfitzhugh/NYCCSC-map-viewer#158]
Are all of the Wizard slide GIFs loading up in the browser ahead of time?  I've just noticed the map on the gh page is taking longer and longer to load up, since we added the Wizard.  Maybe just coincidence.

**Comment by caryfitzhugh** [comment]
Hrm... I don't think so. but I can check.

**Comment by caryfitzhugh** [comment]
yes. it was the GIFs being inlined.
oy!
all 20MB downloaded on page load. zoiks.

**Comment by colinbeier** [comment]
is there an easy work around?

**Comment by caryfitzhugh** [comment]
yeah - easy peasy. I just did it.  in fact, already done! :)

**Comment by colinbeier** [comment]
Nice thanks!

Colin Beier
SUNY ESF

On Mar 9, 2016 12:23 PM, Cary FitzHugh <notifications@github.com> wrote:
yeah - easy peasy. I just did it. in fact, already done! :)
