### ISSUE TITLE
Need to change nomenclature on legend tab to “legend/map controls”

### ISSUE THREAD

**Issue by sasignell** [caryfitzhugh/NYCCSC-map-viewer#159]

**Comment by sasignell** [comment]
OK 'Legend/Controls' is too big to fit... we either make the tab wider or explore some alternatives.  Here are a few off the top of my head

Map Key
toolbox
Active (e.g. terria.js)
Showing

**Comment by colinbeier** [comment]
Can you replace the slash / with an ampersand & please?  Thanks :)
