### ISSUE TITLE
Create a modal that indicates additional layers may be in the clearinghouse but not the map.

### ISSUE THREAD

**Issue by sasignell** [caryfitzhugh/NYCCSC-map-viewer#162]

**Comment by caryfitzhugh** [comment]
@colinbeier so when do we show this modal?

**Comment by colinbeier** [comment]
Maybe we add this content to a splash modal that also leads to the wizard?

Colin Beier
SUNY ESF

On Mar 17, 2016 10:11 AM, Cary FitzHugh <notifications@github.com> wrote:

@colinbeier<https://github.com/colinbeier> so when do we show this modal?

**Comment by colinbeier** [comment]
i'll write some text for the Welcome slide on the wizard and it will include this notice that other layers exist.   

Cary, is there any way we can spruce up the modal so it 1) has rounded edges and 2) is animated (i.e. spring-loaded)?  These are very minor aesthetic things but would be nice.

**Comment by caryfitzhugh** [comment]
Spring loaded? i.e .  expands from the top?

Rounded edges is an asthetic issue -- the entire site (except for a few
buttons) is square cornered... I can change it to rounded if you want
though.

**Comment by colinbeier** [comment]
Sorry, I guess I mean animated (dropping in) instead of just popping on and off. But it's really not a significant thing, just aesthetic. As are the rounded corners... figured these were easy enough.

Colin Beier
SUNY ESF

On Mar 25, 2016 11:30 AM, Cary FitzHugh <notifications@github.com> wrote:
Spring loaded? i.e . expands from the top?

Rounded edges is an asthetic issue -- the entire site (except for a few
buttons) is square cornered... I can change it to rounded if you want
though.

**Comment by caryfitzhugh** [comment]
I'm about 1/2 done on this...

**Comment by caryfitzhugh** [comment]
@colinbeier I have pushed animation / rounded corners. I had to drop the arrows b/c of CSS issues.
But it sounds like no one used them anyway...

What text do you want?

I assume you want a modal to come up automatically when coming to the viewer (first time a user comes or all the time? -- I'd suggest only on the first time).

What should this intro modal say? 
Should it just be the wizard, and we add some text in there about other stuff being in different places?

**Comment by colinbeier** [comment]
Thanks.  A couple of questions:

1. Can you keep the arrows with rounded corners but drop the animation? Or do the rounded corners kill the arrows?  I really like the arrows.  I would rather keep arrows and lose animation.  I do think people used them, and the back to start button is a failsafe for dummies.  

2. For the animation, is it possible to have the modal pop up (or scale up from the middle of the page) instead of drop down?  Or can it somehow be smoother or slower? It just seems very fast.  

Yes, we'll just make the wizard the intro modal.  I am waiting on Lisa for text about other layers being accessed elsewhere in the site.  I will add that to text I'm working on to replace what's there.

**Comment by caryfitzhugh** [comment]
The animation is fast, b/c the HTML changes too quickly internally, so it
looks wrong.  The modal basically clears (so it looks all weird) and then
slides closed.  Not a great effect.
To "fix" that, I'd need to rework how modals are triggered, which is a
pretty big task.  :(

I can't really make it grow from somewhere else on the page without a bunch
of JS.  It pulls down from the top , middle.
It's all done in CSS now, which is really nice and simple.
JS would make it quite complicated.

I can keep the arrows and keep the rounded corners.    And drop the
animation..   ?

**Comment by colinbeier** [comment]
OK, sorry for the hassle. Let's keep the rounded corners and arrows, drop the animation for now.  I hope it hasn't been too big of a time waster.

**Comment by caryfitzhugh** [comment]
ok @colinbeier this is just waiting on some text from your keyboard - I'll add it to the top of the welcome modal...

**Comment by colinbeier** [comment]
Here's my placeholder. I will send it to Lisa for edits.  Might as well put it up now though.  

**WELCOME!**
Thanks for visiting the NYCCSC Map Viewer: a place to interactively explore data and create maps related to climate change impacts, vulnerability and adaptation across New York State. 

**What's in the Map?**
This map viewer contains only a portion of the mappable data sources available in the Clearinghouse, such as other online maps and databases, GIS files, map images and other content, which may be located here.  
**What's _Not_ in the Map?**
Our library of viewable map layers and interactive map functions has been curated by NYSERDA and the site developers, based on input from sector-oriented expert focus groups. If you have suggestions for updates, changes or layers to be added / removed, we welcome your input here! 
**Using the Viewer**
Before getting started, scroll through this Map Guide to get familiar with the layout and functions of the interface. Most layers contain multiple data sources that can be explored with map controls. Many layers can be clicked upon in the map to provide more specific local information or data values. You can also share your map digitally or create pdf maps with legends.

**Comment by colinbeier** [comment]
Oops, hang on.

**Comment by colinbeier** [comment]
WELCOME!
Thanks for visiting the NYCCSC Map Viewer: a place to interactively explore data and create maps related to climate change impacts, vulnerability and adaptation across New York State.

What's in the Map?
Our library of viewable map layers and interactive map functions has been curated by NYSERDA and the site developers, based on input from sector-oriented expert focus groups. If you have suggestions for updates, changes or layers to be added / removed, we welcome your input here! 
**What's _Not_ in the Map?**
Our map viewer contains only a portion of the mappable data sources available in the Clearinghouse, such as other online maps and databases, GIS files, map images and other content, which may be located here.
**Using the Viewer**
Before getting started, scroll through this Map Guide to get familiar with the layout and functions of the interface. Most layers contain multiple data sources that can be explored with map controls. Many layers can be clicked upon in the map to provide more specific local information or data values. You can also share your map digitally or create pdf maps with legends.
