### ISSUE TITLE
Is it possible to create a save a map(s) feature, similar to the one on the data tool

### ISSUE THREAD

**Issue by sasignell** [caryfitzhugh/NYCCSC-map-viewer#168]

**Comment by sasignell** [comment]
We should be able to implement this fairly easily

**Comment by caryfitzhugh** [comment]
@sasignell 
Can you add a PHP endpoint like so:

/savemap.php
* POST
* body contains one field *data*
* returns a token
* do something with SQL to avoid saving duplicates (maybe an MD5 hash?)

/getmap.pho
* GET
* parameter "token"
* returns the data that was saved

If I have these two endpoints, I can put together a save map function.

**Comment by sasignell** [comment]
Sure.  How about an md5 hash of 'timestamp' || 'data'  ... that should
produce unique hashes forever, right?

On Tue, Mar 22, 2016 at 10:25 AM, Cary FitzHugh <notifications@github.com>
wrote:

> @sasignell <https://github.com/sasignell>
> Can you add a PHP endpoint like so:
>
> /savemap.php
>
>    - POST
>    - body contains one field *data*
>    - returns a token
>    - do something with SQL to avoid saving duplicates (maybe an MD5 hash?)
>
> /getmap.pho
>
>    - GET
>    - parameter "token"
>    - returns the data that was saved
>
> If I have these two endpoints, I can put together a save map function.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/caryfitzhugh/NYCCSC-map-viewer/issues/168#issuecomment-199838147>
>



-- 
Steve Signell
Frontier Spatial, L.L.C.
1062 Dean St.
Schenectady, NY 12309
518-232-1008
frontierspatial.com
steve@frontierspatial.com

**Comment by sasignell** [comment]
OK The endpoints are:

http://52.2.5.122/api/v1/savemap.php?

http://52.2.5.122/api/v1/getmap.php?

On Tue, Mar 22, 2016 at 10:37 AM, Steve Signell <steve@frontierspatial.com>
wrote:

> Sure.  How about an md5 hash of 'timestamp' || 'data'  ... that should
> produce unique hashes forever, right?
>
> On Tue, Mar 22, 2016 at 10:25 AM, Cary FitzHugh <notifications@github.com>
> wrote:
>
>> @sasignell <https://github.com/sasignell>
>> Can you add a PHP endpoint like so:
>>
>> /savemap.php
>>
>>    - POST
>>    - body contains one field *data*
>>    - returns a token
>>    - do something with SQL to avoid saving duplicates (maybe an MD5
>>    hash?)
>>
>> /getmap.pho
>>
>>    - GET
>>    - parameter "token"
>>    - returns the data that was saved
>>
>> If I have these two endpoints, I can put together a save map function.
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/caryfitzhugh/NYCCSC-map-viewer/issues/168#issuecomment-199838147>
>>
>
>
>
> --
> Steve Signell
> Frontier Spatial, L.L.C.
> 1062 Dean St.
> Schenectady, NY 12309
> 518-232-1008
> frontierspatial.com
> steve@frontierspatial.com
>



-- 
Steve Signell
Frontier Spatial, L.L.C.
1062 Dean St.
Schenectady, NY 12309
518-232-1008
frontierspatial.com
steve@frontierspatial.com

**Comment by caryfitzhugh** [comment]
Hey steve,

The hash is meant to be consistent, so if someone saves a map with a set of
layers, and then someone tries to save that same set later, we won't add a
new record to the db.  Just an optimization, that may be unnecessary...

**Comment by sasignell** [comment]
OK I'll remove the timestamp then and just hash the json data.  Will that
work?

On Tue, Mar 22, 2016 at 11:09 AM, Cary FitzHugh <notifications@github.com>
wrote:

> Hey steve,
>
> The hash is meant to be consistent, so if someone saves a map with a set of
> layers, and then someone tries to save that same set later, we won't add a
> new record to the db. Just an optimization, that may be unnecessary...
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/caryfitzhugh/NYCCSC-map-viewer/issues/168#issuecomment-199858396>
>



-- 
Steve Signell
Frontier Spatial, L.L.C.
1062 Dean St.
Schenectady, NY 12309
518-232-1008
frontierspatial.com
steve@frontierspatial.com

**Comment by caryfitzhugh** [comment]
that should...

**Comment by sasignell** [comment]
done

On Tue, Mar 22, 2016 at 11:31 AM, Cary FitzHugh <notifications@github.com>
wrote:

> that should...
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/caryfitzhugh/NYCCSC-map-viewer/issues/168#issuecomment-199867401>
>



-- 
Steve Signell
Frontier Spatial, L.L.C.
1062 Dean St.
Schenectady, NY 12309
518-232-1008
frontierspatial.com
steve@frontierspatial.com

**Comment by caryfitzhugh** [comment]
sorry. this isn't done.

@sasignell the POST to the server seems to fail...

Is the savemap a POST?

**Comment by caryfitzhugh** [comment]
@sasignell nudge / bump :)

**Comment by colinbeier** [comment]
Given the circumstances, we're going to have to punt on this until after official launch.  I would like to have a release by tomorrow if possible, Thursday at latest. If you guys disagree, let me know.

**Comment by caryfitzhugh** [comment]
Yeah - this one is pending some work from Steve.  (or my mistake, and needs
some help from Steve to know what's up...)
I'll just hide the share button for now....

**Comment by colinbeier** [comment]
I think you can leave the button with the other two share functions (API strings) alone.  i figured this sharing option was going to be added in the UI to that modal anyways... but maybe not?

**Comment by caryfitzhugh** [comment]
It replaced it - since the string share thing was sorta dumb.  At least,
maybe I mistook what was asked.
I could try to re-add the stirng thing if ppl actually wanted it.

**Comment by caryfitzhugh** [comment]
the string thing was a "placeholder" for the "real" sharing

**Comment by colinbeier** [comment]
OK, well we'll leave it closed for now, I will explain the situation to Lisa et al.  seems you guys feel pretty confident it will work with some, er, work.  still the case?

**Comment by caryfitzhugh** [comment]
yeah -I'm pretty confident that if I just got the silly call working, it
would save / load the map with a nice little URL there, all the other
pieces are there.
I may be able to debug Steve's code tonight and get it going...

**Comment by sasignell** [comment]
I may be able to get to this tomorrow am... I'll let you know

**Comment by sasignell** [comment]
OK its should work just like the adk atlas site now:


http://52.2.5.122/api/v1/savemap.php
http://52.2.5.122/api/v1/getmap.php

On Tue, Mar 29, 2016 at 6:41 PM, Steve Signell <steve@frontierspatial.com>
wrote:

> I may be able to get to this tomorrow am... I'll let you know
> On Mar 29, 2016 4:16 PM, "colinbeier" <notifications@github.com> wrote:
>
>> Given the circumstances, we're going to have to punt on this until after
>> official launch. I would like to have a release by tomorrow if possible,
>> Thursday at latest. If you guys disagree, let me know.
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/caryfitzhugh/NYCCSC-map-viewer/issues/168#issuecomment-203081676>
>>
>


-- 
Steve Signell
Frontier Spatial, L.L.C.
1062 Dean St.
Schenectady, NY 12309
518-232-1008
frontierspatial.com
steve@frontierspatial.com

**Comment by colinbeier** [comment]
Change modal title from "Sharing the Map" to "Saving and Sharing Maps" 

Replace the text with: 

You can save the current map view, including all active layers and settings, by requesting a save link below.  Bookmark the link to return to the map

Share this link with others and they will be able to load up the map directly in their web browser.

Thanks!
