### ISSUE TITLE
On the help/hints popup: When you click on one, there doesn’t seem to be a way to get back to  the list of hints. You have to close out and re-open the Help button

### ISSUE THREAD

**Issue by sasignell** [caryfitzhugh/NYCCSC-map-viewer#169]

**Comment by caryfitzhugh** [comment]
So - I'm not sure what this means.

If you open help, you get the "welcome!" page.

You can go left / right with the arrows.
And it seems to let you move around and you'll come back to the "welcome" page after clicking enough.

So - what was this bug describing? :(

**Comment by colinbeier** [comment]
Not a bug, just a 'web for dummies' thing i suppose.  Guess they missed the arrows.  Will point them out.  Can we add a little text link in the upper right of the modal that just says 'back to start'?

**Comment by caryfitzhugh** [comment]
Sure... Adding....
