### ISSUE TITLE
Sandy Surge layer – model for the legend

### ISSUE THREAD

**Issue by sasignell** [caryfitzhugh/NYCCSC-map-viewer#170]

**Comment by caryfitzhugh** [comment]
@sasignell @colinbeier this is all I could find:
http://services.femadata.com/arcgis/rest/services/2012_Sandy/SurgeBoundaries_Final_0214/MapServer/legend

We could add the "field verified Feb 14, 2013" to a tooltip, or the legend somewhere...

Is that what people want?

**Comment by caryfitzhugh** [comment]
@colinbeier Is all we want the little blurb of text here?

**Comment by colinbeier** [comment]
Can we monkey with the legend at all? It would help to add "(1m)" to the first category, so it reads "NYC Surge Area - Very High Resolution (1m)" and the second so it reads "NYC Surge Area - High Resolution (3m)" 

Or if we can split them up, then we could toggle between resolutions (1m, 3m), which may be preferable in terms of interpretation.   

Below the legend, add the text:  "Field verified Feb 2013"
