### ISSUE TITLE
Soils/surficial geology – this legend font is really fuzzy, is there anything we can do?

### ISSUE THREAD

**Issue by sasignell** [caryfitzhugh/NYCCSC-map-viewer#173]

**Comment by caryfitzhugh** [comment]
there has to be a way to fiddle the getLegend call.

there are somethign about styles.. have to read more.

**Comment by colinbeier** [comment]
the soil moisture legend is better, but when it toggles to surficial geology, that legend seems crammed into the same space, and is much smaller and illegible.
