### ISSUE TITLE
Rare plants layer, map shows white but nothing on the legend.  Not sure how to interprate, can  you check the legend on this layer.

### ISSUE THREAD

**Issue by sasignell** [caryfitzhugh/NYCCSC-map-viewer#174]

**Comment by caryfitzhugh** [comment]
I have checked the legend... We are asking esri to give transparent , but it seems it is giving us white as the background color? :(

![image](https://cloud.githubusercontent.com/assets/445848/13968429/0eda8b74-f053-11e5-8e6f-2ef12dc64d51.png)

Their viewer does the same thing, and does not indicate that white == 0 in the legend.

@colinbeier I could add a "white" = 0 or something.. ?

**Comment by colinbeier** [comment]
Sure, that sounds good

Colin Beier
SUNY ESF

On Mar 22, 2016 5:25 PM, Cary FitzHugh <notifications@github.com> wrote:

I have checked the legend... We are asking esri to give transparent , but it seems it is giving us white as the background color? :(

[image]<https://cloud.githubusercontent.com/assets/445848/13968429/0eda8b74-f053-11e5-8e6f-2ef12dc64d51.png>

Their viewer does the same thing, and does not indicate that white == 0 in the legend.

@colinbeier<https://github.com/colinbeier> I could add a "white" = 0 or something.. ?

**Comment by colinbeier** [comment]
is there any way we could get our legend to look like this one on the ESRI page?  instead of the weird color blocks we have now?

**Comment by caryfitzhugh** [comment]
Which part of ours is weird? It's the same squares and same text, the only
real difference being that theirs is vertical, and has a bit less spacing..
I can make it vertical, it just takes up more space.

**Comment by colinbeier** [comment]
Vertical is a lot more intuitive, if you can change it up, that should help a lot.

**Comment by caryfitzhugh** [comment]
I made it vertical.
I didn't add the white to the bottom - it was pretty tricky to - and the esri page has white (but their legend still says Low : 0 in front of the pinkish stuff.
