### ISSUE TITLE
DEC water body classification map – title needs to specify that it is DEC’s list.  Can we add the  Army Corps wetlands map?

### ISSUE THREAD

**Issue by sasignell** [caryfitzhugh/NYCCSC-map-viewer#176]

**Comment by caryfitzhugh** [comment]
@colinbeier @sasignell The layers are watercls_line and watercls_poly... And they should have the name "DEC" prepended to them?

Where is the army corps of engineers wetlands map? A google search turned up very little.

**Comment by colinbeier** [comment]
Yes the layer name and description should include NYS DEC.  

I have no idea about the Army Corps map... in general they don't make GIS data available without jumping thru a bunch of hoops.  We already have DEC regulatory wetlands in the map - I will remind them of this.
