### ISSUE TITLE
GAP – another fuzzy legend

### ISSUE THREAD

**Issue by sasignell** [caryfitzhugh/NYCCSC-map-viewer#178]

**Comment by sasignell** [comment]
Not too much we can do I'm afraid.  Its pulling the legend directly from the[ WMS source](
https://d2mdm1yqt1xmc6.cloudfront.net/arcgis/services/gap/GAP_Land_Cover_NVC_Formation_Landuse/MapServer/WmsServer?TRANSPARENT=TRUE&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetLegendGraphic&EXCEPTIONS=application%2Fvnd.ogc.se_xml&LAYER=0&FORMAT=image/gif&SCALE=554678930); with such a large legend, it just doesn't fit well into the space alotted.

**Comment by caryfitzhugh** [comment]
This legend stinks.  I tried to pass all sorts of parameters to it, to change it's format (as the docs say you can). and nothing took. Couldn't even change the font color.

I suspect they are caching, or something tricky - because it shouldn't ignore me like this.  :(
I could not do much with this legend.

**Comment by caryfitzhugh** [comment]
I looked on their map viewer page. and it appears that they hard-coded the colors in for each type.
I guess we could do that too... It would take...15 mins to color-dropper each legend and type it in... I guess I could do that....  

Just means that if the data changes, the legend is fubar'd... 

@colinbeier should I go for it?

**Comment by sasignell** [comment]
I don't think we should go down that road-- given that we control only a
small fraction of the data sets on the map, we (aka NYSERDA) should accept
that not everything will look absolutely uniform and perfect.  We are
providing an important service by bringing all these datasets together, and
in some ways trying to gloss over that fact is counterproductive.

On Tue, Mar 22, 2016 at 12:08 PM, Cary FitzHugh <notifications@github.com>
wrote:

> I looked on their map viewer page. and it appears that they hard-coded the
> colors in for each type.
> I guess we could do that too... It would take...15 mins to color-dropper
> each legend and type it in... I guess I could do that....
>
> Just means that if the data changes, the legend is fubar'd...
>
> @colinbeier <https://github.com/colinbeier> should I go for it?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/caryfitzhugh/NYCCSC-map-viewer/issues/178#issuecomment-199884107>
>



-- 
Steve Signell
Frontier Spatial, L.L.C.
1062 Dean St.
Schenectady, NY 12309
518-232-1008
frontierspatial.com
steve@frontierspatial.com

**Comment by colinbeier** [comment]
its not that fuzzy, it is just very small. could we scale it up by 25% to fill the sidebar?

**Comment by caryfitzhugh** [comment]
we can try that... I'll try that for all the getLegend calls.

**Comment by caryfitzhugh** [comment]
I expanded this one out to 100%...

**Comment by colinbeier** [comment]
Looks good, it is a little fuzzy but a lot more legible.  Should we do this for all of the land cover layers? these tend to have a lot of categories with subtle differences among colors.

**Comment by caryfitzhugh** [comment]
I can do it for them.
