### ISSUE TITLE
Data descriptions - lots of edits

### ISSUE THREAD

**Issue by colinbeier** [caryfitzhugh/NYCCSC-map-viewer#189]
Sorry, now realizing that quite a few of the data descriptions could be improved / edited.  

Can you send me or share here the relevant fields in the PgSQL table, so I can directly edit the information that appears for each layer in the modal?  Then I can send back the updated info to push back into the database?  I have a backlog of Ingrid's changes to make, and some of my own.  

Again sorry I should have done this before the release, but I figure these should be easy changes.

**Comment by caryfitzhugh** [comment]
hey colin,

if you go here:
https://github.com/caryfitzhugh/NYCCSC-map-viewer/blob/master/src/js/LayerInfo.js

And click on the pencil (edit).

You can make changes directyl to the files.

Once done, let me know and I can re-release / deploy to gh-pages, etc.

**Comment by caryfitzhugh** [comment]
LayerInfo starts on line 125
https://github.com/caryfitzhugh/NYCCSC-map-viewer/blob/master/src/js/LayerInfo.js#L125

**Comment by colinbeier** [comment]
Once I'm done editing, OK to commit changes?

**Comment by caryfitzhugh** [comment]
yeah - just commit.. I'll pull and deploy to gh-pages when you are done.

**Comment by colinbeier** [comment]
Done.  Thanks!

**Comment by caryfitzhugh** [comment]
hey colin, you have a funky part for "soils" layer.
There are two urls it would seem for the source_url.

catalog.data.gov
and
sdmdataaccess.nrcs.usda.gov

Whcih one did you want in the source_url?

Should I put the other one into the description?

**Comment by colinbeier** [comment]
Oops, uh, delete the second one.  I struggled with this one because the description just addresses topographic moisture, not geology.  could not find a description of the surficial geology layer specific to what we're bringing in, when Steve gets back I will ask him to help track it down.

**Comment by colinbeier** [comment]
Ooops, it looks like I edited the Climate Divisions title instead of the description.  I just revised again and committed the change.  Sorry!

**Comment by caryfitzhugh** [comment]
no worries. I'll update.

**Comment by colinbeier** [comment]
and just found another one, Municipalities.  fixed it and committed.  dang!

**Comment by caryfitzhugh** [comment]
https://i.imgflip.com/11qcv7.jpg

**Comment by colinbeier** [comment]
apparently not.  http://i.imgur.com/xIEfhc4.gifv
