### ISSUE TITLE
Convert GeoJSON to WMS layers

### ISSUE THREAD

**Issue by sasignell** [caryfitzhugh/NYCCSC-map-viewer#19]
This will simplify the code and make several things easier, such as getInfo requests & layer ordering

**Comment by caryfitzhugh** [comment]
what's the status on this one?

**Comment by caryfitzhugh** [comment]
moving to sprint 2.

**Comment by sasignell** [comment]
I think we need to get the wms getfeatureinfo working before we phase these out, if we actually end up doing this.  It might be useful to leave a couple in... lets discuss with Colin

**Comment by caryfitzhugh** [comment]
okies. I'll shoot an email.  Or do you want to?  This task is for this sprint, so we're on the hook to do it. If we don't think we can / should do it this sprint, we can push it to next.

**Comment by sasignell** [comment]
I vote to push it to the next one.  We will lose the popups and clustering
if we move it now, with no replacement.

On Mon, Oct 12, 2015 at 11:28 AM, Cary FitzHugh <notifications@github.com>
wrote:

> okies. I'll shoot an email. Or do you want to? This task is for this
> sprint, so we're on the hook to do it. If we don't think we can / should do
> it this sprint, we can push it to next.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/caryfitzhugh/NYCCSC-map-viewer/issues/19#issuecomment-147437346>
> .
>



-- 
Steve Signell
Frontier Spatial, L.L.C.
1062 Dean St.
Schenectady, NY 12309
518-232-1008
frontierspatial.com
steve@frontierspatial.com

**Comment by caryfitzhugh** [comment]
ok. we'll move it forward.

**Comment by caryfitzhugh** [comment]
Status is that we're moving to change all layers to either:
WMS, ESRI dynamicMap, or GeoJSON Markers.

Only historicdeclarations is currently "bad"
https://docs.google.com/spreadsheets/d/1ccOnzPRkqRExZMlCzRvcq-5HNdwC69xHlzYXVZUMr_M/edit#gid=0

**Comment by caryfitzhugh** [comment]
Leaving this as "open". HistoricDeclaratinos is still geoJSON and a "bad" citizen.
Moving to psrint 4

**Comment by caryfitzhugh** [comment]
done - fema emergencies are now WMS.
