### ISSUE TITLE
NARCCAP is down on gh pages

### ISSUE THREAD

**Issue by colinbeier** [caryfitzhugh/NYCCSC-map-viewer#190]
Both temp and precip.  Was working before latest release.

**Comment by caryfitzhugh** [comment]
I am looking at it, but not totally sure what is going on.
When I disable cache on my browser it seems to work.

One time when I was using http:  instead of https it failed too...

**Comment by colinbeier** [comment]
Cleared my cache and it works now.  

But the legends lost their precision somehow - are integers but should be one decimal point.  I noticed also that the invasive plants data still have decimal points, but should be integers.  Maybe got the two switched in making edits?

**Comment by caryfitzhugh** [comment]
No idea - but I'm looking at that part of the code to remove a warning
anyway, so I'll look...

**Comment by caryfitzhugh** [comment]
pushed a fix and gh-pages has it.
significant digits.

and the cache clearing solved the others.
