### ISSUE TITLE
SoVI has mad errors

### ISSUE THREAD

**Issue by colinbeier** [caryfitzhugh/NYCCSC-map-viewer#191]
its "i" indicator yellow instead of red, draws partially, but shows 40+ errors.

**Comment by caryfitzhugh** [comment]
looking...  taking the CDN out of the equation, and hitting their server
directly, indicates something is wrong with their server (AFAICT).
Almost as if their server is down.  And timing out the requests.

**Comment by colinbeier** [comment]
works fine now. closing.
