### ISSUE TITLE
NARCCAP temp and precip are down

### ISSUE THREAD

**Issue by colinbeier** [caryfitzhugh/NYCCSC-map-viewer#193]
works fine on gh page, error on climate.dev

**Comment by caryfitzhugh** [comment]
It seems like the first request fails, but all others after that work.
hrm...  Wonder what the issue is with that. All these layers are probably the same issue.

**Comment by colinbeier** [comment]
it seems like there are always new issues whenever we put a new release up on climate-dev.  i wonder if its just a coincidence.

**Comment by caryfitzhugh** [comment]
it's just that the CDN is having an issue...  I'm not sure yet what is going on. but - it seems like once things get "spun up" - things work...

**Comment by colinbeier** [comment]
hmm. i reloaded the map today and there were still errors.  how do things get spun up?  just curious.

**Comment by caryfitzhugh** [comment]
well, your stuff may be cached as well.
I'm poking about... sigh.  we'll see...
