### ISSUE TITLE
Water Wells is down

### ISSUE THREAD

**Issue by colinbeier** [caryfitzhugh/NYCCSC-map-viewer#198]
on climate-dev, works fine on gh page

**Comment by caryfitzhugh** [comment]
i just tried this on gh-pages, gh-pages-integration, and climate-dev and it works.
I have my settings on "disable cache".

Is this somewhat an artifact of us devleoping the code (and testing it on testing sites).
Do "normal" users run into this?

**Comment by colinbeier** [comment]
two things:

1. crashed Chrome trying to load this one, it worked second time.  this looks like json?  i am thinking we move it to WMS with GFI enabled to avoid this.  
2. number of features in legend does not change with map view, stays at 19918 no matter how many features are being shown.

**Comment by caryfitzhugh** [comment]
@sasignell - yes let's move this to WMS -- can you do that quickly?

**Comment by sasignell** [comment]
yeah let me bust it out.

On Thu, Apr 7, 2016 at 3:50 PM, Cary FitzHugh <notifications@github.com>
wrote:

> @sasignell - yes let's move this to WMS -- can you do that quickly?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/caryfitzhugh/NYCCSC-map-viewer/issues/198#issuecomment-207064637>
>



-- 
Steve Signell
Frontier Spatial, L.L.C.
1062 Dean St.
Schenectady, NY 12309
518-232-1008
frontierspatial.com
steve@frontierspatial.com

**Comment by sasignell** [comment]
OK Moved it over to WMS and pushed.    The red squares when zoomed out are
an artifact of the CDN before I changed the style to blue circles.  Should
clear up soon

On Thu, Apr 7, 2016 at 3:53 PM, Steve Signell <steve@frontierspatial.com>
wrote:

> yeah let me bust it out.
>
> On Thu, Apr 7, 2016 at 3:50 PM, Cary FitzHugh <notifications@github.com>
> wrote:
>
>> @sasignell - yes let's move this to WMS -- can you do that quickly?
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/caryfitzhugh/NYCCSC-map-viewer/issues/198#issuecomment-207064637>
>>
>
>
>
> --
> Steve Signell
> Frontier Spatial, L.L.C.
> 1062 Dean St.
> Schenectady, NY 12309
> 518-232-1008
> frontierspatial.com
> steve@frontierspatial.com
>



-- 
Steve Signell
Frontier Spatial, L.L.C.
1062 Dean St.
Schenectady, NY 12309
518-232-1008
frontierspatial.com
steve@frontierspatial.com

**Comment by caryfitzhugh** [comment]
Sweet

I shall tidy up tmw morning and off we go

Thanks Steve

**Comment by caryfitzhugh** [comment]
looks good. closing.
