### ISSUE TITLE
Change Endpoint for Columbia NYSERDA Flood

### ISSUE THREAD

**Issue by caryfitzhugh** [caryfitzhugh/NYCCSC-map-viewer#199]
) Are you requesting the data as WMS or WMTS?  We have cache-on-demand enabled, so if you make the request via cached WMS it might load slow the first time for the first user, but afterwards it will be much faster when the PNG files are built and stored on our servers.  Here is an example cached WMS request: 

http://ciesin.columbia.edu/geoserver/gwc/service/wms?LAYERS=nyserda%3Aflood_00_1000&FORMAT=image%2Fpng&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&STYLES=&SRS=EPSG%3A4326&BBOX=-74.098020640929,41.523425978201,-73.88450858577,41.73693803336&WIDTH=256&HEIGHT=256

Notice the request is the same as for regular wms except the root URL changes from http://ciesin.columbia.edu/geoserver/wms? to http://ciesin.columbia.edu/geoserver/gwc/service/wms?

**Comment by colinbeier** [comment]
did we resolve the slow loading issue here?  just noticed that the GFI call is not returning anything.  which is OK, just will want to remove the map locator icon for now.

**Comment by caryfitzhugh** [comment]
Nothing speed-wise was fixed on our end.  The initial call is just slow.
They suggested caching it with their alternative URL.  We are doing that
now, but -- we already cached with Cloudfront, so  -- you don't see much
improvement.  Can remove the map locator...

Reopens #199

**Comment by caryfitzhugh** [comment]
Reopen #199
Opens #199
