### ISSUE TITLE
map live on www.nyclimatescience.org... CDN ERRORS!

### ISSUE THREAD

**Issue by colinbeier** [caryfitzhugh/NYCCSC-map-viewer#201]
Production site is live on nyclimatescience.org now... 

Looks like maybe the CDN 'bugs' are back.  

Following layers are down (red errors):

NARCCAP precip and temp
PRISM precip and temp
Invasive Animal Species
Invasive Insect Species
Invasive Plant Species

Everything else looks good.  Seems to run pretty quickly.

**Comment by colinbeier** [comment]
Well, actually, these might just be down for me in Chrome due to cache issues.  They work fine in Safari.  

hmmm...

**Comment by caryfitzhugh** [comment]
I'm hoping...

**Comment by caryfitzhugh** [comment]
I just pulled it up in an incognito browser window, and climaid came up...
I think it's just your cache?

**Comment by colinbeier** [comment]
Probably.  But if found something else...
