### ISSUE TITLE
Map sharing / request link just spins

### ISSUE THREAD

**Issue by colinbeier** [caryfitzhugh/NYCCSC-map-viewer#202]
this is on nyclimatescience.org site, both in Chrome and Safari. 

i'm guessing it has something to do with the weird double URLs that Cornell is using?

**Comment by caryfitzhugh** [comment]
NOpe - it's because we put the server behind http for that.  guh.  That
might be an easy fix...

**Comment by caryfitzhugh** [comment]
We had the getmap behind the CDN / https, but not our savemap.

**Comment by colinbeier** [comment]
looks like it is working again on gh page
