### ISSUE TITLE
d3 legends for PRISM, NARCCAP not dynamic

### ISSUE THREAD

**Issue by colinbeier** [caryfitzhugh/NYCCSC-map-viewer#203]
the legends / color bar values are not changing as you change months, boundaries, etc. for PRISM or NARCCAP. 

CLIMAID seems to be working fine.

**Comment by colinbeier** [comment]
also noticed here that we lost the decimal point on the PRISM and NARCCAP legends.  and they are moving quite slow all of a sudden.

**Comment by caryfitzhugh** [comment]
ok. I'll look at that in a moment.  I'm seeing on the server that it has no
space left. yet the "df" call says we've still got like 13GB..... hrm...

**Comment by caryfitzhugh** [comment]
maybe that just resolved itself... hrm.

**Comment by sasignell** [comment]
I just deleted a pg dump I had on there so should be good there


On Fri, May 6, 2016 at 9:50 AM, Cary FitzHugh <notifications@github.com>
wrote:

> ok. I'll look at that in a moment. I'm seeing on the server that it has no
> space left. yet the "df" call says we've still got like 13GB..... hrm...
>
> On Fri, May 6, 2016 at 9:48 AM, colinbeier <notifications@github.com>
> wrote:
>
> > also noticed here that we lost the decimal point on the PRISM and NARCCAP
> > legends. and they are moving quite slow all of a sudden.
> >
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/caryfitzhugh/NYCCSC-map-viewer/issues/203#issuecomment-217445045
> >
>
> >
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/caryfitzhugh/NYCCSC-map-viewer/issues/203#issuecomment-217445563>
>



-- 
Steve Signell
Frontier Spatial, L.L.C.
1062 Dean St.
Schenectady, NY 12309
518-232-1008
frontierspatial.com
steve@frontierspatial.com

**Comment by caryfitzhugh** [comment]
I cleared the CDN for that one - and the CDN wasn't accepting POSTs
(didn't see that because we never tried to test the savemap on an https
page).
It should work shortly.

**Comment by caryfitzhugh** [comment]
Looking at the legends now..

**Comment by caryfitzhugh** [comment]
on gh-pages

**Comment by colinbeier** [comment]
yep legends are dynamic again in gh page.  but only showing integers instead of one floating point. 

also the legend numerals seem a tiny bit cut off on the bottom in Safari.  not critical just weird.
