### ISSUE TITLE
bug: share link, via FB, opens new map with no layers in catalog

### ISSUE THREAD

**Issue by colinbeier** [caryfitzhugh/NYCCSC-map-viewer#204]
So i created a share link just with the invasive plants layer up. 

https://www.nyclimatescience.org/map/map_viewer.html?available-layers=&active-layers=&map_state_token=bf470e3762fca868493c83d086013a0d

When I paste the url into my browser it works great.  

Then I shared it via Facebook.  When you open up the FB link

https://l.facebook.com/l.php?u=https%3A%2F%2Fwww.nyclimatescience.org%2Fmap%2Fmap_viewer.html%3Favailable-layers%26active-layers%26map_state_token%3Dbf470e3762fca868493c83d086013a0d&h=fAQEnXsws
 
the layer loads up but nothing shows up in the Layers tab (catalog). i tried it again with an incognito window and did the same.  

i noticed that when i hit the FB hyperlink the address I end up with is missing a '=' in the url in two places 

available-layers&active-layers&map_state_token=bf470e3762fca868493c83d086013a0d

should be: 

available-layers=&active-layers=&map_state_token=bf470e3762fca868493c83d086013a0d 

something with the API?  it's weird.  could become an issue if the map links start being share via FB.

**Comment by caryfitzhugh** [comment]
not sure. should be easy to fix. Have to check it out.

**Comment by caryfitzhugh** [comment]
@colinbeier want me to look into this at all? or just close this?

**Comment by colinbeier** [comment]
Nah, let's close it

Colin Beier
SUNY ESF

On Aug 1, 2016 10:04 PM, Cary FitzHugh <notifications@github.com> wrote:

@colinbeier<https://github.com/colinbeier> want me to look into this at all? or just close this?

**Comment by caryfitzhugh** [comment]
ok! thus says colin.  closed.
