### ISSUE TITLE
layer order issue from Amanda

### ISSUE THREAD

**Issue by colinbeier** [caryfitzhugh/NYCCSC-map-viewer#206]
***I tried to replicate this problem in the production site but everything worked fine... so this is maybe just a placeholder***

Just wanted to let you know that when overlaying layers in the mapper, the climate projection layers always seem to appear on top, no matter how you move layers around in the map control tab (e.g., when to display designated trout streams on top of the NARCCAP temp projections layer). Not sure why that is, but a user should be able to move those to the bottom, if they want.
 
--Amanda

**Comment by caryfitzhugh** [comment]
Yeah - we'll need a reproduction case if we can't reproduce it.  Any number
of things could be borked?
