### ISSUE TITLE
GetFeatureInfo

### ISSUE THREAD

**Issue by sasignell** [caryfitzhugh/NYCCSC-map-viewer#22]

**Comment by caryfitzhugh** [comment]
Create a modal.
When a user clicks the map, we get it's location, we look at it's lat/lng.
We make a call for any "WMS-type" layers (active / not opacity 0) - and then the response,
we put into the modal.

? html as an iframe?

* AADT
* Railroads
* Streams
* boundary layers
* slr_vuln
* sovi
* nlcd

**Comment by caryfitzhugh** [comment]
@sasignell ok, so I put up some code.

It works for aadt

boundary layers give me back bad info (cannot find ...)

And the public WMS layers don't seem to like my requests.

We can fiddle some more but hopefully I'll have these done by the end of the day tmw.

**Comment by caryfitzhugh** [comment]
I pushed and deployed to gh-pages.
