### ISSUE TITLE
Layers not respecting ordering / opacity

### ISSUE THREAD

**Issue by caryfitzhugh** [caryfitzhugh/NYCCSC-map-viewer#28]
This is weird - and should be looked at.

Can we make the layers respect ordering? 

If not - should we group layers in the showing tab?

TBD. important.

**Comment by sasignell** [comment]
We can do this, but it is one of leaflet's weak areas.  We'll be able to
work it out though

**Comment by caryfitzhugh** [comment]
Maybe we have to group "markers" at the top.
We'll figure it out....

**Comment by caryfitzhugh** [comment]
by putting the boundary on the top - clicks do not get triggered on any layers.

Need getFeatureInfo and clicks on geoJSON (somehow) to handle it.

**Comment by caryfitzhugh** [comment]
The ordering is respected now.  Clicks may get consumed by an over-eager top layer though.  That's not good.

**Comment by sasignell** [comment]
I think we can turn off clicks in leaflet... Will look at this later today

**Comment by caryfitzhugh** [comment]
I tried to look at it, and now I can't replicate the issue... so maybe it's not an issue?

**Comment by caryfitzhugh** [comment]
Closing, b/c I can't reproduce the issue I was seeing....
