### ISSUE TITLE
Remove logo from the iframe top left.

### ISSUE THREAD

**Issue by caryfitzhugh** [caryfitzhugh/NYCCSC-map-viewer#39]
This should be removed.  
Talk with Lisa, I guess.
Link to help. Something. ? we'll figure it out.

**Comment by colinbeier** [comment]
I would like to try out a graphic that says 'Maps & GIS' so we have some kind of logo / identity for the viewer.  I'll play around with some alternatives...

**Comment by caryfitzhugh** [comment]
ok, sounds good.

**Comment by sasignell** [comment]
How about including logo options as in the api, e.g. logo=false or logo=nyccsc, etc.

**Comment by caryfitzhugh** [comment]
Colin said he was going to give me something. I'd rather not make an API
change (it just involves so many ppl, etc... ugh).
We could queue this up for later?  If Colin has a logo he wants, we can use
that. Or maybe we just remove it for now?
I'm really pushing back, simply because I think we need to focus on getting
the important things done, and this seems to fall outside that category.
If colin has a logo he wants instead, we can drop that in, or just hide
it.  If we want to add it tinot the API later, then we could scheduled that
task for later?

THoughts?

**Comment by sasignell** [comment]
I say lets just drop it for now.

On Thu, Oct 22, 2015 at 10:42 AM, Cary FitzHugh <notifications@github.com>
wrote:

> Colin said he was going to give me something. I'd rather not make an API
> change (it just involves so many ppl, etc... ugh).
> We could queue this up for later? If Colin has a logo he wants, we can use
> that. Or maybe we just remove it for now?
> I'm really pushing back, simply because I think we need to focus on getting
> the important things done, and this seems to fall outside that category.
> If colin has a logo he wants instead, we can drop that in, or just hide
> it. If we want to add it tinot the API later, then we could scheduled that
> task for later?
>
> THoughts?
>
> On Thu, Oct 22, 2015 at 8:34 AM, Steve Signell <notifications@github.com>
> wrote:
>
> > How about including logo options as in the api, e.g. logo=false or
> > logo=nyccsc, etc.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/caryfitzhugh/NYCCSC-map-viewer/issues/39#issuecomment-150206614
> >
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/caryfitzhugh/NYCCSC-map-viewer/issues/39#issuecomment-150246429>
> .
>



-- 
Steve Signell
Frontier Spatial, L.L.C.
1062 Dean St.
Schenectady, NY 12309
518-232-1008
frontierspatial.com
steve@frontierspatial.com

**Comment by colinbeier** [comment]
Definitely NOT a priority... I will create a basic image / text / logo to go in that spot, but its not high on my to-do list this week...

**Comment by caryfitzhugh** [comment]
Removed for now in the clone-layers branch / PR.

**Comment by colinbeier** [comment]
Here are a few options in a single pdf, just for your review... obviously these need more formatting.  

Oops I cannot attach the pdf without write permission to the repo...

**Comment by caryfitzhugh** [comment]
I'll add you as a repo person... 1 sec.

**Comment by caryfitzhugh** [comment]
there you go

**Comment by colinbeier** [comment]
very simple, would need to buy the icons to use them and for full-res.  
[header drafts.pdf](https://github.com/caryfitzhugh/NYCCSC-map-viewer/files/21037/header.drafts.pdf)

**Comment by caryfitzhugh** [comment]
Do you just want me to do it in illustrator? That first logo isn't too
hard...

**Comment by colinbeier** [comment]
I'm not sure that would be the best use of your time, Cary!  I would have used Illustrator but I'm having all sorts of trouble with it lately...

**Comment by caryfitzhugh** [comment]
:) yeah, probably not. sounds good.
