### ISSUE TITLE
Folder heierarchy

### ISSUE THREAD

**Issue by sasignell** [caryfitzhugh/NYCCSC-map-viewer#42]
Right now the layers in the folders are not mutually exclusive (or even close).  Unless we are completely married to the 'sector' approach, I have a couple proposals:

1) just have a list of layers, and each layer has one or more small icons (e.g. wave-->coastal, silo-->agriculture, etc.) associated with it for each sector or other category (e.g. climate data).  The user can then quickly filter these using a drop down, as in our alpha map.

2) We divide layers up into virtually mutually exclusive groups of air, water (fresh/salt), land and society:
* air: mintemp, maxtemp (historic,future) pollution, weather layers, etc.
* (fresh)water: flood hazard, ppt, alsc, lake ice, etc.
* (salt)water: sea level rise, sandysurge, ocean temp (historic, future), coastal vulnerability,
* land: nlcd, agriculture layers, 
* society: railroads, aadt, subways, waste treatment plants, other infrastructure

**Comment by sasignell** [comment]
Sorry the formatting was screwy on that one.  The categories were Air,Water,Land,Society.  Maybe this is something we try out during testing, if at all.  It certainly would be simple to implement a different folder structure at that time.

**Comment by caryfitzhugh** [comment]
I'm going to close this since it really isn't actionable. It's more of a research task. 
I'm confident that organization of the layers will come up in the beta reviews, and we'll get some direction then.
