### ISSUE TITLE
Move CDN to Colin's account on AWS

### ISSUE THREAD

**Issue by caryfitzhugh** [caryfitzhugh/NYCCSC-map-viewer#45]
Should be off my personal account and on the SUNY account.

**Comment by colinbeier** [comment]
Basic (free) account is set up on AWS.  Do you guys want my login credentials or should we get you access to my account via your own credentials?

**Comment by caryfitzhugh** [comment]
We should set up IAM user accounts on that thing.  I think there is
probably a tutorial on it somewhere.
You want to set up some admin IAM credentials on the account.
http://docs.aws.amazon.com/IAM/latest/UserGuide/best-practices.html#create-iam-users

I could set things up if you wanted, but that involves sending your
credentials over the wire somehow.

**Comment by caryfitzhugh** [comment]
done! woot. Colin's account now has a number of them.
They don't cost any $$ to exist, just pay for bandwidth.  We fiddled the last few weeks and my total AWS bill for the CDN for NYCCSC was $0.12. So  - it's pretty cheap.

![aws cloudfront management console 2015-11-03 13-16-14](https://cloud.githubusercontent.com/assets/445848/10917649/dfbd0254-822f-11e5-995e-c2657e157577.png)
