### ISSUE TITLE
Beta layer: Soils

### ISSUE THREAD

**Issue by colinbeier** [caryfitzhugh/NYCCSC-map-viewer#51]
Content team is asking for a 'soils layers' - this could be lots of things.  Mainly are looking for soil moisture, but also have asked for other things that don't exist.  

I think Steve has looked into a few potential WMS options for soils data already.  

1. USDA NRCS Soils Data Mart offers access via WMS queries:
http://sdmdataaccess.nrcs.usda.gov/WebServiceHelp.aspx

Looks like a system only a fed agency could love, based on this manual:  
http://sdmdataaccess.nrcs.usda.gov/documents/SoilDataAccessQueryGuide.pdf
- see p. 15-16 for list of tables available for query
- need to identify all map units in NY State
- map unit components are sets of attributes for map units (i provide a brief list of those relevant for us) 
- we want to be sure to query SSURGO data, not STATSGO data; see p. 34

Hope access is easier than it may seem.  Steve -- I think -- also has some experience with SSURGO.  Lots of variables available for public read access, so I will try to narrow them down to help define the query.  We are mainly interested in soil moisture / drainage class, but erosion might also be useful. 

> Map units within NYS
>> Map unit components: >>coerosionacc Component Erosion Accelerated (likelihood of erosion based on texture, landscape position) >>corestrictions Component Restrictions (rooting depth limitations) >>cosoilmoist Component Soil Moisture (based on drainage classes)  >>cotaxmoistcl Component Taxonomic Moisture Class (also based on drainage) 

Actually its not clear if this source will provide the polygons as well as the tabular information, now that I read more carefully.  I just spent an hour trying to figure this out so I want to defer to Steve's experience in terms of SSURGO data.  I could not find anything quickly on the National Map but that definitely does not mean it isn't there.

**Comment by sasignell** [comment]
Added surficial lithology to ecosystems folder.  Is this good enough for a soils placeholder?

**Comment by colinbeier** [comment]
Any other vars?

Colin Beier
SUNY ESF

On Oct 27, 2015 8:22 AM, Steve Signell <notifications@github.com> wrote:

Added surficial lithology to ecosystems folder. Is this good enough for a soils placeholder?

**Comment by sasignell** [comment]
they have a moisture index:
[image: Inline image 1]

and a landforms:
[image: Inline image 2]

On Tue, Oct 27, 2015 at 9:00 AM, colinbeier <notifications@github.com>
wrote:

> Any other vars?
>
> Colin Beier
> SUNY ESF
>
> On Oct 27, 2015 8:22 AM, Steve Signell <notifications@github.com> wrote:
>
> Added surficial lithology to ecosystems folder. Is this good enough for a
> soils placeholder?
>
> —
> Reply to this email directly or view it on GitHub<
> https://github.com/caryfitzhugh/NYCCSC-map-viewer/issues/51#issuecomment-151473963
> >.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/caryfitzhugh/NYCCSC-map-viewer/issues/51#issuecomment-151487399>
> .
>



-- 
Steve Signell
Frontier Spatial, L.L.C.
1062 Dean St.
Schenectady, NY 12309
518-232-1008
frontierspatial.com
steve@frontierspatial.com

**Comment by colinbeier** [comment]
moisture index would be best.  if you can offer that plus lithology using a simple toggle, that would be awesome.  if that takes a while to set up, just moisture index would be great.

**Comment by sasignell** [comment]
topographic moisture and surface lith now in one ecosystem-->'soils...' layer

**Comment by caryfitzhugh** [comment]
I see this, I'll lcose this issue now.
