### ISSUE TITLE
Beta layer: Dams

### ISSUE THREAD

**Issue by colinbeier** [caryfitzhugh/NYCCSC-map-viewer#52]
Need layer on dams / impoundments that is comprehensive as possible. 

NYS DEC has this kmz available: 
http://www.dec.ny.gov/maps/nysdamslink.kmz

DEC data might not include any dams within NYC boundaries, which could fall under NYC DEP jurisdiction.

**Comment by sasignell** [comment]
Layer added from clearinghouse-->PostGIS-->Geoserver.  Popup emulates DEC kmz file; leaves a lot to be desired.

**Comment by colinbeier** [comment]
Looks good for beta.
