### ISSUE TITLE
Beta layer: Hospitals

### ISSUE THREAD

**Issue by colinbeier** [caryfitzhugh/NYCCSC-map-viewer#53]
This web map should have harvestable data.  Hospital names and geolocations should suffice.  

http://profiles.health.ny.gov/hospital/

It looks like there is a database behind the site which includes lists of services, etc. It might be useful to map hospitals with certain attributes, but until we are asked to do so, I would keep it simple.

**Comment by sasignell** [comment]
Hospitals are included in Coastal Zones-->'HAZUS Critical Facilities' layer.. is this satisfactory?

**Comment by colinbeier** [comment]
I think that layer only includes hospitals within the coastal zone, does not include inland facilities... but we could check the map.

**Comment by sasignell** [comment]
added hospitals layer from geojson

**Comment by colinbeier** [comment]
Looks good to me.
