### ISSUE TITLE
Beta layer: Air Quality Monitoring Stations

### ISSUE THREAD

**Issue by colinbeier** [caryfitzhugh/NYCCSC-map-viewer#54]
https://gis.ny.gov/gisdata/fileserver/?DSID=1159&file=AirMonStations.zip

Lisa made some other suggestions, which I attempted to track down without luck, so this should serve as a placeholder for beta.

**Comment by sasignell** [comment]
Added  this as geojson in 'Climat Data' folder

**Comment by colinbeier** [comment]
Can you please move this to Public Health folder?  Thanks

**Comment by sasignell** [comment]
I'll get back to this later tonight or tomorrow

On Tue, Oct 27, 2015 at 9:37 AM, colinbeier <notifications@github.com>
wrote:

> Can you please move this to Public Health folder? Thanks
>
> On Oct 27, 2015, at 12:48 AM, Steve Signell wrote:
>
> > Added this as geojson in 'Climat Data' folder
>
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/caryfitzhugh/NYCCSC-map-viewer/issues/54#issuecomment-151498994>
> .
>



-- 
Steve Signell
Frontier Spatial, L.L.C.
1062 Dean St.
Schenectady, NY 12309
518-232-1008
frontierspatial.com
steve@frontierspatial.com

**Comment by colinbeier** [comment]
Sorry guys... have to reopen.  Lisa realized (finally) that the dataset here is just the stations, not the air quality data itself.  I've been telling her and the Content Team for months that this wasn't useful, they kept this link in there, so we brought it in.  

Getting real-time air quality data into the map is definitely POST-BETA.  But it might be achievable in the same way (at least in the UI) that we are doing the USGS gauges.  

Steve, when you have a chance, can you check this out:

http://www.dec.ny.gov/airmon/index.php

Someone built this site for DEC using Javascript.  The interface leads you to select station by station, or multiple stations by DEC region.  If there is a way to harvest the real-time data from this site, we might compile it together into a statewide map layer.  Again, not for beta, but maybe down the line.  We can give Lisa a sense of how long it will take to pull it together, and she can decide if its enough of a priority.

**Comment by sasignell** [comment]
I don't see an easy way to link to these, as they are using a set of UIDs that are not in our table.  We could set up a crosswalk... there aren't many stations.  Then we could have a link in the popup.

**Comment by colinbeier** [comment]
Agree.  A crosswalk might be feasible given the number of stations.  Would we be able to set something up to bring in the real-time data / forecast for each station, kind of like the USGS gauges?

**Comment by sasignell** [comment]
Yes, very similar to the stream gages.  Is this a priority for beta? I can
crank it out pretty quick

On Wed, Nov 4, 2015 at 8:22 AM, colinbeier <notifications@github.com> wrote:

> Agree. A crosswalk might be feasible given the number of stations. Would
> we be able to set something up to bring in the real-time data / forecast
> for each station, kind of like the USGS gauges?
>
> On Nov 4, 2015, at 8:19 AM, Steve Signell wrote:
>
> > I don't see an easy way to link to these, as they are using a set of
> UIDs that are not in our table. We could set up a crosswalk... there aren't
> many stations. Then we could have a link in the popup.
>
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/caryfitzhugh/NYCCSC-map-viewer/issues/54#issuecomment-153717883>
> .
>



-- 
Steve Signell
Frontier Spatial, L.L.C.
1062 Dean St.
Schenectady, NY 12309
518-232-1008
frontierspatial.com
steve@frontierspatial.com

**Comment by colinbeier** [comment]
It would be awesome if you could get this into one of the current Sprints (4 or 5)... that would make Lisa VERY HAPPY :)

**Comment by sasignell** [comment]
Only 43 of the 67 stations have links on the DEC site.... should we show
them all, or just the ones that can be linked?


On Wed, Nov 4, 2015 at 8:28 AM, colinbeier <notifications@github.com> wrote:

> It would be awesome if you could get this into one of the current Sprints
> (4 or 5)... that would make Lisa VERY HAPPY :)
>
> On Nov 4, 2015, at 8:24 AM, Steve Signell wrote:
>
> > Yes, very similar to the stream gages. Is this a priority for beta? I can
> > crank it out pretty quick
> >
> > On Wed, Nov 4, 2015 at 8:22 AM, colinbeier <notifications@github.com>
> wrote:
> >
> > > Agree. A crosswalk might be feasible given the number of stations.
> Would
> > > we be able to set something up to bring in the real-time data /
> forecast
> > > for each station, kind of like the USGS gauges?
> > >
> > > On Nov 4, 2015, at 8:19 AM, Steve Signell wrote:
> > >
> > > > I don't see an easy way to link to these, as they are using a set of
> > > UIDs that are not in our table. We could set up a crosswalk... there
> aren't
> > > many stations. Then we could have a link in the popup.
> > >
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub.
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> https://github.com/caryfitzhugh/NYCCSC-map-viewer/issues/54#issuecomment-153717883
> >
> > > .
> > >
> >
> >
> >
> > --
> > Steve Signell
> > Frontier Spatial, L.L.C.
> > 1062 Dean St.
> > Schenectady, NY 12309
> > 518-232-1008
> > frontierspatial.com
> > steve@frontierspatial.com
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/caryfitzhugh/NYCCSC-map-viewer/issues/54#issuecomment-153719217>
> .
>



-- 
Steve Signell
Frontier Spatial, L.L.C.
1062 Dean St.
Schenectady, NY 12309
518-232-1008
frontierspatial.com
steve@frontierspatial.com

**Comment by colinbeier** [comment]
Just those that can be linked... 

Lisa said the locations of the stations themselves were useless without the data (which is what I'd been saying for months, it took her actually seeing the map to realize)

**Comment by sasignell** [comment]
Ok I didn't see that response until I had already brought them all in, with
links on the sites that have them-- check it out.  I can take out the ones
that don't have links if you still want.

On Wed, Nov 4, 2015 at 8:54 AM, colinbeier <notifications@github.com> wrote:

> Just those that can be linked...
>
> Lisa said the locations of the stations themselves were useless without
> the data (which is what I'd been saying for months, it took her actually
> seeing the map to realize)
>
> On Nov 4, 2015, at 8:51 AM, Steve Signell wrote:
>
> > Only 43 of the 67 stations have links on the DEC site.... should we show
> > them all, or just the ones that can be linked?
> >
> >
> > On Wed, Nov 4, 2015 at 8:28 AM, colinbeier <notifications@github.com>
> wrote:
> >
> > > It would be awesome if you could get this into one of the current
> Sprints
> > > (4 or 5)... that would make Lisa VERY HAPPY :)
> > >
> > > On Nov 4, 2015, at 8:24 AM, Steve Signell wrote:
> > >
> > > > Yes, very similar to the stream gages. Is this a priority for beta?
> I can
> > > > crank it out pretty quick
> > > >
> > > > On Wed, Nov 4, 2015 at 8:22 AM, colinbeier <notifications@github.com
> >
> > > wrote:
> > > >
> > > > > Agree. A crosswalk might be feasible given the number of stations.
> > > Would
> > > > > we be able to set something up to bring in the real-time data /
> > > forecast
> > > > > for each station, kind of like the USGS gauges?
> > > > >
> > > > > On Nov 4, 2015, at 8:19 AM, Steve Signell wrote:
> > > > >
> > > > > > I don't see an easy way to link to these, as they are using a
> set of
> > > > > UIDs that are not in our table. We could set up a crosswalk...
> there
> > > aren't
> > > > > many stations. Then we could have a link in the popup.
> > > > >
> > > > > >
> > > > > > —
> > > > > > Reply to this email directly or view it on GitHub.
> > > > > >
> > > > >
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > > <
> > >
> https://github.com/caryfitzhugh/NYCCSC-map-viewer/issues/54#issuecomment-153717883
> > > >
> > > > > .
> > > > >
> > > >
> > > >
> > > >
> > > > --
> > > > Steve Signell
> > > > Frontier Spatial, L.L.C.
> > > > 1062 Dean St.
> > > > Schenectady, NY 12309
> > > > 518-232-1008
> > > > frontierspatial.com
> > > > steve@frontierspatial.com
> > > > —
> > > > Reply to this email directly or view it on GitHub.
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> https://github.com/caryfitzhugh/NYCCSC-map-viewer/issues/54#issuecomment-153719217
> >
> > > .
> > >
> >
> >
> >
> > --
> > Steve Signell
> > Frontier Spatial, L.L.C.
> > 1062 Dean St.
> > Schenectady, NY 12309
> > 518-232-1008
> > frontierspatial.com
> > steve@frontierspatial.com
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/caryfitzhugh/NYCCSC-map-viewer/issues/54#issuecomment-153725091>
> .
>



-- 
Steve Signell
Frontier Spatial, L.L.C.
1062 Dean St.
Schenectady, NY 12309
518-232-1008
frontierspatial.com
steve@frontierspatial.com

**Comment by colinbeier** [comment]
Dang homie you fast... i wrote you back in 3 minutes.  

Links work great ... is there any chance their little status graphic (below) could be dropped into the popup on the map?  That would be totally sweet.  


AQI 10	
Good
O3	0.018 ppm

**Comment by sasignell** [comment]
check it

On Wed, Nov 4, 2015 at 9:13 AM, colinbeier <notifications@github.com> wrote:

> Dang homie you fast... i wrote you back in 3 minutes.
>
> Links work great ... is there any chance their little status graphic
> (below) could be dropped into the popup on the map? That would be totally
> sweet.
>
>
> AQI 10
> Good
> O3 0.018 ppm
>
> On Nov 4, 2015, at 9:07 AM, Steve Signell wrote:
>
> > Ok I didn't see that response until I had already brought them all in,
> with
> > links on the sites that have them-- check it out. I can take out the ones
> > that don't have links if you still want.
> >
> > On Wed, Nov 4, 2015 at 8:54 AM, colinbeier <notifications@github.com>
> wrote:
> >
> > > Just those that can be linked...
> > >
> > > Lisa said the locations of the stations themselves were useless without
> > > the data (which is what I'd been saying for months, it took her
> actually
> > > seeing the map to realize)
> > >
> > > On Nov 4, 2015, at 8:51 AM, Steve Signell wrote:
> > >
> > > > Only 43 of the 67 stations have links on the DEC site.... should we
> show
> > > > them all, or just the ones that can be linked?
> > > >
> > > >
> > > > On Wed, Nov 4, 2015 at 8:28 AM, colinbeier <notifications@github.com
> >
> > > wrote:
> > > >
> > > > > It would be awesome if you could get this into one of the current
> > > Sprints
> > > > > (4 or 5)... that would make Lisa VERY HAPPY :)
> > > > >
> > > > > On Nov 4, 2015, at 8:24 AM, Steve Signell wrote:
> > > > >
> > > > > > Yes, very similar to the stream gages. Is this a priority for
> beta?
> > > I can
> > > > > > crank it out pretty quick
> > > > > >
> > > > > > On Wed, Nov 4, 2015 at 8:22 AM, colinbeier <
> notifications@github.com
> > > >
> > > > > wrote:
> > > > > >
> > > > > > > Agree. A crosswalk might be feasible given the number of
> stations.
> > > > > Would
> > > > > > > we be able to set something up to bring in the real-time data /
> > > > > forecast
> > > > > > > for each station, kind of like the USGS gauges?
> > > > > > >
> > > > > > > On Nov 4, 2015, at 8:19 AM, Steve Signell wrote:
> > > > > > >
> > > > > > > > I don't see an easy way to link to these, as they are using a
> > > set of
> > > > > > > UIDs that are not in our table. We could set up a crosswalk...
> > > there
> > > > > aren't
> > > > > > > many stations. Then we could have a link in the popup.
> > > > > > >
> > > > > > > >
> > > > > > > > —
> > > > > > > > Reply to this email directly or view it on GitHub.
> > > > > > > >
> > > > > > >
> > > > > > > —
> > > > > > > Reply to this email directly or view it on GitHub
> > > > > > > <
> > > > >
> > >
> https://github.com/caryfitzhugh/NYCCSC-map-viewer/issues/54#issuecomment-153717883
> > > > > >
> > > > > > > .
> > > > > > >
> > > > > >
> > > > > >
> > > > > >
> > > > > > --
> > > > > > Steve Signell
> > > > > > Frontier Spatial, L.L.C.
> > > > > > 1062 Dean St.
> > > > > > Schenectady, NY 12309
> > > > > > 518-232-1008
> > > > > > frontierspatial.com
> > > > > > steve@frontierspatial.com
> > > > > > —
> > > > > > Reply to this email directly or view it on GitHub.
> > > > > >
> > > > >
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > > <
> > >
> https://github.com/caryfitzhugh/NYCCSC-map-viewer/issues/54#issuecomment-153719217
> > > >
> > > > > .
> > > > >
> > > >
> > > >
> > > >
> > > > --
> > > > Steve Signell
> > > > Frontier Spatial, L.L.C.
> > > > 1062 Dean St.
> > > > Schenectady, NY 12309
> > > > 518-232-1008
> > > > frontierspatial.com
> > > > steve@frontierspatial.com
> > > > —
> > > > Reply to this email directly or view it on GitHub.
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> https://github.com/caryfitzhugh/NYCCSC-map-viewer/issues/54#issuecomment-153725091
> >
> > > .
> > >
> >
> >
> >
> > --
> > Steve Signell
> > Frontier Spatial, L.L.C.
> > 1062 Dean St.
> > Schenectady, NY 12309
> > 518-232-1008
> > frontierspatial.com
> > steve@frontierspatial.com
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/caryfitzhugh/NYCCSC-map-viewer/issues/54#issuecomment-153731800>
> .
>



-- 
Steve Signell
Frontier Spatial, L.L.C.
1062 Dean St.
Schenectady, NY 12309
518-232-1008
frontierspatial.com
steve@frontierspatial.com

**Comment by colinbeier** [comment]
cream dream - nice work!  you can close this baby.
