### ISSUE TITLE
Create new layer category (heading): Land Use

### ISSUE THREAD

**Issue by colinbeier** [caryfitzhugh/NYCCSC-map-viewer#55]
Lisa and others mentioned that the Land Use map layer (NLCD) should not be listed under a Sector heading, but under its own heading (or in its own category) called 'Land Use'.  

I really don't like creating one-off categories like this, so if we can come up with alternatives, I'm all ears.

**Comment by sasignell** [comment]
Air land water society

**Comment by sasignell** [comment]
Done.  Also added gap landcover (easy) so this wouldn't be a one-off category.  We could possibly expand this category to include land use and/or elevation/hillshade.

**Comment by sasignell** [comment]
I changed this to Land Cover-- is that what you meant?  Also added the Anthro. Biomes to it.
