### ISSUE TITLE
NYC Hurricane Evacuation Centers

### ISSUE THREAD

**Issue by colinbeier** [caryfitzhugh/NYCCSC-map-viewer#56]
Data should be harvestable from this web map

https://data.cityofnewyork.us/Public-Safety/Hurricane-Evacuation-Centers/ayer-cga7

**Comment by sasignell** [comment]
this is a pain; has a crazy NYC projection...

**Comment by colinbeier** [comment]
Not a priority for beta .. Sorry

Colin Beier
SUNY ESF

On Oct 27, 2015 8:56 PM, Steve Signell <notifications@github.com> wrote:

this is a pain; has a crazy NYC projection...

**Comment by caryfitzhugh** [comment]
ok. not a beta. moving out into the future.
