### ISSUE TITLE
Beta layers: Historical Climate

### ISSUE THREAD

**Issue by colinbeier** [caryfitzhugh/NYCCSC-map-viewer#60]
Content team would like to add several different historical climate layers from ACIS, might be bundled into a single layer, or added to other bundles:

Bill and Art have agreed to provide pre-canned summaries of these data from ACIS, summarized by county, watershed and climate zone, to generate choropleth maps.  

1. Seasonal count of days with rain > 1" 
2. Seasonal maximum length of consecutive dry days (<0.1" rain)
3. Seasonal count of days > extreme temperature base (90, 95, 100 °F)
4. Degree days 

Once Bill has these ready, they SHOULD work just like the historical PRISM data from ACIS.

**Comment by colinbeier** [comment]
WIll follow up (yet again) with Bill and Art on these ACIS-based summaries.  Stay tuned.

**Comment by sasignell** [comment]
If you want I can just pull in some random stuff from acis....doubt anyone
wound notice the difference

**Comment by colinbeier** [comment]
Maybe not, but we (you) would be wasting time... eventually someone will notice the data isn't what they asked for / would like and we'll have to go back and get something different.  Hang tight for now.

**Comment by caryfitzhugh** [comment]
is this all in?

**Comment by colinbeier** [comment]
yes, for this release, its good.
