### ISSUE TITLE
Beta layer: Greenhouse gas pools and fluxes

### ISSUE THREAD

**Issue by colinbeier** [caryfitzhugh/NYCCSC-map-viewer#63]
this site has spatial model outputs for several variables that are quite relevant for our map.  these could be clipped for NYS or US NE and combined into a single layer with toggling across the variables, or kept as separate layers:

Biomass C stock
http://landcarbon.org/categories/biomass-c/download/

Methane flux
http://landcarbon.org/categories/ch4-flux/download/

Net ecosystem C flux
http://landcarbon.org/categories/net-ecosystem-c-balance/download/

NOx flux
http://landcarbon.org/categories/n2o-flux/download/

Soil organic C stock
http://landcarbon.org/categories/soil-c/download/

Total ecosystem C stock
http://landcarbon.org/categories/ecosystem-c/download/

**Comment by sasignell** [comment]
These are some awkward file formats...

**Comment by colinbeier** [comment]
ok. does this mean you cannot use them?  or... how much extra work to get them in?

**Comment by sasignell** [comment]
These are downloaded as geotiffs... not the worst, but we'll have to come
up with symbology, e.g. color ramp for each one.  I can them serve them as
WMS via Geoserver.  I have absolutely no idea which ones are relevant and
for which time period, so if you could download the tiffs for the ones you
want (preferrably clipped to NY and environs) I can then load them up, and
we can create a layer switcher or whatever.

Unfortunately, it seems the only way to clip the data before downloading is
to draw a box (actually just click 2 corners of a box-- took me a few
minutes to figure that out.)  The file upload does not seem to do anything,
although you could try it with one of the attached files.  Drawing a box by
hand for multiple datasets will kind of stink because they'll all be
slightly different in extent.

On Tue, Oct 27, 2015 at 10:50 PM, colinbeier <notifications@github.com>
wrote:

> ok. does this mean you cannot use them? or... how much extra work to get
> them in?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/caryfitzhugh/NYCCSC-map-viewer/issues/63#issuecomment-151706202>
> .
>



-- 
Steve Signell
Frontier Spatial, L.L.C.
1062 Dean St.
Schenectady, NY 12309
518-232-1008
frontierspatial.com
steve@frontierspatial.com

**Comment by colinbeier** [comment]
I have created six (6) geotiffs, two variables (Biomass C, Net Ecosystem Flux) and three parameters each (2010, 2050 B1 scenario, 2050 A2 scenario).  Will send to Steve by email.

**Comment by colinbeier** [comment]
Another alternative, not quite the same but should suffice, and is based on measurements, not models. 

http://www.ncasi2.org/GCOLE3/gcole.shtml

I downloaded a bunch of .shp files which I believe we can bring into the map pretty easily.  Will send to Steve as alternative to the data sets from LandCarbon that are mentioned above.

**Comment by sasignell** [comment]
OK I added one of Colin's geotiffs to geoserver and it works great coming straight out of geoserver:

http://52.11.55.233:8080/geoserver/nyccsc/wms?service=WMS&version=1.1.0&request=GetMap&layers=nyccsc:frstc_cent_miroc_a2_2010_WGS84&styles=&bbox=-127.8734072494179,22.90110267493787,-65.36375557531585,51.54864624218032&width=768&height=351&srs=EPSG:4326&format=application/openlayers

I loaded it into our site @ Ecosystems-->Forest Carbon (probably not the right title).  However, there are some issues with the rendering on our site... I think it has to do with 1) the fact that this is a geotiff, not a postgis layer, and 2) some opacity conflicts with our code 3)the fact that it's so large and finally 4)the cdn has cached some of my earlier versions of this before I had the symbology configured correctly.

**Comment by caryfitzhugh** [comment]
The layer works for me at the moment? opacity and ordering are correct.
The 2050 layer shows nothing though (maybe that is your caching issue). I will evict the cache now.

**Comment by sasignell** [comment]
Maybe it was just a bandwidth issue on my end.  It will help to clip the
tiffs to the n East .I haven't added 2050 yet...

**Comment by sasignell** [comment]
So should I continue working to bring in the rest of the GeoTIffs, or should I shift to the hex polygons?

**Comment by colinbeier** [comment]
Let me see / test the geotiffs tonight and I'll follow up...

Colin Beier
SUNY ESF

On Nov 3, 2015 5:31 PM, Steve Signell <notifications@github.com> wrote:

So should I continue working to bring in the rest of the GeoTIffs, or should I shift to the hex polygons?

**Comment by colinbeier** [comment]
For the geotiff, are you generating the color bar and could you easily adjust / edit it?  Or is it built-in?  There also seem to be a number of errors reporting back (70). 

If we cannot easily change the color ramp for the geotiff, then we should go with the hex polygons.

**Comment by sasignell** [comment]
we can change the color ramp pretty easily... what do you want it to be?

On Tue, Nov 3, 2015 at 8:42 PM, colinbeier <notifications@github.com> wrote:

> For the geotiff, are you generating the color bar and could you easily
> adjust / edit it? Or is it built-in? There also seem to be a number of
> errors reporting back (70).
>
> If we cannot easily change the color ramp for the geotiff, then we should
> go with the hex polygons.
>
> On Nov 3, 2015, at 5:32 PM, Steve Signell wrote:
>
> > So should I continue working to bring in the rest of the GeoTIffs, or
> should I shift to the hex polygons?
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/caryfitzhugh/NYCCSC-map-viewer/issues/63#issuecomment-153544010>
> .
>



-- 
Steve Signell
Frontier Spatial, L.L.C.
1062 Dean St.
Schenectady, NY 12309
518-232-1008
frontierspatial.com
steve@frontierspatial.com

**Comment by colinbeier** [comment]
white to green

http://www.pixelfor.me/crc/F06C053C

**Comment by sasignell** [comment]
OK done. check it out.

On Tue, Nov 3, 2015 at 9:42 PM, colinbeier <notifications@github.com> wrote:

> white to green
>
> http://www.pixelfor.me/crc/F06C053C
>
>
> On Nov 3, 2015, at 9:16 PM, Steve Signell wrote:
>
> > we can change the color ramp pretty easily... what do you want it to be?
> >
> > On Tue, Nov 3, 2015 at 8:42 PM, colinbeier <notifications@github.com>
> wrote:
> >
> > > For the geotiff, are you generating the color bar and could you easily
> > > adjust / edit it? Or is it built-in? There also seem to be a number of
> > > errors reporting back (70).
> > >
> > > If we cannot easily change the color ramp for the geotiff, then we
> should
> > > go with the hex polygons.
> > >
> > > On Nov 3, 2015, at 5:32 PM, Steve Signell wrote:
> > >
> > > > So should I continue working to bring in the rest of the GeoTIffs, or
> > > should I shift to the hex polygons?
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub.
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> https://github.com/caryfitzhugh/NYCCSC-map-viewer/issues/63#issuecomment-153544010
> >
> > > .
> > >
> >
> >
> >
> > --
> > Steve Signell
> > Frontier Spatial, L.L.C.
> > 1062 Dean St.
> > Schenectady, NY 12309
> > 518-232-1008
> > frontierspatial.com
> > steve@frontierspatial.com
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/caryfitzhugh/NYCCSC-map-viewer/issues/63#issuecomment-153553730>
> .
>



-- 
Steve Signell
Frontier Spatial, L.L.C.
1062 Dean St.
Schenectady, NY 12309
518-232-1008
frontierspatial.com
steve@frontierspatial.com

**Comment by colinbeier** [comment]
looks good... the tiling seems to be doing something weird with the raster symbology, like this:

**Comment by colinbeier** [comment]
also, when i click on the map with the layer on, it downloads a wms file automatically?  in Chrome

**Comment by sasignell** [comment]
that was the get feature request bugging out.  Just fixed for this layer
and anthromes.  The formatting leaves something to be desired in the
getfeatureinfo modal, but we may be styling that on the client side soon.

On Tue, Nov 3, 2015 at 10:10 PM, colinbeier <notifications@github.com>
wrote:

> also, when i click on the map with the layer on, it downloads a wms file
> automatically? in Chrome
>
> On Nov 3, 2015, at 9:59 PM, Steve Signell wrote:
>
> > OK done. check it out.
> >
> > On Tue, Nov 3, 2015 at 9:42 PM, colinbeier <notifications@github.com>
> wrote:
> >
> > > white to green
> > >
> > > http://www.pixelfor.me/crc/F06C053C
> > >
> > >
> > > On Nov 3, 2015, at 9:16 PM, Steve Signell wrote:
> > >
> > > > we can change the color ramp pretty easily... what do you want it to
> be?
> > > >
> > > > On Tue, Nov 3, 2015 at 8:42 PM, colinbeier <notifications@github.com
> >
> > > wrote:
> > > >
> > > > > For the geotiff, are you generating the color bar and could you
> easily
> > > > > adjust / edit it? Or is it built-in? There also seem to be a
> number of
> > > > > errors reporting back (70).
> > > > >
> > > > > If we cannot easily change the color ramp for the geotiff, then we
> > > should
> > > > > go with the hex polygons.
> > > > >
> > > > > On Nov 3, 2015, at 5:32 PM, Steve Signell wrote:
> > > > >
> > > > > > So should I continue working to bring in the rest of the
> GeoTIffs, or
> > > > > should I shift to the hex polygons?
> > > > > >
> > > > > > —
> > > > > > Reply to this email directly or view it on GitHub.
> > > > > >
> > > > >
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > > <
> > >
> https://github.com/caryfitzhugh/NYCCSC-map-viewer/issues/63#issuecomment-153544010
> > > >
> > > > > .
> > > > >
> > > >
> > > >
> > > >
> > > > --
> > > > Steve Signell
> > > > Frontier Spatial, L.L.C.
> > > > 1062 Dean St.
> > > > Schenectady, NY 12309
> > > > 518-232-1008
> > > > frontierspatial.com
> > > > steve@frontierspatial.com
> > > > —
> > > > Reply to this email directly or view it on GitHub.
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> https://github.com/caryfitzhugh/NYCCSC-map-viewer/issues/63#issuecomment-153553730
> >
> > > .
> > >
> >
> >
> >
> > --
> > Steve Signell
> > Frontier Spatial, L.L.C.
> > 1062 Dean St.
> > Schenectady, NY 12309
> > 518-232-1008
> > frontierspatial.com
> > steve@frontierspatial.com
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/caryfitzhugh/NYCCSC-map-viewer/issues/63#issuecomment-153558897>
> .
>



-- 
Steve Signell
Frontier Spatial, L.L.C.
1062 Dean St.
Schenectady, NY 12309
518-232-1008
frontierspatial.com
steve@frontierspatial.com

**Comment by colinbeier** [comment]
this geotiff looks good, i think it suffices for BETA purposes. we have the list of other variables that Land Carbon offers.  We also have the hex polygons based on the FIA data, and those should be easy enough to bring in (and serve) via Geoserver.  So... for now this one go bye bye.
