### ISSUE TITLE
change mouse icon to crosshairs or help

### ISSUE THREAD

**Issue by sasignell** [caryfitzhugh/NYCCSC-map-viewer#65]
Pointer does not make it obvious that map can be clicked for info

**Comment by caryfitzhugh** [comment]
http://stackoverflow.com/questions/24093263/set-font-awesome-icons-as-cursor-is-this-possible

http://fortawesome.github.io/Font-Awesome/icon/crosshairs/

?

Would that be what we want?

**Comment by caryfitzhugh** [comment]
I guess the test would be - if there are any layers active which allow get_feature_info requests.

**Comment by sasignell** [comment]
Yes, that sounds about right!

On Tue, Oct 27, 2015 at 11:57 AM, Cary FitzHugh <notifications@github.com>
wrote:

> I guess the test would be - if there are any layers active which allow
> get_feature_info requests.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/caryfitzhugh/NYCCSC-map-viewer/issues/65#issuecomment-151549821>
> .
>



-- 
Steve Signell
Frontier Spatial, L.L.C.
1062 Dean St.
Schenectady, NY 12309
518-232-1008
frontierspatial.com
steve@frontierspatial.com

**Comment by caryfitzhugh** [comment]
blerg. I can't do it.
The CSS should work. but it doesnt'.  I looked around. FFx is slightly better, but still bad.
The only alternative is something with JS (somehow?) --  I looked at the terria.js site and they don't do it either.  

Saw terria js had the source loading and would put up a loading indicator... replicated that, sorta nifty.

But no-go on the cursor. The CSS cursor rules don't seem to work over top of a leaflet map.

I'll let you close this Steve.

**Comment by sasignell** [comment]
I just changed the css for the map to be cursor: crosshair.  I think this is an improvement over the (drag)hand.

**Comment by caryfitzhugh** [comment]
Weird

If it works, great.  I couldn't get it to consistently show the cursor, but
something else may have been messing it up

**Comment by sasignell** [comment]
I haven't tested it much so you could be right....

**Comment by colinbeier** [comment]
Seems to work OK.  We'll probably need to test this with users.

**Comment by caryfitzhugh** [comment]
closing.
