### ISSUE TITLE
Make jsonp calls from geoserver (json_feed.js) for development

### ISSUE THREAD

**Issue by sasignell** [caryfitzhugh/NYCCSC-map-viewer#66]
It is awkward to have to cut and paste geojson into json_feed.js during dev when PostGIS queries are being tweaked.  The jsonp feeds from Geoserver are pulled live from db

**Comment by caryfitzhugh** [comment]
this is represented in a different issue. closing this one in favor of that one.
https://github.com/caryfitzhugh/NYCCSC-map-viewer/issues/67
