### ISSUE TITLE
Load geojson only if layer is clicked on?

### ISSUE THREAD

**Issue by sasignell** [caryfitzhugh/NYCCSC-map-viewer#67]
Currently, the size of geoJSON data is getting pretty large and causes the initial map load to be slow.  Can we have these load only if the layer is clicked on?  That seemed to be working pretty well before.

**Comment by colinbeier** [comment]
Yes that sounds good to me

Colin Beier
SUNY ESF

On Oct 27, 2015 8:07 AM, Steve Signell <notifications@github.com> wrote:

Currently, the size of geoJSON data is getting pretty large and causes the initial map load to be slow. Can we have these load only if the layer is clicked on? That seemed to be working pretty well before.

**Comment by caryfitzhugh** [comment]
Yeah, we can do that. Just do the getJSON in the create_leaflet_layers.

**Comment by caryfitzhugh** [comment]
ops. sorry

**Comment by caryfitzhugh** [comment]
I'm working on htis.

**Comment by caryfitzhugh** [comment]
- [ ] dams
- [ ] spdes
- [ ] subwayLines
- [ ] airmon
- [ ] alsc 
- [ ] hostpital

**Comment by caryfitzhugh** [comment]
ghg_facilities, are new..  Do we serve them? Can I use my standard URL to get that geoJSON data?

**Comment by sasignell** [comment]
Yes the ghg_facilities are on geoserver, same url template.


On Mon, Nov 2, 2015 at 4:40 PM, Cary FitzHugh <notifications@github.com>
wrote:

> ghg_facilities, are new.. Do we serve them? Can I use my standard URL to
> get that geoJSON data?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/caryfitzhugh/NYCCSC-map-viewer/issues/67#issuecomment-153165818>
> .
>



-- 
Steve Signell
Frontier Spatial, L.L.C.
1062 Dean St.
Schenectady, NY 12309
518-232-1008
frontierspatial.com
steve@frontierspatial.com

**Comment by caryfitzhugh** [comment]
@sasignell the issue with dams is that the longitude is incorrect.  They all are basically 0. This is pulled from the feed (first record I see).  This is the URL I used.

http://d6wsatugt1elr.cloudfront.net/geoserver/wfs?Renderers.dams.jsonp_callback=jQuery111305776277424301952_1446567819254&service=WFS&version=1.1.0&request=GetFeature&typeName=dams&srsName=EPSG%3A4326&outputFormat=text%2Fjavascript&format_options=callback%3ARenderers.dams.jsonp_callback%3B&_=1446567819255

```json
{"type":"Feature",
  "id":"dams.fid--15c7a0c3_150ce285afc_-6fee",
   "geometry":{
        "type":"Point",
         "coordinates":[-79.4894448363725, 3.907791113492804E-4]
    },
    "geometry_name":"geom",
    "properties":{"state_id":"027-0040","federal_id":"NY00485","name":"Oak Orchard Creek Dam:Waterport Pond","constr_typ":"CN - Concrete Gravity","hazard":"High hazard","hazard_code":"C","owners":"Brookfield Renewable Energy Group - Ny West Operations","purposes":"Hydroelectric"}}
```

**Comment by sasignell** [comment]
Not sure what's up with this... the lat lons are correct here 

http://52.11.55.233:8080/geoserver/nyccsc/wms?service=WMS&version=1.1.0&request=GetMap&layers=nyccsc:dams&styles=&bbox=-79.7588888888378,40.5166666666633,-72.2933333333283,45.0061111111044&width=768&height=461&srs=EPSG:26918&format=application/openlayers

and here

http://52.11.55.233:8080/geoserver/nyccsc/wfs?service=WFS&version=1.0.0&request=GetFeature&typeName=nyccsc:dams&maxFeatures=50&outputFormat=application/json

**Comment by caryfitzhugh** [comment]
Let me make sure that is the URL I am using.

**Comment by caryfitzhugh** [comment]
This URL is what I'm using.
ANd it seems to have the borked longitudes.

http://52.11.55.233:8080/geoserver/wfs?Renderers.dams.jsonp_callback=jQuery111307635393589735031_1446648770270&service=WFS&version=1.1.0&request=GetFeature&typeName=dams&srsName=EPSG%3A4326&outputFormat=text%2Fjavascript&format_options=callback%3ARenderers.dams.jsonp_callback%3B&_=1446648770271

Comparing the two, I notice that my URL has the srsName, if I remove that...
http://52.11.55.233:8080/geoserver/wfs?Renderers.dams.jsonp_callback=jQuery111307635393589735031_1446648770270&service=WFS&version=1.1.0&request=GetFeature&typeName=dams&outputFormat=text%2Fjavascript&format_options=callback%3ARenderers.dams.jsonp_callback%3B&_=1446648770271

I get the right stuff! Weird.
So - what is srsName?

Updating dams.

**Comment by caryfitzhugh** [comment]
Sweet! WOrks.

**Comment by sasignell** [comment]
srs name is the name of the Spatial Reference System... goeserver converts
everything to lat lon (srs=WGS84, epsg4326) anyway, so no need for that
parameter


On Wed, Nov 4, 2015 at 9:55 AM, Cary FitzHugh <notifications@github.com>
wrote:

> This URL is what I'm using.
> ANd it seems to have the borked longitudes.
>
>
> http://52.11.55.233:8080/geoserver/wfs?Renderers.dams.jsonp_callback=jQuery111307635393589735031_1446648770270&service=WFS&version=1.1.0&request=GetFeature&typeName=dams&srsName=EPSG%3A4326&outputFormat=text%2Fjavascript&format_options=callback%3ARenderers.dams.jsonp_callback%3B&_=1446648770271
>
> Comparing the two, I notice that my URL has the srsName, if I remove
> that...
>
> http://52.11.55.233:8080/geoserver/wfs?Renderers.dams.jsonp_callback=jQuery111307635393589735031_1446648770270&service=WFS&version=1.1.0&request=GetFeature&typeName=dams&outputFormat=text%2Fjavascript&format_options=callback%3ARenderers.dams.jsonp_callback%3B&_=1446648770271
>
> I get the right stuff! Weird.
> So - what is srsName?
>
> Updating dams.
>
> On Wed, Nov 4, 2015 at 9:49 AM, Cary FitzHugh <cary.fitzhugh@gmail.com>
> wrote:
>
>
> > Let me make sure that is the URL I am using.
> >
> > On Wed, Nov 4, 2015 at 9:48 AM, Steve Signell <notifications@github.com>
> > wrote:
> >
> >> Not sure what's up with this... the lat lons are correct here
> >>
> >>
> >>
> http://52.11.55.233:8080/geoserver/nyccsc/wms?service=WMS&version=1.1.0&request=GetMap&layers=nyccsc:dams&styles=&bbox=-79.7588888888378,40.5166666666633,-72.2933333333283,45.0061111111044&width=768&height=461&srs=EPSG:26918&format=application/openlayers
> >>
> >> and here
> >>
> >>
> >>
> http://52.11.55.233:8080/geoserver/nyccsc/wfs?service=WFS&version=1.0.0&request=GetFeature&typeName=nyccsc:dams&maxFeatures=50&outputFormat=application/json
> >>
> >> —
> >> Reply to this email directly or view it on GitHub
> >> <
> https://github.com/caryfitzhugh/NYCCSC-map-viewer/issues/67#issuecomment-153749524
> >
> >> .
> >>
> >
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/caryfitzhugh/NYCCSC-map-viewer/issues/67#issuecomment-153752497>
> .
>



-- 
Steve Signell
Frontier Spatial, L.L.C.
1062 Dean St.
Schenectady, NY 12309
518-232-1008
frontierspatial.com
steve@frontierspatial.com

**Comment by caryfitzhugh** [comment]
sweet! I closed this with a git commit message. :+1:
