### ISSUE TITLE
getFeatureInfo behavior

### ISSUE THREAD

**Issue by sasignell** [caryfitzhugh/NYCCSC-map-viewer#68]
there should be no popup if nothing is returned

only layers with valid results should show up in the modal (no blank rows for active layers that return no results)

**Comment by caryfitzhugh** [comment]
This is tricky.

If we want to do this, we'd need to add some code into your iframe responses, to tell us (the parent container) what height to make you when you are done loading.
It might be some JS as simple as window.postMessage ( ) ...
https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage
The loading iframe would need to inform the parent iframe when it has loaded and what height it's view is.  So the parent modal could figure out when to display or not.

Or we can go with just returning HTML.  If the getFeatureInfo calls return HTML via a JSONP call, I can manipulate the data easier. This is similar to what you had done before.

Which do you prefer?  I think, now realizing that we may make requests that return nothing, I think I'd lean towards the JSONP get_Feature_info...   It also doesn't keep things squished into a small box.

On the other hand -- if you want to do D3 and other complex things in those responses, it may be good to spend the time to have some postMessage callback messages (if only to keep the rendering separate and clean).

**Comment by caryfitzhugh** [comment]
I'll look at doing the iframe JS code.  Should not be too hard.  

But it means that 3rd party getFeatureInfo URLs may not work. Do we care?  When I tried them before, there never was much good info from them... (if there was iframe info at all).

**Comment by caryfitzhugh** [comment]
The decision was to pull back JSONP, and then let steve render this in the UI with ractive.
TBD.  Need to riffle across all the gfi layers and do this.

**Comment by caryfitzhugh** [comment]
some sites use JSON.
some use JSONP.
I'm hoping to keep it consistent, and use JSON / AJAX, which means our server needs CORS enabled.

**Comment by caryfitzhugh** [comment]
@sasignell there are a few that I need your expertise on.

* usgs-stream
* slr_vuln
* nlcd

**Comment by caryfitzhugh** [comment]
These are getting close. I did a few examples for @sasignell.  
I'll try to do some more tonight. 

This is a much better UI experience, if things aren't found at the location, nothing comes up in the modal. Woot.  Very close.

I can't figure out power-stations.  Maybe @sasignell can give some expertise in decoding what the identify url should have. I couldn't get it working. :( 

If we can't get the GFI calls working for usgs / slr_vuln and ncld, I'll just turn those off for now.

CLOSE!  WOooOOOoOOoOoOt!
:checkered_flag:

**Comment by caryfitzhugh** [comment]
ok. done for now. Adding some tasks in for the missing GFI layers.

**Comment by caryfitzhugh** [comment]
https://github.com/caryfitzhugh/NYCCSC-map-viewer/issues/87
