### ISSUE TITLE
Possible Layer: Ecosystems: US Forest Service Climate Atlas - Trees

### ISSUE THREAD

**Issue by colinbeier** [caryfitzhugh/NYCCSC-map-viewer#74]
Iverson et al.'s models of future habitat for US tree species:

http://www.fs.fed.us/nrs/atlas/

KMZ download here (as of 10.28.15), CMB also has files if this link is down:

https://www.cloudvault.usda.gov/public.php?service=files&t=04f6784f6a8f0d6bfcb11dba22c7858b&download

I'm writing this as I download the files, not sure what they look like yet, will comment again with more details on what we actually want to bring into our map as a layer.

**Comment by colinbeier** [comment]
Check here for web services:

http://wassimap.sgcp.ncsu.edu:8399/arcgis/rest/services/taccimo

**Comment by sasignell** [comment]
these WMS will be easy as cake to integrate.  We should pick a dozen or so
high profile species off this list
<http://wassimap.sgcp.ncsu.edu:8399/arcgis/rest/services/taccimo/treeatlas_high/MapServer>
 and I'll make some sliders, dropdowns, etc.


On Mon, Nov 16, 2015 at 10:59 AM, colinbeier <notifications@github.com>
wrote:

> Check here for web services:
>
> http://wassimap.sgcp.ncsu.edu:8399/arcgis/rest/services/taccimo
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/caryfitzhugh/NYCCSC-map-viewer/issues/74#issuecomment-157078369>
> .
>



-- 
Steve Signell
Frontier Spatial, L.L.C.
1062 Dean St.
Schenectady, NY 12309
518-232-1008
frontierspatial.com
steve@frontierspatial.com

**Comment by colinbeier** [comment]
OK, here's a list of species and layer numbers, based on the link above.  I would like to have a drop down for the species (common name), ad a toggle for the scenarios (current, GCM Hi, GCM Low), which would switch between the three layers for each species.  

taccimo climate atlas layers:

species
common name
current
GCM Hi emissions
GCM Low emissions

Acer rubrum
Red maple
4
60
116

Acer saccharum
Sugar maple
5
61
117

Betula alleghaniensis
Yellow birch
7
64
119

Carya glabra
Pignut hickory
10
66
122

Fagus grandifolia
American beech
14
70
126

Fraxinus americana
White ash
15
71
127

Picea rubens
Red spruce
28
84
140

Pinus strobus
Eastern white pine
35
91
147

Populus tremuloides
Quaking aspen
40
96
152

Prunus serotina
Black cherry
41
97
146

Quercus alba
White oak
42
98
154

Quercus rubra
Northern red oak
49
105
161

Tsuga canadensis
Eastern hemlock
55
111
167

**Comment by sasignell** [comment]
I added the layer with radio button toggles for scenario=current/low/high and species=yellow birch, sugar maple.

However, the scenarios should be a slider with values 0, 64(high) and 112(low), and the species need to be a dropdown box.  We don't have example of a slider with discrete values, or a dropdown... Cary, can you help with those?

**Comment by caryfitzhugh** [comment]
yes, I can help with those. :) I'll look at this when I can.

**Comment by sasignell** [comment]
This basically done, although there's still an issue with the slider-- it
should go from current-->low-->high...

On Thu, Dec 10, 2015 at 10:18 AM, Cary FitzHugh <notifications@github.com>
wrote:

> yes, I can help with those. :) I'll look at this when I can.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/caryfitzhugh/NYCCSC-map-viewer/issues/74#issuecomment-163655673>
> .
>



-- 
Steve Signell
Frontier Spatial, L.L.C.
1062 Dean St.
Schenectady, NY 12309
518-232-1008
frontierspatial.com
steve@frontierspatial.com

**Comment by caryfitzhugh** [comment]
look at #99 for a few updates to the nomenclature.

**Comment by caryfitzhugh** [comment]
psuhed.  CDN still in progress..  will need to use
?cdn=disable for now.
