### ISSUE TITLE
BETA: Map directory (folders, subfolders, layers)

### ISSUE THREAD

**Issue by colinbeier** [caryfitzhugh/NYCCSC-map-viewer#79]
Here is a working draft of a map DIRECTORY that we can use to keep track of layers and organize stuff.

https://docs.google.com/spreadsheets/d/1t8yaZku75ugT55ulGEUAryriNGL3WPe46rfy7aQZfK0/edit#gid=4585829

**Comment by caryfitzhugh** [comment]
I'm going to close this, just because it's not an actionable task.  it'll stay in the history though so people can find it if they want the link.
