### ISSUE TITLE
Beta layer: Social Vulnerability Index

### ISSUE THREAD

**Issue by colinbeier** [caryfitzhugh/NYCCSC-map-viewer#80]
Map layer disappears when zoomed in beyond the 20km scale bar.  If this is a default, we should probably change it so that users can zoom in further.  

Also, the Get Info function is not working with this layer. Should it return the index value?

**Comment by sasignell** [comment]
Unfortunately the zoom issue is baked into the web map service.  As far as getFeatureInfo goes, the WMS does not appear to be functional... try it out here:

http://catalog.data.gov/dataset/social-vulnerability-index-sovi-for-the-u-s-coastal-states-based-on-the-2010-census-tracts/resource/288ce3de-f720-4579-a250-6847274c70eb

**Comment by caryfitzhugh** [comment]
I can look and see if I can make the request for XML.

**Comment by caryfitzhugh** [comment]
how can I tell from this:
http://coast.noaa.gov/arcgis/rest/services/sovi/sovi_tracts2010/MapServer
what the LAYERS / QUERY_LAYERS / STYLES parameters can be?

**Comment by sasignell** [comment]
there's a little 'WMS' link on that page that takes you to the WMS
getCapabilities Document:

*http://coast.noaa.gov/arcgis/services/sovi/sovi_tracts2010/MapServer/WMSServer?request=GetCapabilities&service=WMS
<http://coast.noaa.gov/arcgis/services/sovi/sovi_tracts2010/MapServer/WMSServer?request=GetCapabilities&service=WMS>*

Are we trying to make it show when zoomed in?  Not sure if we'll be able to
do that... seems they've turned it off server-side.


On Thu, Nov 5, 2015 at 12:06 PM, Cary FitzHugh <notifications@github.com>
wrote:

> how can I tell from this:
> http://coast.noaa.gov/arcgis/rest/services/sovi/sovi_tracts2010/MapServer
> what the LAYERS / QUERY_LAYERS / STYLES parameters can be?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/caryfitzhugh/NYCCSC-map-viewer/issues/80#issuecomment-154124281>
> .
>



-- 
Steve Signell
Frontier Spatial, L.L.C.
1062 Dean St.
Schenectady, NY 12309
518-232-1008
frontierspatial.com
steve@frontierspatial.com

**Comment by colinbeier** [comment]
I'll confirm with Lisa that this is a limitation set by the data provider... she and Content Team can decide later if they want to remove the layer.  We'll leave it in for now.  With that, I'll close the issue.

**Comment by sasignell** [comment]
OK I dug deeper and found the problem.  Sorry I didn't catch it earlier-- should be fixed now
