### ISSUE TITLE
Make sure all external sites are behind a CDN

### ISSUE THREAD

**Issue by caryfitzhugh** [caryfitzhugh/NYCCSC-map-viewer#88]
This was done. we'll need to do it again.

**Comment by caryfitzhugh** [comment]
And make sure all the front-end parts are https, regardless of the backend (http or https source servers)

**Comment by caryfitzhugh** [comment]
The CDNs all need to respect https.  
The CDN method needs to force to https if it finds a match.

**Comment by colinbeier** [comment]
based on the emails from Lisa this morning, seems like this issue with the https is persisting (e.g., NOAA layers)... has this been "fixed" but not yet pushed to production, or does it still need to be "fixed"?

**Comment by sasignell** [comment]
I didn't get the emails from Lisa... was there anything pertinent to me?


On Thu, Dec 10, 2015 at 8:51 AM, colinbeier <notifications@github.com>
wrote:

> based on the emails from Lisa this morning, seems like this issue with the
> https is persisting (e.g., NOAA layers)... has this been "fixed" but not
> yet pushed to production, or does it still need to be "fixed"?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/caryfitzhugh/NYCCSC-map-viewer/issues/88#issuecomment-163624316>
> .
>



-- 
Steve Signell
Frontier Spatial, L.L.C.
1062 Dean St.
Schenectady, NY 12309
518-232-1008
frontierspatial.com
steve@frontierspatial.com

**Comment by caryfitzhugh** [comment]
This is not fixed. I rememeberd this last night, and will try to get this
done for monday.

**Comment by caryfitzhugh** [comment]
this is fixed and pushed.

**Comment by caryfitzhugh** [comment]
CFEM_critical is mussed up. I needed to set the format to "image%/png" ?? Ha. what a silly bug.
At least they told me in a 301 redirect that I needed it... oy!

![shell 2015-12-10 12-56-25](https://cloud.githubusercontent.com/assets/445848/11723663/881e87c2-9f3d-11e5-8524-8bd3dff529d5.png)
