### ISSUE TITLE
Convert USGS streamflow to vector layer

### ISSUE THREAD

**Issue by sasignell** [caryfitzhugh/NYCCSC-map-viewer#92]
Colin wanted me to move USGS stream gages back to vector layer rather than WMS.  I did that, however I had that one set up as CircleMarkers rather than Markers and it was throwing an error relating to opacity in lines 87 & 89 of usgs_streamflow.js so I commented them out.  Is there an easy fix to this, or am I going to have to convert this to markers?

**Comment by caryfitzhugh** [comment]
i'll take a gander tonight.

**Comment by caryfitzhugh** [comment]
Since you have a circleMarker in there, the function setOpacity doesn't work for that.
We need to setStyle({fillOpacity 0, opacity:0 }) 
to hide it.
and a similar one to show it.

I also made sure the JSONP here was going to be cached by the CDN.

Marker circles look cool!

**Comment by sasignell** [comment]
Just one thing... this layer is drawing behind the WMS layers.  There's a leaflet function called .bringToFront(); that might be useful.  If these circlemarkers are a pain, I can convert it to markers, so let me know, Cary.  Or I could try doing a D3 prototype on this and see how it works..

**Comment by caryfitzhugh** [comment]
ok, no worries. I'll look.

**Comment by caryfitzhugh** [comment]
THis is fixed now - there was some older leftover CSS from an earlier idea I was aiming towards.
