### ISSUE TITLE
Add clusters to alsc and fix popups

### ISSUE THREAD

**Issue by sasignell** [caryfitzhugh/NYCCSC-map-viewer#93]

**Comment by sasignell** [comment]
Again, I can't figure out why this isn't working... maybe something do do with having switched servers?  You might want to look at LayerInfo.js where I changed some parameters to point to Colin's new server... maybe I fudged something up?

**Comment by caryfitzhugh** [comment]
I found something :)

The coordinates on that data that was pulled in were like this:
```
geometry: Object
  coordinates: Array[2]
    0: 569489
    1: 4929676
    length: 2
type: "Point"
```

Those don't look right to me.  Lat/lng is what we need!

And so - I vaguely remembered something about the srsName.
And sure enough, the srsName parameter had been dropped from the new alsc.

```
srsName: "EPSG:4326",
```

so - adding that in, seems to have made it work.
