### ISSUE TITLE
convert hospitals to wfs call instead of jsonFeed

### ISSUE THREAD

**Issue by sasignell** [caryfitzhugh/NYCCSC-map-viewer#94]
I added the hospital layer to the geoserver on 52.2.5.122 and hooked up the render file, but I think there is a problem with the CDN-- its having trouble finding the wfs service for that layer....

**Comment by caryfitzhugh** [comment]
hey @sasignell hope you are well!
I looked, and found a few issues in our JSONP calls - simply that they wouldn't be cached by the CDN, so I fixed those.

But - I'm not sure what is going on with the hospitals call through the CDN. 

I have now enabled logging on this CDN, so I can see what is going in and coming out. 
Maybe you can find the apache logs on that geoserer and see why it's returning something invalid.

make a request to this
```
/geoserver/wfs?service=WFS&version=1.1.0&request=GetFeature&typeName=hospital&outputFormat=text%2Fjavascript&format_options=callback%3ARenderers.hospital.jsonp_callback
```
and then through the CDN
```
http://d3k0ernyjb0bdf.cloudfront.net/geoserver/wfs?service=WFS&version=1.1.0&request=GetFeature&typeName=hospital&outputFormat=text%2Fjavascript&format_options=callback%3ARenderers.hospital.jsonp_callback&_test
```


I had to add _test (or whatever you want) to make that request go through the CDN to the server.

**Comment by caryfitzhugh** [comment]
I looked at the logs in Cloudfront, not very helpful.
Need to get a hold of the logs on the apache server. I'm having trouble understanding what is going on (and why it's only going on for this ...)

**Comment by sasignell** [comment]
Maybe its because I forgot to update the /server folder?  I just pushed the
latest to GitHub

On Fri, Nov 20, 2015 at 9:25 AM, Cary FitzHugh <notifications@github.com>
wrote:

> I looked at the logs in Cloudfront, not very helpful.
> Need to get a hold of the logs on the apache server. I'm having trouble
> understanding what is going on (and why it's only going on for this ...)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/caryfitzhugh/NYCCSC-map-viewer/issues/94#issuecomment-158414555>
> .
>



-- 
Steve Signell
Frontier Spatial, L.L.C.
1062 Dean St.
Schenectady, NY 12309
518-232-1008
frontierspatial.com
steve@frontierspatial.com

**Comment by caryfitzhugh** [comment]
that shoulnd't have much effect on it - since the server we are hitting is the one you stood up.
hrm.  did you do any auth stuff? shouldn't I be able to log into that instance with the nyccsc creds?

**Comment by caryfitzhugh** [comment]
speaking of that (server deployment) -- you mentioned at one point confiugring apache with some files in the server dir -- which files were those? I assume those shouldn't be in the WAR file, but somewhere else  so that apache can pick them up.

**Comment by sasignell** [comment]
It made me generate a new key pair (since I moved it from Oregon to Va.)...
try the attached

On Fri, Nov 20, 2015 at 9:46 AM, Cary FitzHugh <notifications@github.com>
wrote:

> speaking of that (server deployment) -- you mentioned at one point
> confiugring apache with some files in the server dir -- which files were
> those? I assume those shouldn't be in the WAR file, but somewhere else so
> that apache can pick them up.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/caryfitzhugh/NYCCSC-map-viewer/issues/94#issuecomment-158420254>
> .
>



-- 
Steve Signell
Frontier Spatial, L.L.C.
1062 Dean St.
Schenectady, NY 12309
518-232-1008
frontierspatial.com
steve@frontierspatial.com

**Comment by caryfitzhugh** [comment]
can't attach to gituhub issues I guess...

**Comment by caryfitzhugh** [comment]
send me something over the gogole chat with history off.

**Comment by sasignell** [comment]
just sent you a regular email...did you recieve?



On Fri, Nov 20, 2015 at 10:18 AM, Cary FitzHugh <notifications@github.com>
wrote:

> send me something over the gogole chat with history off.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/caryfitzhugh/NYCCSC-map-viewer/issues/94#issuecomment-158429241>
> .
>



-- 
Steve Signell
Frontier Spatial, L.L.C.
1062 Dean St.
Schenectady, NY 12309
518-232-1008
frontierspatial.com
steve@frontierspatial.com

**Comment by caryfitzhugh** [comment]
weird. the CDN may not be pointing to the right server (or something)... will look more in a bit.  I make requests to the server directly, and see them in the logs. I make one through cloudfront (which misses cache, and should request data from the origin aserver) and I see nothing... so weird!

**Comment by sasignell** [comment]
it should be pointing to 52.2.5.122
<https://console.aws.amazon.com/ec2/v2/home?region=us-east-1#Addresses:search=52.2.5.122;sort=publicIp>,
correct?

On Fri, Nov 20, 2015 at 11:51 AM, Cary FitzHugh <notifications@github.com>
wrote:

> weird. the CDN may not be pointing to the right server (or something)...
> will look more in a bit. I make requests to the server directly, and see
> them in the logs. I make one through cloudfront (which misses cache, and
> should request data from the origin aserver) and I see nothing... so weird!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/caryfitzhugh/NYCCSC-map-viewer/issues/94#issuecomment-158457614>
> .
>



-- 
Steve Signell
Frontier Spatial, L.L.C.
1062 Dean St.
Schenectady, NY 12309
518-232-1008
frontierspatial.com
steve@frontierspatial.com

**Comment by caryfitzhugh** [comment]
I'll double check. just weird behavior. It's going *somewhere* for that
response.

**Comment by sasignell** [comment]
Sorry man, I just don't know much about all this cdn/elastic IP stuff...

On Fri, Nov 20, 2015 at 2:01 PM, Cary FitzHugh <notifications@github.com>
wrote:

> I'll double check. just weird behavior. It's going *somewhere* for that
> response.
>
> On Fri, Nov 20, 2015 at 12:40 PM, Steve Signell <notifications@github.com>
> wrote:
>
> > it should be pointing to 52.2.5.122
> > <
> >
> https://console.aws.amazon.com/ec2/v2/home?region=us-east-1#Addresses:search=52.2.5.122;sort=publicIp
> > >,
> > correct?
> >
> > On Fri, Nov 20, 2015 at 11:51 AM, Cary FitzHugh <
> notifications@github.com>
> > wrote:
> >
> > > weird. the CDN may not be pointing to the right server (or
> something)...
> > > will look more in a bit. I make requests to the server directly, and
> see
> > > them in the logs. I make one through cloudfront (which misses cache,
> and
> > > should request data from the origin aserver) and I see nothing... so
> > weird!
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/caryfitzhugh/NYCCSC-map-viewer/issues/94#issuecomment-158457614
> > >
> > > .
> > >
> >
> >
> >
> > --
> > Steve Signell
> > Frontier Spatial, L.L.C.
> > 1062 Dean St.
> > Schenectady, NY 12309
> > 518-232-1008
> > frontierspatial.com
> > steve@frontierspatial.com
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/caryfitzhugh/NYCCSC-map-viewer/issues/94#issuecomment-158469408
> >
> > .
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/caryfitzhugh/NYCCSC-map-viewer/issues/94#issuecomment-158495478>
> .
>



-- 
Steve Signell
Frontier Spatial, L.L.C.
1062 Dean St.
Schenectady, NY 12309
518-232-1008
frontierspatial.com
steve@frontierspatial.com

**Comment by caryfitzhugh** [comment]
ok, it was pointing to something in us-west.  I assume it's the old server.
That thing may still be running - so you might want to terminate it?  I found it, but won't shut it down since maybe you are still using it?
https://us-west-2.console.aws.amazon.com/ec2/v2/home?region=us-west-2#

I invalidated the CDN cache, so shortly it should be pulling fresh things.

**Comment by caryfitzhugh** [comment]
The CDN Url now returns the right data! CLosing!
