### ISSUE TITLE
gfi requests: don't open any modal if no data returned

### ISSUE THREAD

**Issue by sasignell** [caryfitzhugh/NYCCSC-map-viewer#95]
Right now we're still getting a blank modal if there's no features returned... It would be better if nothing at all happened... can the modal be suppressed in those cases?

**Comment by caryfitzhugh** [comment]
So - we can very easily hide the modal until something responds.  The
downside is that you click, and nothing happens for a few seconds.  SO
maybe you'd click again? I'll mockup having the modal just wait for some
content and see how "bad" it is.

**Comment by sasignell** [comment]
Maybe we could have a leaflet marker popup as a placeholder...with a little
timer or something-- if there's a result, it opens the modal, if not, it
just says no results?  Just a thought...

On Mon, Nov 23, 2015 at 8:21 AM, Cary FitzHugh <notifications@github.com>
wrote:

> So - we can very easily hide the modal until something responds. The
> downside is that you click, and nothing happens for a few seconds. SO
> maybe you'd click again? I'll mockup having the modal just wait for some
> content and see how "bad" it is.
>
> On Mon, Nov 23, 2015 at 7:27 AM, Steve Signell <notifications@github.com>
> wrote:
>
> > Assigned #95 <
> https://github.com/caryfitzhugh/NYCCSC-map-viewer/issues/95>
> > to @caryfitzhugh <https://github.com/caryfitzhugh>.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/caryfitzhugh/NYCCSC-map-viewer/issues/95#event-471985055
> >
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/caryfitzhugh/NYCCSC-map-viewer/issues/95#issuecomment-158931999>
> .
>



-- 
Steve Signell
Frontier Spatial, L.L.C.
1062 Dean St.
Schenectady, NY 12309
518-232-1008
frontierspatial.com
steve@frontierspatial.com

**Comment by caryfitzhugh** [comment]
hrm. ok.  looking.

**Comment by sasignell** [comment]
I can help with this if you want previously, I've created a 'dummy' marker
layer with nothing in it and then clear it out and place a marker at the
location clicked and (optionally) open a popup ,

e.g.

initialize:
var graphicMarker = L.layerGroup().addTo(map);

then in the function:
graphicMarker.clearLayers();
          L.marker([e.latlng.lat, e.latlng.lng], {
            clickable: false
          }).addTo(graphicMarker)
            .bindPopup(popupContent)
.openPopup();;




On Mon, Nov 23, 2015 at 9:24 AM, Cary FitzHugh <notifications@github.com>
wrote:

> hrm. ok. looking.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/caryfitzhugh/NYCCSC-map-viewer/issues/95#issuecomment-158947192>
> .
>



-- 
Steve Signell
Frontier Spatial, L.L.C.
1062 Dean St.
Schenectady, NY 12309
518-232-1008
frontierspatial.com
steve@frontierspatial.com

**Comment by caryfitzhugh** [comment]
I got the marker, i am just now workign on not showing the modal until it gets data.

**Comment by sasignell** [comment]
Cool--how does it look?  Is it an improvement?

On Mon, Nov 23, 2015 at 10:39 AM, Cary FitzHugh <notifications@github.com>
wrote:

> I got the marker, i am just now workign on not showing the modal until it
> gets data.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/caryfitzhugh/NYCCSC-map-viewer/issues/95#issuecomment-158971944>
> .
>



-- 
Steve Signell
Frontier Spatial, L.L.C.
1062 Dean St.
Schenectady, NY 12309
518-232-1008
frontierspatial.com
steve@frontierspatial.com

**Comment by caryfitzhugh** [comment]
sorry. working...

**Comment by caryfitzhugh** [comment]
Pushed to the gh-pages site.
try it out.

**Comment by caryfitzhugh** [comment]
I believe this is done right? @sasignell 

except for the marker... lemme see what I can do.
bah. I just don't know what you were thinking. I'm closing this, and we can add another task to fiddle the marker.
