### ISSUE TITLE
nfhl flood hazard draws above usgs_streamflow

### ISSUE THREAD

**Issue by sasignell** [caryfitzhugh/NYCCSC-map-viewer#97]
OK usgs_streamflow now seems to draw above all (yay!) but the nfhl layer...  I tried adding a zvalue to nfhl.js but didn't seem to help.  Maybe this is because its a esri layer?

**Comment by caryfitzhugh** [comment]
haha. well. I've done screwed something up.  
Lemme look.

**Comment by sasignell** [comment]
Hi Cary,
   Hope this didn't turn into a wormhole for you!

On Mon, Nov 23, 2015 at 11:45 AM, Cary FitzHugh <notifications@github.com>
wrote:

> haha. well. I've done screwed something up.
>
> Lemme look.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/caryfitzhugh/NYCCSC-map-viewer/issues/97#issuecomment-158991931>
> .
>



-- 
Steve Signell
Frontier Spatial, L.L.C.
1062 Dean St.
Schenectady, NY 12309
518-232-1008
frontierspatial.com
steve@frontierspatial.com

**Comment by caryfitzhugh** [comment]
noaa_slr, sandysurge, nfhl are all esri-dynamic-map layers.
They are added as "overlay" layers.

I don't have time to do this right now, but I think the esriDynamicLayers need to have added code to set their ZIndex correctly.  This shouldn't be too bad.

The same goes for the GeoJSON usgs_streamflow layer. I need to find a way to set it's markers to the "overlay" zindex.  

I fiddled for a bit tongiht, but couldn't get something set that works.  Argh.  
And this week changed a bit - I need to do family / Thanksgiving stuff...

**Comment by sasignell** [comment]
No problem....let's regroup next week.  Have a  good thanksgiving!

**Comment by caryfitzhugh** [comment]
You too... and colin as well!

**Comment by caryfitzhugh** [comment]
looking at the esri dynamic layers and their ability to work within the architecture.

**Comment by caryfitzhugh** [comment]
done. the SVG layer that the path is working with now respects the zindex and opacity.
