### ISSUE TITLE
TACCIMO Layer Updates

### ISSUE THREAD

**Issue by caryfitzhugh** [caryfitzhugh/NYCCSC-map-viewer#99]
The taccimo layer was added recently.

* Make sure that it is behind a CDN
* convert the radio buttons to a slider for scenario with three discrete values: Current,Low,High (values 0,112,56)
* species should be a dropdown instead of radio since we have so many species.

**Comment by colinbeier** [comment]
Also... some edits to metadata for this layer

Name: USFS Climate Change Atlas - Tree Species
Description: The Climate Change Atlas documents the current and possible future distribution of 134 tree species and 147 bird species in the Eastern United States and gives detailed information on environmental characteristics defining these distributions. 
Source: USDA Forest Service Northern Research Station

**Comment by colinbeier** [comment]
also, Emissions is misspelled in the legend

**Comment by caryfitzhugh** [comment]
closing. only thing I didn't do is CDN. that comes in #88
